/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public enum CompressionMethod {

    /**
     * No compression is applied; data is stored 'as is'
     */
    None(0),
    /**
     * Voxel values are compressed using a lossy wavelet compression algorithm. This usually produces excellent results for continuous data, but is not applicable when dealing with discrete values.
     */
    Wavelet(1),
    /**
     * Voxel values are compressed using run-length encoding which is a fast, lossless algorithm. This gives good results when the same value is often repeated for adjacent voxels, for example classification data.
     */
    RLE(2),
    /**
     * Voxel values are compressed using zip (zlib) which is a slower, lossless algorithm that gives fairly good compression for all types of data.
     */
    Zip(3),
    /**
     * This method is experimental and no guarantee is made that decompression for data compressed in this format will be supported in future versions. Voxel values are compressed using a lossy wavelet compression algorithm. Also the threshold takes into account the absolute average of each block. This is good for data that varies a lot in signal strength. This usually produces excellent results for continuous data, but is not applicable when dealing with discrete values.
     */
    WaveletNormalizeBlock(4),
    /**
     * Voxel values are compressed using a losslees wavelet compression algorithm. This usually produces excellent results for continuous data, but is not applicable when dealing with discrete values.
     */
    WaveletLossless(5),
    /**
     * This method is experimental and no guarantee is made that decompression for data compressed in this format will be supported in future versions. Voxel values are compressed using a lossless wavelet compression algorithm. Also the threshold takes into account the absolute average of each block. This is good for data that varies a lot in signal strength. This usually produces excellent results for continuous data, but is not applicable when dealing with discrete values.
     */
    WaveletNormalizeBlockLossless(6);

    private final int value;

    CompressionMethod(int value) {
        this.value = value;
    }

    public int value() {
        return this.value;
    }

    public static CompressionMethod fromInt(int value) {
        if (value == 0) return None;
        if (value == 1) return Wavelet;
        if (value == 2) return RLE;
        if (value == 3) return Zip;
        if (value == 4) return WaveletNormalizeBlock;
        if (value == 5) return WaveletLossless;
        if (value == 6) return WaveletNormalizeBlockLossless;
        return CompressionMethod.values()[0];
    }

}
