
/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.opengroup.openvds;
import java.nio.*;

// THIS FILE WAS AUTOGENERATED BY 'make-vector-classes.py' DO NOT EDIT!

public class DoubleMatrix3x3 extends ByteBufferBackedObject {

    public DoubleMatrix3x3() {
        this.createByteBuffer(Double.BYTES * 3 * 3);
        getManagedBuffer().putDouble(this.getByteBufferOffset() + DoubleVector3.BYTES * 0 + Double.BYTES * 0, 1.0);
        getManagedBuffer().putDouble(this.getByteBufferOffset() + DoubleVector3.BYTES * 1 + Double.BYTES * 1, 1.0);
        getManagedBuffer().putDouble(this.getByteBufferOffset() + DoubleVector3.BYTES * 2 + Double.BYTES * 2, 1.0);        
    }

    public DoubleVector3 getX() {
        return new DoubleVector3(this.getBackingByteBuffer(), this.getByteBufferOffset() + Double.BYTES * 3 * 0);
    }


    public DoubleVector3 getY() {
        return new DoubleVector3(this.getBackingByteBuffer(), this.getByteBufferOffset() + Double.BYTES * 3 * 1);
    }


    public DoubleVector3 getZ() {
        return new DoubleVector3(this.getBackingByteBuffer(), this.getByteBufferOffset() + Double.BYTES * 3 * 2);
    }

    public void setX(DoubleVector3 value) {
          this.getX().put(this.getManagedBuffer(), this.getByteBufferOffset() + Double.BYTES * 3 * 0);
    }


    public void setY(DoubleVector3 value) {
          this.getY().put(this.getManagedBuffer(), this.getByteBufferOffset() + Double.BYTES * 3 * 1);
    }


    public void setZ(DoubleVector3 value) {
          this.getZ().put(this.getManagedBuffer(), this.getByteBufferOffset() + Double.BYTES * 3 * 2);
    }

    public String toString() {
        String value = "(";
        for (int i = 0; i < 3; ++i)
        {
            if (i > 0)
                value = value + ", ";
            value = value + "X(" + this.getX().toString() + ")";
            value = value + "Y(" + this.getY().toString() + ")";
            value = value + "Z(" + this.getZ().toString() + ")";
        }
        value = value + ")";
        return value;
    }

    public boolean equals(Object other) {
        if (other == this) return true;
        if (other == null) return false;
        if (getClass() != other.getClass()) return false;
        DoubleMatrix3x3 real_other = (DoubleMatrix3x3)other;
        return (this.getX().equals(real_other.getX()) &&
                this.getY().equals(real_other.getY()) &&
                this.getZ().equals(real_other.getZ()));
    }

    public static final int BYTES = Double.BYTES * 3 * 3;
}

