/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public class IndexRegionIntVector2 extends ManagedBase {

    ///AUTOGEN-OK: FIELD_DECL Min type-parameter-0-0 UNEXPOSED
    native private void getMinImpl(long native_object, ByteBuffer result, long result_byteoffset);
    public IntVector2 getMin() {
        IntVector2 result = new IntVector2();
        getMinImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset());
        return result;
    }

    native private void setMinImpl(long native_object, ByteBuffer value, long value_byteoffset);
    
    public void setMin(IntVector2 value) {
    
        setMinImpl(getNativeObject(), ManagedBase.requireNonNull(value, "value may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(value, "value may not be null").getByteBufferOffset());    
    
    }

    ///AUTOGEN-OK: FIELD_DECL Max type-parameter-0-0 UNEXPOSED
    native private void getMaxImpl(long native_object, ByteBuffer result, long result_byteoffset);
    public IntVector2 getMax() {
        IntVector2 result = new IntVector2();
        getMaxImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset());
        return result;
    }

    native private void setMaxImpl(long native_object, ByteBuffer value, long value_byteoffset);
    
    public void setMax(IntVector2 value) {
    
        setMaxImpl(getNativeObject(), ManagedBase.requireNonNull(value, "value may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(value, "value may not be null").getByteBufferOffset());    
    
    }

    native private static long ctorImpl();
    
    public IndexRegionIntVector2() {
    
        super(ctorImpl());
    
    }

    native private static long ctor2Impl(ByteBuffer Min, long Min_byteoffset, ByteBuffer Max, long Max_byteoffset);
    
    public IndexRegionIntVector2(IntVector2 Min, IntVector2 Max) {
    
        super(ctor2Impl(ManagedBase.requireNonNull(Min, "Min may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(Min, "Min may not be null").getByteBufferOffset(), ManagedBase.requireNonNull(Max, "Max may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(Max, "Max may not be null").getByteBufferOffset()));
    
    }

    IndexRegionIntVector2(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject, boolean isDisposing);

    @Override
    protected void onDisposing(long native_object, boolean isDisposing) {
        dtorImpl(native_object, isDisposing);
    }

    static IndexRegionIntVector2 fromNativeObject(long nativeobject) {
        if (nativeobject == 0) {
           return null;
        }
        return new IndexRegionIntVector2(nativeobject);
    }




}
