/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public enum MetadataType {

        Int(0),
        IntVector2(1),
        IntVector3(2),
        IntVector4(3),
        Float(4),
        FloatVector2(5),
        FloatVector3(6),
        FloatVector4(7),
        Double(8),
        DoubleVector2(9),
        DoubleVector3(10),
        DoubleVector4(11),
        String(12),
        BLOB(13);

    private final int value;

    MetadataType(int value) {
        this.value = value;
    }

    public int value() {
        return this.value;
    }

    public static MetadataType fromInt(int value) {
        if (value == 0) return Int;
        if (value == 1) return IntVector2;
        if (value == 2) return IntVector3;
        if (value == 3) return IntVector4;
        if (value == 4) return Float;
        if (value == 5) return FloatVector2;
        if (value == 6) return FloatVector3;
        if (value == 7) return FloatVector4;
        if (value == 8) return Double;
        if (value == 9) return DoubleVector2;
        if (value == 10) return DoubleVector3;
        if (value == 11) return DoubleVector4;
        if (value == 12) return String;
        if (value == 13) return BLOB;
        return MetadataType.values()[0];
    }

}
