/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public class VolumeData {
	static {
		/* Ensure jni wrapper library is loaded */
		ManagedBase.staticInit();
	}

    ///AUTOGEN-OK: FUNCTION_DECL CompressionMethod_IsWavelet bool (OpenVDS::CompressionMethod) FUNCTIONPROTO
    native private static boolean CompressionMethod_IsWaveletImpl(long compressionMethod);
    public static boolean compressionMethod_IsWavelet(CompressionMethod compressionMethod) {
        return CompressionMethod_IsWaveletImpl(ManagedBase.requireNonNull(compressionMethod, "compressionMethod may not be null").value());
    }

    ///AUTOGEN-OK: FUNCTION_DECL GetLODSize int (int, int, int, bool) FUNCTIONPROTO
    native private static int GetLODSizeImpl(int voxelMin, int voxelMax, int LOD, boolean includePartialUpperVoxel);

    /**
     * Get the number of voxels at a particular LOD from a voxel range (ranges are exclusive).
     * 
     * @param voxelMin The minimum voxel index of the range.
     * @param voxelMax The maximum voxel index of the range (ranges are exclusive, so the range does not include voxelMax).
     * @param includePartialUpperVoxel This controls the rounding. Usually you want the size of the range to be all voxels in the range, but when we are copying from multiple adjacent ranges we only want to round up for the last one.
     * @param LOD The LOD level for which the size is requested.
     */
    public static int getLODSize(int voxelMin, int voxelMax, int LOD, boolean includePartialUpperVoxel) {
        return GetLODSizeImpl(voxelMin, voxelMax, LOD, includePartialUpperVoxel);
    }

    ///AUTOGEN-OK: FUNCTION_DECL VolumeDataHash_IsDefined bool (uint64_t) FUNCTIONPROTO
    native private static boolean VolumeDataHash_IsDefinedImpl(long volumeDataHash);

    /**
     * Determine whether the given volume data hash is defined.
     * 
     */
    public static boolean volumeDataHash_IsDefined(long volumeDataHash) {
        return VolumeDataHash_IsDefinedImpl(volumeDataHash);
    }

    ///AUTOGEN-OK: FUNCTION_DECL VolumeDataHash_IsNoValue bool (uint64_t) FUNCTIONPROTO
    native private static boolean VolumeDataHash_IsNoValueImpl(long volumeDataHash);

    /**
     * Determine whether the given volume data hash is the no-data-value.
     * 
     */
    public static boolean volumeDataHash_IsNoValue(long volumeDataHash) {
        return VolumeDataHash_IsNoValueImpl(volumeDataHash);
    }

    ///AUTOGEN-OK: FUNCTION_DECL VolumeDataHash_IsConstant bool (uint64_t) FUNCTIONPROTO
    native private static boolean VolumeDataHash_IsConstantImpl(long volumeDataHash);

    /**
     * Determine whether the given volume data hash is constant.
     * 
     */
    public static boolean volumeDataHash_IsConstant(long volumeDataHash) {
        return VolumeDataHash_IsConstantImpl(volumeDataHash);
    }


}

///AUTOGEN-IGNORE: FUNCTION_DECL ReadElement bool (const bool *, uint64_t) FUNCTIONPROTO
///AUTOGEN-IGNORE: FUNCTION_DECL WriteElement void (bool *, uint64_t, bool) FUNCTIONPROTO
///AUTOGEN-IGNORE: FUNCTION_DECL PitchScale int () FUNCTIONPROTO
