/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;

/**
 * Describes the number of samples, name, unit and coordinates (annotation) of an axis (dimension) of the volume
 * 
 */
public class VolumeDataAxisDescriptor extends ManagedBase {

    native private static long ctorImpl();
    
    /**
     * Default constructor
     * 
     */
    public VolumeDataAxisDescriptor() {
    
        super(ctorImpl());
    
    }

    native private static long ctor2Impl(int numSamples, String name, String unit, float coordinateMin, float coordinateMax);
    
    /**
     * Constructor
     * 
     * @param numSamples The number of samples along this axis
     * @param name The name of this axis
     * @param unit The unit of the coordinates of this axis
     * @param coordinateMin The coordinate of the first sample of this axis
     * @param coordinateMax The coordinate of the last sample of this axis
     */
    public VolumeDataAxisDescriptor(int numSamples, String name, String unit, float coordinateMin, float coordinateMax) {
    
        super(ctor2Impl(numSamples, ManagedBase.requireNonNull(name, "name may not be null"), ManagedBase.requireNonNull(unit, "unit may not be null"), coordinateMin, coordinateMax));
    
    }

    ///AUTOGEN-OK: CXX_METHOD GetNumSamples int () const FUNCTIONPROTO
    native private int GetNumSamplesImpl(long native_object);

    /**
     * Get the number of samples along this axis
     * 
     * @return The number of samples along this axis
     */
    public int getNumSamples() {
        return GetNumSamplesImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetName const char *() const FUNCTIONPROTO
    native private String GetNameImpl(long native_object);

    /**
     * Get the name of this axis
     * 
     * @return The name of this axis
     */
    public String getName() {
        return GetNameImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetUnit const char *() const FUNCTIONPROTO
    native private String GetUnitImpl(long native_object);

    /**
     * Get the unit of the coordinates of this axis
     * 
     * @return The unit of the coordinates of this axis
     */
    public String getUnit() {
        return GetUnitImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetCoordinateMin float () const FUNCTIONPROTO
    native private float GetCoordinateMinImpl(long native_object);

    /**
     * Get the coordinate of the first sample of this axis
     * 
     * @return The coordinate of the first sample of this axis
     */
    public float getCoordinateMin() {
        return GetCoordinateMinImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetCoordinateMax float () const FUNCTIONPROTO
    native private float GetCoordinateMaxImpl(long native_object);

    /**
     * Get the coordinate of the last sample of this axis
     * 
     * @return The coordinate of the last sample of this axis
     */
    public float getCoordinateMax() {
        return GetCoordinateMaxImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetCoordinateStep float () const FUNCTIONPROTO
    native private float GetCoordinateStepImpl(long native_object);

    /**
     * Get the coordiante step size per sample
     * 
     * @return The coordiante step size per sample
     */
    public float getCoordinateStep() {
        return GetCoordinateStepImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD SampleIndexToCoordinate float (int) FUNCTIONPROTO
    native private float SampleIndexToCoordinateImpl(long native_object, int sampleIndex);

    /**
     * Convert a sample index on this axis to a coordinate
     * 
     * @param sampleIndex The sample index get the coordinate of
     * @return The coordinate of the sample index
     */
    public float sampleIndexToCoordinate(int sampleIndex) {
        return SampleIndexToCoordinateImpl(getNativeObject(), sampleIndex);
    }

    ///AUTOGEN-OK: CXX_METHOD CoordinateToSampleIndex int (float) FUNCTIONPROTO
    native private int CoordinateToSampleIndexImpl(long native_object, float coordinate);

    /**
     * Convert a coordinate to a sample index (rounding to the closest index)
     * 
     * @param coordinate The coordinate to get the sample index of
     * @return The sample index of the coordinate
     */
    public int coordinateToSampleIndex(float coordinate) {
        return CoordinateToSampleIndexImpl(getNativeObject(), coordinate);
    }

    ///AUTOGEN-OK: CXX_METHOD CoordinateToSamplePosition float (float) FUNCTIONPROTO
    native private float CoordinateToSamplePositionImpl(long native_object, float coordinate);

    /**
     * Convert a coordinate to a sample position (to use with RequestVolumeSamples or an InterpolatingVolumeDataAccessor)
     * 
     * @param coordinate The coordinate to get the sample position of
     * @return The sample position of the coordinate
     */
    public float coordinateToSamplePosition(float coordinate) {
        return CoordinateToSamplePositionImpl(getNativeObject(), coordinate);
    }

    VolumeDataAxisDescriptor(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject, boolean isDisposing);

    @Override
    protected void onDisposing(long native_object, boolean isDisposing) {
        dtorImpl(native_object, isDisposing);
    }

    static VolumeDataAxisDescriptor fromNativeObject(long nativeobject) {
        if (nativeobject == 0) {
           return null;
        }
        return new VolumeDataAxisDescriptor(nativeobject);
    }




}
