//=============================================================================
// <copyright>
// Copyright (c) 2021 Bluware Inc. All rights reserved.
//
// All rights are reserved. Reproduction or transmission in whole or in part,
// in any form or by any means, electronic, mechanical or otherwise,
// is prohibited without the prior written permission of the copyright owner.
// </copyright>
//=============================================================================


// THIS FILE IS AUTOGENERATED. DO NOT EDIT!

//#pragma warning(disable : 4996) // Hide exception warning from VolumeDataAccess.h

#include "Marshaling.h"


#include "MetadataContainer.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_MetadataContainer_IsMetadataIntAvailableImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->IsMetadataIntAvailable(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_MetadataContainer_IsMetadataIntVector2AvailableImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->IsMetadataIntVector2Available(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_MetadataContainer_IsMetadataIntVector3AvailableImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->IsMetadataIntVector3Available(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_MetadataContainer_IsMetadataIntVector4AvailableImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->IsMetadataIntVector4Available(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_MetadataContainer_IsMetadataFloatAvailableImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->IsMetadataFloatAvailable(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_MetadataContainer_IsMetadataFloatVector2AvailableImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->IsMetadataFloatVector2Available(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_MetadataContainer_IsMetadataFloatVector3AvailableImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->IsMetadataFloatVector3Available(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_MetadataContainer_IsMetadataFloatVector4AvailableImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->IsMetadataFloatVector4Available(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_MetadataContainer_IsMetadataDoubleAvailableImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->IsMetadataDoubleAvailable(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_MetadataContainer_IsMetadataDoubleVector2AvailableImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->IsMetadataDoubleVector2Available(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_MetadataContainer_IsMetadataDoubleVector3AvailableImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->IsMetadataDoubleVector3Available(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_MetadataContainer_IsMetadataDoubleVector4AvailableImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->IsMetadataDoubleVector4Available(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_MetadataContainer_IsMetadataStringAvailableImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->IsMetadataStringAvailable(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_MetadataContainer_IsMetadataBLOBAvailableImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->IsMetadataBLOBAvailable(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jint JNICALL Java_com_hue_proxylib_MetadataContainer_GetMetadataIntImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->GetMetadataInt(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_GetMetadataIntVector2Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->GetMetadataIntVector2(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name));
    *(OpenVDS::IntVector2*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_GetMetadataIntVector3Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->GetMetadataIntVector3(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name));
    *(OpenVDS::IntVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_GetMetadataIntVector4Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->GetMetadataIntVector4(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name));
    *(OpenVDS::IntVector4*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  HUE_JNI_CATCH
}

JNIEXPORT jfloat JNICALL Java_com_hue_proxylib_MetadataContainer_GetMetadataFloatImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->GetMetadataFloat(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_GetMetadataFloatVector2Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->GetMetadataFloatVector2(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name));
    *(OpenVDS::FloatVector2*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_GetMetadataFloatVector3Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->GetMetadataFloatVector3(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name));
    *(OpenVDS::FloatVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_GetMetadataFloatVector4Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->GetMetadataFloatVector4(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name));
    *(OpenVDS::FloatVector4*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  HUE_JNI_CATCH
}

JNIEXPORT jdouble JNICALL Java_com_hue_proxylib_MetadataContainer_GetMetadataDoubleImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->GetMetadataDouble(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_GetMetadataDoubleVector2Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->GetMetadataDoubleVector2(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name));
    *(OpenVDS::DoubleVector2*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_GetMetadataDoubleVector3Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->GetMetadataDoubleVector3(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name));
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_GetMetadataDoubleVector4Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->GetMetadataDoubleVector4(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name));
    *(OpenVDS::DoubleVector4*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  HUE_JNI_CATCH
}

JNIEXPORT jstring JNICALL Java_com_hue_proxylib_MetadataContainer_GetMetadataStringImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    auto result = pInstance->GetMetadataString(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
    return HueJNI_newString(env, result);
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataIntImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jint value)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataInt(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               value);
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataIntVector2Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataIntVector2(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNI_cast<OpenVDS::Vector<int, 2>>(value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataIntVector3Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataIntVector3(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNI_cast<OpenVDS::Vector<int, 3>>(value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataIntVector4Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataIntVector4(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNI_cast<OpenVDS::Vector<int, 4>>(value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataFloatImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jfloat value)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataFloat(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               value);
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataFloatVector2Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataFloatVector2(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNI_cast<OpenVDS::Vector<float, 2>>(value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataFloatVector3Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataFloatVector3(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNI_cast<OpenVDS::Vector<float, 3>>(value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataFloatVector4Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataFloatVector4(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNI_cast<OpenVDS::Vector<float, 4>>(value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataDoubleImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jdouble value)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataDouble(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               value);
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataDoubleVector2Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataDoubleVector2(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNI_cast<OpenVDS::Vector<double, 2>>(value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataDoubleVector3Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataDoubleVector3(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNI_cast<OpenVDS::Vector<double, 3>>(value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataDoubleVector4Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataDoubleVector4(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNI_cast<OpenVDS::Vector<double, 4>>(value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataStringImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jstring value)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataString(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNIStringWrapper(env, native_handle, value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataBLOBImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject data)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto tmpdata = HueJNIAsyncBuffer<void>(env, data);
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataBLOB(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               tmpdata.buffer(), tmpdata.byteSize());
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_CopyMetadataImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jlong metadataReadAccess)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->CopyMetadata(HueJNIStringWrapper(env, native_handle, category), HueJNI_cast<OpenVDS::MetadataReadAccess>(metadataReadAccess));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_ClearMetadataImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->ClearMetadata(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_ClearMetadata2Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->ClearMetadata(HueJNIStringWrapper(env, native_handle, category));
  }
  HUE_JNI_CATCH
}
///AUTOGEN-FAIL: CXX_METHOD GetMetadataBLOB void (const char *, const char *, const void **, uint64_t *) const FUNCTIONPROTO

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataIntImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jint value)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataInt(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               value);
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataIntVector2Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataIntVector2(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNI_cast<OpenVDS::Vector<int, 2>>(value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataIntVector3Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataIntVector3(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNI_cast<OpenVDS::Vector<int, 3>>(value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataIntVector4Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataIntVector4(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNI_cast<OpenVDS::Vector<int, 4>>(value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataFloatImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jfloat value)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataFloat(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               value);
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataFloatVector2Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataFloatVector2(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNI_cast<OpenVDS::Vector<float, 2>>(value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataFloatVector3Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataFloatVector3(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNI_cast<OpenVDS::Vector<float, 3>>(value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataFloatVector4Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataFloatVector4(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNI_cast<OpenVDS::Vector<float, 4>>(value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataDoubleImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jdouble value)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataDouble(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               value);
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataDoubleVector2Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataDoubleVector2(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNI_cast<OpenVDS::Vector<double, 2>>(value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataDoubleVector3Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataDoubleVector3(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNI_cast<OpenVDS::Vector<double, 3>>(value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataDoubleVector4Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataDoubleVector4(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNI_cast<OpenVDS::Vector<double, 4>>(value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataStringImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jstring value)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataString(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNIStringWrapper(env, native_handle, value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataString2Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jstring value)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataString(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               HueJNIStringWrapper(env, native_handle, value));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_SetMetadataBLOBImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name, jobject data)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto tmpdata = HueJNIAsyncBuffer<void>(env, data);
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->SetMetadataBLOB(
                               HueJNIStringWrapper(env, native_handle, category), 
                               HueJNIStringWrapper(env, native_handle, name), 
                               tmpdata.buffer(), tmpdata.byteSize());
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_CopyMetadataImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jlong metadataReadAccess)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->CopyMetadata(HueJNIStringWrapper(env, native_handle, category), HueJNI_cast<OpenVDS::MetadataReadAccess>(metadataReadAccess));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_ClearMetadataImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category, jstring name)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->ClearMetadata(HueJNIStringWrapper(env, native_handle, category), HueJNIStringWrapper(env, native_handle, name));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_ClearMetadata2Impl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring category)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::MetadataContainer>(native_handle);
    pInstance->ClearMetadata(HueJNIStringWrapper(env, native_handle, category));
  }
  HUE_JNI_CATCH
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_MetadataContainer_dtorImpl
  (JNIEnv * env, jobject object, jlong native_handle)
{
  HUE_JNI_TRY
  {
    HueJNI_destroyHandle<OpenVDS::MetadataContainer>(env, native_handle);
  }
  HUE_JNI_CATCH
}



#ifdef __cplusplus
}
#endif
