/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


// THIS FILE IS AUTOGENERATED. DO NOT EDIT!

//#pragma warning(disable : 4996) // Hide exception warning from VolumeDataAccess.h

#include "Marshaling.h"


#include "MetadataAccess.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_MetadataReadAccess_IsMetadataIntAvailableImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->IsMetadataIntAvailable(CPPJNIStringWrapper(env, native_handle, category), CPPJNIStringWrapper(env, native_handle, name));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_MetadataReadAccess_IsMetadataIntVector2AvailableImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->IsMetadataIntVector2Available(CPPJNIStringWrapper(env, native_handle, category), CPPJNIStringWrapper(env, native_handle, name));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_MetadataReadAccess_IsMetadataIntVector3AvailableImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->IsMetadataIntVector3Available(CPPJNIStringWrapper(env, native_handle, category), CPPJNIStringWrapper(env, native_handle, name));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_MetadataReadAccess_IsMetadataIntVector4AvailableImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->IsMetadataIntVector4Available(CPPJNIStringWrapper(env, native_handle, category), CPPJNIStringWrapper(env, native_handle, name));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_MetadataReadAccess_IsMetadataFloatAvailableImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->IsMetadataFloatAvailable(CPPJNIStringWrapper(env, native_handle, category), CPPJNIStringWrapper(env, native_handle, name));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_MetadataReadAccess_IsMetadataFloatVector2AvailableImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->IsMetadataFloatVector2Available(CPPJNIStringWrapper(env, native_handle, category), CPPJNIStringWrapper(env, native_handle, name));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_MetadataReadAccess_IsMetadataFloatVector3AvailableImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->IsMetadataFloatVector3Available(CPPJNIStringWrapper(env, native_handle, category), CPPJNIStringWrapper(env, native_handle, name));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_MetadataReadAccess_IsMetadataFloatVector4AvailableImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->IsMetadataFloatVector4Available(CPPJNIStringWrapper(env, native_handle, category), CPPJNIStringWrapper(env, native_handle, name));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_MetadataReadAccess_IsMetadataDoubleAvailableImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->IsMetadataDoubleAvailable(CPPJNIStringWrapper(env, native_handle, category), CPPJNIStringWrapper(env, native_handle, name));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_MetadataReadAccess_IsMetadataDoubleVector2AvailableImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->IsMetadataDoubleVector2Available(CPPJNIStringWrapper(env, native_handle, category), CPPJNIStringWrapper(env, native_handle, name));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_MetadataReadAccess_IsMetadataDoubleVector3AvailableImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->IsMetadataDoubleVector3Available(CPPJNIStringWrapper(env, native_handle, category), CPPJNIStringWrapper(env, native_handle, name));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_MetadataReadAccess_IsMetadataDoubleVector4AvailableImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->IsMetadataDoubleVector4Available(CPPJNIStringWrapper(env, native_handle, category), CPPJNIStringWrapper(env, native_handle, name));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_MetadataReadAccess_IsMetadataStringAvailableImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->IsMetadataStringAvailable(CPPJNIStringWrapper(env, native_handle, category), CPPJNIStringWrapper(env, native_handle, name));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_MetadataReadAccess_IsMetadataBLOBAvailableImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->IsMetadataBLOBAvailable(CPPJNIStringWrapper(env, native_handle, category), CPPJNIStringWrapper(env, native_handle, name));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jint JNICALL Java_org_opengroup_openvds_MetadataReadAccess_GetMetadataIntImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->GetMetadataInt(CPPJNIStringWrapper(env, native_handle, category), CPPJNIStringWrapper(env, native_handle, name));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataReadAccess_GetMetadataIntVector2Impl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->GetMetadataIntVector2(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name));
    *(OpenVDS::IntVector2*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataReadAccess_GetMetadataIntVector3Impl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->GetMetadataIntVector3(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name));
    *(OpenVDS::IntVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataReadAccess_GetMetadataIntVector4Impl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->GetMetadataIntVector4(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name));
    *(OpenVDS::IntVector4*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT jfloat JNICALL Java_org_opengroup_openvds_MetadataReadAccess_GetMetadataFloatImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->GetMetadataFloat(CPPJNIStringWrapper(env, native_handle, category), CPPJNIStringWrapper(env, native_handle, name));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataReadAccess_GetMetadataFloatVector2Impl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->GetMetadataFloatVector2(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name));
    *(OpenVDS::FloatVector2*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataReadAccess_GetMetadataFloatVector3Impl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->GetMetadataFloatVector3(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name));
    *(OpenVDS::FloatVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataReadAccess_GetMetadataFloatVector4Impl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->GetMetadataFloatVector4(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name));
    *(OpenVDS::FloatVector4*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT jdouble JNICALL Java_org_opengroup_openvds_MetadataReadAccess_GetMetadataDoubleImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->GetMetadataDouble(CPPJNIStringWrapper(env, native_handle, category), CPPJNIStringWrapper(env, native_handle, name));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataReadAccess_GetMetadataDoubleVector2Impl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->GetMetadataDoubleVector2(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name));
    *(OpenVDS::DoubleVector2*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataReadAccess_GetMetadataDoubleVector3Impl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->GetMetadataDoubleVector3(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name));
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataReadAccess_GetMetadataDoubleVector4Impl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->GetMetadataDoubleVector4(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name));
    *(OpenVDS::DoubleVector4*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT jstring JNICALL Java_org_opengroup_openvds_MetadataReadAccess_GetMetadataStringImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    auto result = pInstance->GetMetadataString(CPPJNIStringWrapper(env, native_handle, category), CPPJNIStringWrapper(env, native_handle, name));
    return CPPJNI_newString(env, result);
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataReadAccess_dtorImpl
  (JNIEnv * env, jobject object, jlong native_handle, jboolean is_disposing)
{
  CPPJNI_TRY
  {
    CPPJNI_destroyHandle<OpenVDS::MetadataReadAccess>(env, native_handle);
  }
  CPPJNI_CATCH
}


#include <algorithm>

JNIEXPORT jintArray JNICALL Java_org_opengroup_openvds_MetadataReadAccess_GetMetadataKeyTypesImpl
(JNIEnv* env, jobject object, jlong native_handle)
{
  using namespace OpenVDS;

  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);

    auto lsKey = pInstance->GetMetadataKeys();

    jsize nKey = (jsize)std::distance(lsKey.begin(), lsKey.end());

    jintArray metadata_key_types = env->NewIntArray(nKey);

    jsize iKey = 0;
    for (const auto& key : lsKey)
    {
      jint keyType = (int)key.GetType();
      env->SetIntArrayRegion(metadata_key_types, iKey, 1, &keyType);
      iKey++;
    }

    return metadata_key_types;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jobjectArray JNICALL Java_org_opengroup_openvds_MetadataReadAccess_GetMetadataKeyCategoriesImpl
(JNIEnv* env, jobject object, jlong native_handle)
{
  using namespace OpenVDS;

  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);

    auto lsKey = pInstance->GetMetadataKeys();

    jsize nKey = (jsize)std::distance(lsKey.begin(), lsKey.end());

    jobjectArray metadata_key_categories = (jobjectArray)env->NewObjectArray(nKey, env->FindClass("java/lang/String"), env->NewStringUTF(""));

    jsize iKey = 0;
    for (const auto& key : lsKey)
    {
      env->SetObjectArrayElement(metadata_key_categories, iKey, env->NewStringUTF(key.GetCategory()));
      iKey++;
    }

    return metadata_key_categories;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jobjectArray JNICALL Java_org_opengroup_openvds_MetadataReadAccess_GetMetadataKeyNamesImpl
(JNIEnv* env, jobject object, jlong native_handle)
{
  using namespace OpenVDS;

  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);

    auto lsKey = pInstance->GetMetadataKeys();

    jsize nKey = (jsize)std::distance(lsKey.begin(), lsKey.end());

    jobjectArray metadata_key_names = (jobjectArray)env->NewObjectArray(nKey, env->FindClass("java/lang/String"), env->NewStringUTF(""));

    jsize iKey = 0;
    for (const auto& key : lsKey)
    {
      env->SetObjectArrayElement(metadata_key_names, iKey, env->NewStringUTF(key.GetName()));
      iKey++;
    }

    return metadata_key_names;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jbyteArray JNICALL Java_org_opengroup_openvds_MetadataReadAccess_GetMetadataBLOBImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataReadAccess>(native_handle);
    std::vector<uint8_t> data;
    pInstance->GetMetadataBLOB(CPPJNIStringWrapper(env, category), CPPJNIStringWrapper(env, name), data);
    if (data.size() > UINT_MAX) 
    {
      throw std::runtime_error("BLOB is too big for Java bytearray.");
    }
    jbyteArray arr = env->NewByteArray((jsize)data.size());
    env->SetByteArrayRegion(arr, 0, (jsize)data.size(), (jbyte const*)data.data());
    return arr;
  }
  CPPJNI_CATCH
  return 0;
}



JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataWriteAccess_SetMetadataIntImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name, jint value)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataWriteAccess>(native_handle);
    pInstance->SetMetadataInt(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name), 
                               value);
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataWriteAccess_SetMetadataIntVector2Impl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataWriteAccess>(native_handle);
    pInstance->SetMetadataIntVector2(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name), 
                               CPPJNIByteBufferAdapter<OpenVDS::IntVector2>(env, valuebytebuffer, valuebyteoffset));
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataWriteAccess_SetMetadataIntVector3Impl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataWriteAccess>(native_handle);
    pInstance->SetMetadataIntVector3(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name), 
                               CPPJNIByteBufferAdapter<OpenVDS::IntVector3>(env, valuebytebuffer, valuebyteoffset));
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataWriteAccess_SetMetadataIntVector4Impl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataWriteAccess>(native_handle);
    pInstance->SetMetadataIntVector4(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name), 
                               CPPJNIByteBufferAdapter<OpenVDS::IntVector4>(env, valuebytebuffer, valuebyteoffset));
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataWriteAccess_SetMetadataFloatImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name, jfloat value)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataWriteAccess>(native_handle);
    pInstance->SetMetadataFloat(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name), 
                               value);
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataWriteAccess_SetMetadataFloatVector2Impl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataWriteAccess>(native_handle);
    pInstance->SetMetadataFloatVector2(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name), 
                               CPPJNIByteBufferAdapter<OpenVDS::FloatVector2>(env, valuebytebuffer, valuebyteoffset));
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataWriteAccess_SetMetadataFloatVector3Impl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataWriteAccess>(native_handle);
    pInstance->SetMetadataFloatVector3(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name), 
                               CPPJNIByteBufferAdapter<OpenVDS::FloatVector3>(env, valuebytebuffer, valuebyteoffset));
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataWriteAccess_SetMetadataFloatVector4Impl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataWriteAccess>(native_handle);
    pInstance->SetMetadataFloatVector4(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name), 
                               CPPJNIByteBufferAdapter<OpenVDS::FloatVector4>(env, valuebytebuffer, valuebyteoffset));
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataWriteAccess_SetMetadataDoubleImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name, jdouble value)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataWriteAccess>(native_handle);
    pInstance->SetMetadataDouble(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name), 
                               value);
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataWriteAccess_SetMetadataDoubleVector2Impl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataWriteAccess>(native_handle);
    pInstance->SetMetadataDoubleVector2(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name), 
                               CPPJNIByteBufferAdapter<OpenVDS::DoubleVector2>(env, valuebytebuffer, valuebyteoffset));
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataWriteAccess_SetMetadataDoubleVector3Impl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataWriteAccess>(native_handle);
    pInstance->SetMetadataDoubleVector3(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name), 
                               CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, valuebytebuffer, valuebyteoffset));
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataWriteAccess_SetMetadataDoubleVector4Impl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name, jobject valuebytebuffer, jlong valuebyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataWriteAccess>(native_handle);
    pInstance->SetMetadataDoubleVector4(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name), 
                               CPPJNIByteBufferAdapter<OpenVDS::DoubleVector4>(env, valuebytebuffer, valuebyteoffset));
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataWriteAccess_SetMetadataStringImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name, jstring value)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataWriteAccess>(native_handle);
    pInstance->SetMetadataString(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name), 
                               CPPJNIStringWrapper(env, native_handle, value));
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataWriteAccess_SetMetadataString2Impl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name, jstring value)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataWriteAccess>(native_handle);
    pInstance->SetMetadataString(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name), 
                               std::string(CPPJNIStringWrapper(env, native_handle, value)));
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataWriteAccess_SetMetadataBLOBImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name, jobject data)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto tmpdata = CPPJNIAsyncBuffer<void>(env, data);
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataWriteAccess>(native_handle);
    pInstance->SetMetadataBLOB(
                               CPPJNIStringWrapper(env, native_handle, category), 
                               CPPJNIStringWrapper(env, native_handle, name), 
                               tmpdata.buffer(), tmpdata.byteSize());
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataWriteAccess_CopyMetadataImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jlong metadataReadAccess)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataWriteAccess>(native_handle);
    pInstance->CopyMetadata(CPPJNIStringWrapper(env, native_handle, category), CPPJNI_cast<OpenVDS::MetadataReadAccess>(metadataReadAccess));
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataWriteAccess_ClearMetadataImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category, jstring name)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataWriteAccess>(native_handle);
    pInstance->ClearMetadata(CPPJNIStringWrapper(env, native_handle, category), CPPJNIStringWrapper(env, native_handle, name));
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataWriteAccess_ClearMetadata2Impl
  (JNIEnv * env, jobject object, jlong native_handle, jstring category)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::MetadataWriteAccess>(native_handle);
    pInstance->ClearMetadata(CPPJNIStringWrapper(env, native_handle, category));
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_MetadataWriteAccess_dtorImpl
  (JNIEnv * env, jobject object, jlong native_handle, jboolean is_disposing)
{
  CPPJNI_TRY
  {
    CPPJNI_destroyHandle<OpenVDS::MetadataWriteAccess>(env, native_handle);
  }
  CPPJNI_CATCH
}



#ifdef __cplusplus
}
#endif
