//=============================================================================
// <copyright>
// Copyright (c) 2021 Bluware Inc. All rights reserved.
//
// All rights are reserved. Reproduction or transmission in whole or in part,
// in any form or by any means, electronic, mechanical or otherwise,
// is prohibited without the prior written permission of the copyright owner.
// </copyright>
//=============================================================================


// THIS FILE IS AUTOGENERATED. DO NOT EDIT!

//#pragma warning(disable : 4996) // Hide exception warning from VolumeDataAccess.h

#include "Marshaling.h"


#include "VolumeDataLayoutDescriptor.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_com_hue_proxylib_VolumeDataLayoutDescriptor_ctorImpl
  (JNIEnv * env, jclass cls, jobject jproxyinterface)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto context = new HueJNIObjectContext_t<OpenVDS::VolumeDataLayoutDescriptor>();

    auto native_handle = context->handle();
    context->setObject(new OpenVDS::VolumeDataLayoutDescriptor());

    return native_handle;
  }
  HUE_JNI_CATCH
  return 0;
}


JNIEXPORT jlong JNICALL Java_com_hue_proxylib_VolumeDataLayoutDescriptor_ctor2Impl
  (JNIEnv * env, jclass cls, jobject jproxyinterface, jlong brickSize, jint negativeMargin, jint positiveMargin, jint brickSize2DMultiplier, jlong lodLevels, jlong options, jint fullResolutionDimension)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto context = new HueJNIObjectContext_t<OpenVDS::VolumeDataLayoutDescriptor>();

    auto native_handle = context->handle();
    context->setObject(new OpenVDS::VolumeDataLayoutDescriptor(
                               (enum OpenVDS::VolumeDataLayoutDescriptor::BrickSize)brickSize, 
                               negativeMargin, 
                               positiveMargin, 
                               brickSize2DMultiplier, 
                               (enum OpenVDS::VolumeDataLayoutDescriptor::LODLevels)lodLevels, 
                               (enum OpenVDS::VolumeDataLayoutDescriptor::Options)options, 
                               fullResolutionDimension));

    return native_handle;
  }
  HUE_JNI_CATCH
  return 0;
}


JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_VolumeDataLayoutDescriptor_IsValidImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayoutDescriptor>(native_handle);
    auto result = pInstance->IsValid();
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jlong JNICALL Java_com_hue_proxylib_VolumeDataLayoutDescriptor_GetBrickSizeImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayoutDescriptor>(native_handle);
    auto result = pInstance->GetBrickSize();
    return (jlong)result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jint JNICALL Java_com_hue_proxylib_VolumeDataLayoutDescriptor_GetNegativeMarginImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayoutDescriptor>(native_handle);
    auto result = pInstance->GetNegativeMargin();
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jint JNICALL Java_com_hue_proxylib_VolumeDataLayoutDescriptor_GetPositiveMarginImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayoutDescriptor>(native_handle);
    auto result = pInstance->GetPositiveMargin();
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jint JNICALL Java_com_hue_proxylib_VolumeDataLayoutDescriptor_GetBrickSizeMultiplier2DImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayoutDescriptor>(native_handle);
    auto result = pInstance->GetBrickSizeMultiplier2D();
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jlong JNICALL Java_com_hue_proxylib_VolumeDataLayoutDescriptor_GetLODLevelsImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayoutDescriptor>(native_handle);
    auto result = pInstance->GetLODLevels();
    return (jlong)result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_VolumeDataLayoutDescriptor_IsCreate2DLODsImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayoutDescriptor>(native_handle);
    auto result = pInstance->IsCreate2DLODs();
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_VolumeDataLayoutDescriptor_IsForceFullResolutionDimensionImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayoutDescriptor>(native_handle);
    auto result = pInstance->IsForceFullResolutionDimension();
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jint JNICALL Java_com_hue_proxylib_VolumeDataLayoutDescriptor_GetFullResolutionDimensionImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayoutDescriptor>(native_handle);
    auto result = pInstance->GetFullResolutionDimension();
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_VolumeDataLayoutDescriptor_dtorImpl
  (JNIEnv * env, jobject object, jlong native_handle)
{
  HUE_JNI_TRY
  {
    HueJNI_destroyHandle<OpenVDS::VolumeDataLayoutDescriptor>(env, native_handle);
  }
  HUE_JNI_CATCH
}



#ifdef __cplusplus
}
#endif
