//=============================================================================
// <copyright>
// Copyright (c) 2021 Bluware Inc. All rights reserved.
//
// All rights are reserved. Reproduction or transmission in whole or in part,
// in any form or by any means, electronic, mechanical or otherwise,
// is prohibited without the prior written permission of the copyright owner.
// </copyright>
//=============================================================================


// THIS FILE IS AUTOGENERATED. DO NOT EDIT!

//#pragma warning(disable : 4996) // Hide exception warning from VolumeDataAccess.h

#include "Marshaling.h"


#include "VolumeDataLayout.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetContentsHashImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetContentsHash();
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jint JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetDimensionalityImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetDimensionality();
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jint JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetChannelCountImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetChannelCount();
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_VolumeDataLayout_IsChannelAvailableImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring channelName)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->IsChannelAvailable(HueJNIStringWrapper(env, native_handle, channelName));
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jint JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetChannelIndexImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jstring channelName)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetChannelIndex(HueJNIStringWrapper(env, native_handle, channelName));
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jlong JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetLayoutDescriptorImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetLayoutDescriptor();
    auto context = HueJNI_createObjectContext(new OpenVDS::VolumeDataLayoutDescriptor(result));
    return context->handle();
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jlong JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetChannelDescriptorImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint channel)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetChannelDescriptor(channel);
    auto context = HueJNI_createObjectContext(new OpenVDS::VolumeDataChannelDescriptor(result));
    return context->handle();
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jlong JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetAxisDescriptorImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint dimension)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetAxisDescriptor(dimension);
    auto context = HueJNI_createObjectContext(new OpenVDS::VolumeDataAxisDescriptor(result));
    return context->handle();
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jlong JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetChannelFormatImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint channel)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetChannelFormat(channel);
    return (jlong)result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jlong JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetChannelComponentsImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint channel)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetChannelComponents(channel);
    return (jlong)result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jstring JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetChannelNameImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint channel)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetChannelName(channel);
    return HueJNI_newString(env, result);
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jstring JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetChannelUnitImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint channel)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetChannelUnit(channel);
    return HueJNI_newString(env, result);
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jfloat JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetChannelValueRangeMinImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint channel)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetChannelValueRangeMin(channel);
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jfloat JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetChannelValueRangeMaxImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint channel)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetChannelValueRangeMax(channel);
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_VolumeDataLayout_IsChannelDiscreteImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint channel)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->IsChannelDiscrete(channel);
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_VolumeDataLayout_IsChannelRenderableImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint channel)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->IsChannelRenderable(channel);
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_VolumeDataLayout_IsChannelAllowingLossyCompressionImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint channel)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->IsChannelAllowingLossyCompression(channel);
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_VolumeDataLayout_IsChannelUseZipForLosslessCompressionImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint channel)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->IsChannelUseZipForLosslessCompression(channel);
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jlong JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetChannelMappingImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint channel)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetChannelMapping(channel);
    return (jlong)result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jint JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetDimensionNumSamplesImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint dimension)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetDimensionNumSamples(dimension);
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jstring JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetDimensionNameImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint dimension)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetDimensionName(dimension);
    return HueJNI_newString(env, result);
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jstring JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetDimensionUnitImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint dimension)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetDimensionUnit(dimension);
    return HueJNI_newString(env, result);
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jfloat JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetDimensionMinImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint dimension)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetDimensionMin(dimension);
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jfloat JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetDimensionMaxImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint dimension)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetDimensionMax(dimension);
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_com_hue_proxylib_VolumeDataLayout_IsChannelUseNoValueImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint channel)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->IsChannelUseNoValue(channel);
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jfloat JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetChannelNoValueImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint channel)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetChannelNoValue(channel);
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jfloat JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetChannelIntegerScaleImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint channel)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetChannelIntegerScale(channel);
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT jfloat JNICALL Java_com_hue_proxylib_VolumeDataLayout_GetChannelIntegerOffsetImpl
  (JNIEnv * env, jobject object, jobject jproxyinterface, jlong native_handle, jint channel)
{
  JEnvPushPop
    stackitem(env, jproxyinterface);

  HUE_JNI_TRY
  {
    auto pInstance = HueJNI_cast<OpenVDS::VolumeDataLayout>(native_handle);
    auto result = pInstance->GetChannelIntegerOffset(channel);
    return result;
  }
  HUE_JNI_CATCH
  return 0;
}

JNIEXPORT void JNICALL Java_com_hue_proxylib_VolumeDataLayout_dtorImpl
  (JNIEnv * env, jobject object, jlong native_handle)
{
  HUE_JNI_TRY
  {
    HueJNI_destroyHandle<OpenVDS::VolumeDataLayout>(env, native_handle);
  }
  HUE_JNI_CATCH
}



#ifdef __cplusplus
}
#endif
