stages:
- prepare
- build
- test
- deploy
variables:
  SHA_IMAGE_TAG: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:1"
  SHA_MANYLINUX_IMAGE_TAG: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:manylinux-1"
  SHA_CENTOS7DEV7_IMAGE_TAG: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:centos7dev7-1"
  CMAKE_OPTIONS: "-GNinja -DCMAKE_BUILD_TYPE=Debug"
cache:
  paths:
  - ccache
  - 3rdparty
devel-container-gitlab:
  stage: prepare
  image: docker:19.03
  tags:
  - docker-runner
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $SHA_IMAGE_TAG -f docker/alpine-gitlab-ci.Dockerfile .
  - docker push $SHA_IMAGE_TAG
  only:
  - master
gcp-containerize-gitlab:
  stage: prepare
  image: docker:19.03
  tags: ["osdu-small"]
  variables:
    BUILD_PATH: "docker/alpine-gitlab-ci.Dockerfile"
    IMAGE_NAME: "openvds-ingestion"
  script:
    - export EXTRA_DOCKER_TAG=""
    - >
      if [[ "$CI_COMMIT_TAG" != "" ]];
      then EXTRA_DOCKER_TAG="-t $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_TAG";
      elif [[ "$CI_COMMIT_REF_NAME" = "master" ]];
      then EXTRA_DOCKER_TAG="-t $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest"; fi
    - docker build -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA $EXTRA_DOCKER_TAG -f $BUILD_PATH .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME
  rules:
    - if: "$OSDU_GCP == 'true'"
      when: on_success
devel-container-gcr:
  stage: prepare
  image: docker:19.03
  tags: ["osdu-small"]
  variables:
    OSDU_GCP_IMAGE_PATH: "seismic/open-vds/openvds-ingestion"
    OSDU_GCP_GCR_REGISTRY: "gcr.io/osdu-anthos"
  before_script:
  - cat $OSDU_GCP_DEPLOY_FILE | docker login -u _json_key --password-stdin https://gcr.io
  script:
  - docker build --tag $OSDU_GCP_GCR_REGISTRY/$OSDU_GCP_IMAGE_PATH:$CI_COMMIT_TAG --file docker/alpine-gitlab-ci.Dockerfile .
  - docker push $OSDU_GCP_GCR_REGISTRY/$OSDU_GCP_IMAGE_PATH:$CI_COMMIT_TAG
  rules:
  - if: "$OSDU_GCP == 'true' && $CI_COMMIT_TAG"
    when: on_success
devel-container-merge-request:
  stage: prepare
  image: docker:19.03
  tags:
  - docker-runner
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $SHA_IMAGE_TAG -f docker/alpine-gitlab-ci.Dockerfile .
  - docker push $SHA_IMAGE_TAG
  only:
  - merge_requests
devel-container-manylinux-merge-request:
  stage: prepare
  image: docker:19.03
  tags:
  - docker-runner
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $SHA_MANYLINUX_IMAGE_TAG -f docker/manylinux-2014.Dockerfile .
  - docker push $SHA_MANYLINUX_IMAGE_TAG
  only:
  - merge_requests
devel-container-centos7dev7-merge-request:
  stage: prepare
  image: docker:19.03
  tags:
  - docker-runner
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $SHA_CENTOS7DEV7_IMAGE_TAG -f docker/centos7.Dockerfile .
  - docker push $SHA_CENTOS7DEV7_IMAGE_TAG
  only:
  - merge_requests
compile:
  stage: build
  image: "$SHA_IMAGE_TAG"
  tags:
  - docker-runner
  artifacts:
    expire_in: 1 hr
    paths:
    - build
  before_script:
  - export CCACHE_BASEDIR="$PWD"
  - export CCACHE_DIR="$PWD/ccache"
  - export CCACHE_COMPILERCHECK=content
  - ccache --zero-stats || true
  - ccache --show-stats || true
  script:
  - mkdir -p build
  - cd build
  - cmake -DBUILD_DOCS=ON $CMAKE_OPTIONS ..
  - ninja
  after_script:
  - export CCACHE_DIR="$PWD/ccache"
  - ccache --show-stats
  only:
  - master
compile-merge-request:
  stage: build
  image: "$SHA_IMAGE_TAG"
  tags:
  - docker-runner
  artifacts:
    expire_in: 1 hr
    paths:
    - build
  before_script:
  - export CCACHE_BASEDIR="$PWD"
  - export CCACHE_DIR="$PWD/ccache"
  - export CCACHE_COMPILERCHECK=content
  - ccache --zero-stats || true
  - ccache --show-stats || true
  script:
  - export CCACHE_DIR="$PWD/ccache"
  - mkdir -p build
  - cd build
  - cmake $CMAKE_OPTIONS ..
  - ninja
  after_script:
  - export CCACHE_DIR="$PWD/ccache"
  - ccache --show-stats
  only:
  - merge_requests
compile-merge-request-manylinux:
  stage: build
  image: "$SHA_MANYLINUX_IMAGE_TAG"
  tags:
  - docker-runner
  artifacts:
    expire_in: 1 hr
    paths:
    - build-manylinux
  before_script:
  - export CCACHE_BASEDIR="$PWD"
  - export CCACHE_DIR="$PWD/ccache-manylinux"
  - export CCACHE_COMPILERCHECK=content
  - ccache --zero-stats || true
  - ccache --show-stats || true
  script:
  - export CCACHE_DIR="$PWD/ccache-manylinux"
  - mkdir -p build-manylinux
  - cd build-manylinux
  - cmake $CMAKE_OPTIONS -DPython3_ROOT_DIR="/opt/python/cp310-cp310" -DBOOST_INCLUDEDIR=/usr/include/boost169 -DBOOST_LIBRARYDIR=/usr/lib64/boost169 ..
  - ninja
  after_script:
  - export CCACHE_DIR="$PWD/ccache-manylinux"
  - ccache --show-stats
  only:
  - merge_requests
compile-merge-request-centos7dev7:
  stage: build
  image: "$SHA_CENTOS7DEV7_IMAGE_TAG"
  tags:
  - docker-runner
  artifacts:
    expire_in: 1 hr
    paths:
    - build-centos7dev7
  before_script:
  - export CCACHE_BASEDIR="$PWD"
  - export CCACHE_DIR="$PWD/ccache-centos7dev7"
  - export CCACHE_COMPILERCHECK=content
  - ccache --zero-stats || true
  - ccache --show-stats || true
  script:
  - export CCACHE_DIR="$PWD/ccache-centos7dev7"
  - mkdir -p build-centos7dev7
  - cd build-centos7dev7
  - cmake $CMAKE_OPTIONS -DBOOST_INCLUDEDIR=/usr/include/boost169 -DBOOST_LIBRARYDIR=/usr/lib64/boost169 ..
  - ninja
  after_script:
  - export CCACHE_DIR="$PWD/ccache-centos7dev7"
  - ccache --show-stats
  only:
  - merge_requests
unit-tests:
  stage: test
  image: "$SHA_IMAGE_TAG"
  tags:
  - docker-runner
  script:
  - cd build
  - ctest -V
  only:
  - merge_requests
  artifacts:
    when: always
    reports:
      junit:
        - build/test_results/*.xml
        - build/test_results_java/junitreports/*.xml
unit-tests-manylinux:
  stage: test
  image: "$SHA_MANYLINUX_IMAGE_TAG"
  tags:
  - docker-runner
  script:
  - cd build-manylinux
  - ctest -V
  only:
  - merge_requests
  artifacts:
    when: always
    reports:
      junit:
        - build-manylinux/test_results/*.xml
        - build-manylinux/test_results_java/junitreports/*.xml
unit-tests-centos7dev7:
  stage: test
  image: "$SHA_CENTOS7DEV7_IMAGE_TAG"
  tags:
  - docker-runner
  script:
  - cd build-centos7dev7
  - ctest -V
  only:
  - merge_requests
  artifacts:
    when: always
    reports:
      junit:
        - build-centos7dev7/test_results/*.xml
        - build-centos7dev7/test_results_java/junitreports/*.xml
pages:
  stage: deploy
  image: "$SHA_IMAGE_TAG"
  tags:
  - docker-runner
  script:
  - mv build/docs/html public
  artifacts:
    paths:
    - public
  only:
  - master
include:
- template: Security/SAST.gitlab-ci.yml
sast:
  variables:
    SAST_EXCLUDED_PATHS: _skbuild, 3rdparty, binpackage, CMake, common, docker, docs,
      examples, java, out, python, tests
    SAST_EXCLUDED_ANALYZERS: bandit, brakeman, eslint, gosec, kubesec, nodejs-scan,
      phpcs-security-audit, pmd-apex, security-code-scan, semgrep, sobelow, spotbugs
    SAST_FLAWFINDER_LEVEL: '4'
  stage: test
