/****************************************************************************
** Copyright 2021 The Open Group
** Copyright 2021 Bluware, Inc.
**
** Licensed under the Apache License, Version 2.0 (the "License");
** you may not use this file except in compliance with the License.
** You may obtain a copy of the License at
**
**     http://www.apache.org/licenses/LICENSE-2.0
**
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS,
** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
** See the License for the specific language governing permissions and
** limitations under the License.
****************************************************************************/

#include "PyIJKCoordinateTransformer.h"
#include <OpenVDS/IJKCoordinateTransformer.h>

using namespace native;
void 
PyIJKCoordinateTransformer::initModule(py::module& m)
{
//AUTOGEN-BEGIN
  // IJKCoordinateTransformer
  py::class_<IJKCoordinateTransformer> 
    IJKCoordinateTransformer_(m,"IJKCoordinateTransformer", OPENVDS_DOCSTRING(IJKCoordinateTransformer));

  IJKCoordinateTransformer_.def(py::init<                              >(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKCoordinateTransformer));
  IJKCoordinateTransformer_.def(py::init<const native::IJKGridDefinition &, const native::IntVector3 &>(), py::arg("ijkGridDefinition").none(false), py::arg("ijkSize").none(false), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKCoordinateTransformer_2));
  IJKCoordinateTransformer_.def(py::init<const native::IJKGridDefinition &, const native::IntVector3 &, const native::IntVector3 &>(), py::arg("ijkGridDefinition").none(false), py::arg("ijkSize").none(false), py::arg("ijkToVoxelDimensionMap").none(false), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKCoordinateTransformer_3));
  IJKCoordinateTransformer_.def(py::init<const native::VDSIJKGridDefinition &, const native::IntVector3 &>(), py::arg("vdsIJKGridDefinition").none(false), py::arg("ijkSize").none(false), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKCoordinateTransformer_4));
  IJKCoordinateTransformer_.def(py::init<const native::IJKGridDefinition &, const native::IntVector3 &, const native::DoubleVector3 &, const native::DoubleVector3 &>(), py::arg("ijkGridDefinition").none(false), py::arg("ijkSize").none(false), py::arg("ijkAnnotationStart").none(false), py::arg("ijkAnnotationEnd").none(false), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKCoordinateTransformer_5));
  IJKCoordinateTransformer_.def(py::init<const native::IJKGridDefinition &, const native::IntVector3 &, const native::IntVector3 &, const native::DoubleVector3 &, const native::DoubleVector3 &>(), py::arg("ijkGridDefinition").none(false), py::arg("ijkSize").none(false), py::arg("ijkToVoxelDimensionMap").none(false), py::arg("ijkAnnotationStart").none(false), py::arg("ijkAnnotationEnd").none(false), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKCoordinateTransformer_6));
  IJKCoordinateTransformer_.def(py::init<const native::VDSIJKGridDefinition &, const native::IntVector3 &, const native::DoubleVector3 &, const native::DoubleVector3 &>(), py::arg("vdsIJKGridDefinition").none(false), py::arg("ijkSize").none(false), py::arg("ijkAnnotationStart").none(false), py::arg("ijkAnnotationEnd").none(false), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKCoordinateTransformer_7));
  IJKCoordinateTransformer_.def(py::init<const native::VolumeDataLayout *>(), py::arg("layout").none(false), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKCoordinateTransformer_8));
  IJKCoordinateTransformer_.def("IJKPositionToWorld"          , static_cast<native::DoubleVector3(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::IJKPositionToWorld), py::arg("ijkPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKPositionToWorld));
  IJKCoordinateTransformer_.def("IJKIndexToWorld"             , static_cast<native::DoubleVector3(IJKCoordinateTransformer::*)(const native::IntVector3 &) const>(&IJKCoordinateTransformer::IJKIndexToWorld), py::arg("ijkIndex").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKIndexToWorld));
  IJKCoordinateTransformer_.def("IJKPositionToAnnotation"     , static_cast<native::DoubleVector3(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::IJKPositionToAnnotation), py::arg("ijkPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKPositionToAnnotation));
  IJKCoordinateTransformer_.def("IJKIndexToAnnotation"        , static_cast<native::DoubleVector3(IJKCoordinateTransformer::*)(const native::IntVector3 &) const>(&IJKCoordinateTransformer::IJKIndexToAnnotation), py::arg("ijkIndex").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKIndexToAnnotation));
  IJKCoordinateTransformer_.def("IJKPositionToVoxelPosition"  , static_cast<native::DoubleVector3(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::IJKPositionToVoxelPosition), py::arg("ijkPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKPositionToVoxelPosition));
  IJKCoordinateTransformer_.def("IJKIndexToVoxelIndex"        , static_cast<native::IntVector3(IJKCoordinateTransformer::*)(const native::IntVector3 &) const>(&IJKCoordinateTransformer::IJKIndexToVoxelIndex), py::arg("ijkIndex").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKIndexToVoxelIndex));
  IJKCoordinateTransformer_.def("worldToIJKPosition"          , static_cast<native::DoubleVector3(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::WorldToIJKPosition), py::arg("worldPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_WorldToIJKPosition));
  IJKCoordinateTransformer_.def("worldToIJKIndex"             , static_cast<native::IntVector3(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::WorldToIJKIndex), py::arg("worldPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_WorldToIJKIndex));
  IJKCoordinateTransformer_.def("worldToAnnotation"           , static_cast<native::DoubleVector3(IJKCoordinateTransformer::*)(native::DoubleVector3) const>(&IJKCoordinateTransformer::WorldToAnnotation), py::arg("worldPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_WorldToAnnotation));
  IJKCoordinateTransformer_.def("worldToVoxelPosition"        , static_cast<native::DoubleVector3(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::WorldToVoxelPosition), py::arg("worldPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_WorldToVoxelPosition));
  IJKCoordinateTransformer_.def("worldToVoxelIndex"           , static_cast<native::IntVector3(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::WorldToVoxelIndex), py::arg("worldPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_WorldToVoxelIndex));
  IJKCoordinateTransformer_.def("annotationToIJKPosition"     , static_cast<native::DoubleVector3(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::AnnotationToIJKPosition), py::arg("annotationPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_AnnotationToIJKPosition));
  IJKCoordinateTransformer_.def("annotationToIJKIndex"        , static_cast<native::IntVector3(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::AnnotationToIJKIndex), py::arg("annotationPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_AnnotationToIJKIndex));
  IJKCoordinateTransformer_.def("annotationToWorld"           , static_cast<native::DoubleVector3(IJKCoordinateTransformer::*)(native::DoubleVector3) const>(&IJKCoordinateTransformer::AnnotationToWorld), py::arg("annotationPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_AnnotationToWorld));
  IJKCoordinateTransformer_.def("annotationToVoxelPosition"   , static_cast<native::DoubleVector3(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::AnnotationToVoxelPosition), py::arg("annotationPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_AnnotationToVoxelPosition));
  IJKCoordinateTransformer_.def("annotationToVoxelIndex"      , static_cast<native::IntVector3(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::AnnotationToVoxelIndex), py::arg("annotationPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_AnnotationToVoxelIndex));
  IJKCoordinateTransformer_.def("voxelPositionToIJKPosition"  , static_cast<native::DoubleVector3(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::VoxelPositionToIJKPosition), py::arg("voxelPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_VoxelPositionToIJKPosition));
  IJKCoordinateTransformer_.def("voxelIndexToIJKIndex"        , static_cast<native::IntVector3(IJKCoordinateTransformer::*)(const native::IntVector3 &) const>(&IJKCoordinateTransformer::VoxelIndexToIJKIndex), py::arg("voxelIndex").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_VoxelIndexToIJKIndex));
  IJKCoordinateTransformer_.def("voxelPositionToWorld"        , static_cast<native::DoubleVector3(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::VoxelPositionToWorld), py::arg("voxelPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_VoxelPositionToWorld));
  IJKCoordinateTransformer_.def("voxelIndexToWorld"           , static_cast<native::DoubleVector3(IJKCoordinateTransformer::*)(const native::IntVector3 &) const>(&IJKCoordinateTransformer::VoxelIndexToWorld), py::arg("voxelIndex").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_VoxelIndexToWorld));
  IJKCoordinateTransformer_.def("voxelPositionToAnnotation"   , static_cast<native::DoubleVector3(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::VoxelPositionToAnnotation), py::arg("voxelPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_VoxelPositionToAnnotation));
  IJKCoordinateTransformer_.def("voxelIndexToAnnotation"      , static_cast<native::DoubleVector3(IJKCoordinateTransformer::*)(const native::IntVector3 &) const>(&IJKCoordinateTransformer::VoxelIndexToAnnotation), py::arg("voxelIndex").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_VoxelIndexToAnnotation));
  IJKCoordinateTransformer_.def("isIJKPositionOutOfRange"     , static_cast<bool(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::IsIJKPositionOutOfRange), py::arg("ijkPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IsIJKPositionOutOfRange));
  IJKCoordinateTransformer_.def("isIJKIndexOutOfRange"        , static_cast<bool(IJKCoordinateTransformer::*)(const native::IntVector3 &) const>(&IJKCoordinateTransformer::IsIJKIndexOutOfRange), py::arg("ijkIndex").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IsIJKIndexOutOfRange));
  IJKCoordinateTransformer_.def("isVoxelPositionOutOfRange"   , static_cast<bool(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::IsVoxelPositionOutOfRange), py::arg("voxelPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IsVoxelPositionOutOfRange));
  IJKCoordinateTransformer_.def("isVoxelIndexOutOfRange"      , static_cast<bool(IJKCoordinateTransformer::*)(const native::IntVector3 &) const>(&IJKCoordinateTransformer::IsVoxelIndexOutOfRange), py::arg("voxelIndex").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IsVoxelIndexOutOfRange));
  IJKCoordinateTransformer_.def("convertIJKPositionToIndex"   , static_cast<native::IntVector3(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::ConvertIJKPositionToIndex), py::arg("ijkPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_ConvertIJKPositionToIndex));
  IJKCoordinateTransformer_.def("convertVoxelPositionToIndex" , static_cast<native::IntVector3(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::ConvertVoxelPositionToIndex), py::arg("voxelPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_ConvertVoxelPositionToIndex));
  IJKCoordinateTransformer_.def(py::self == py::self);
  IJKCoordinateTransformer_.def("errorCodeIfIJKPositionOutOfRange", static_cast<int(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::ErrorCodeIfIJKPositionOutOfRange), py::arg("ijkPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_ErrorCodeIfIJKPositionOutOfRange));
  IJKCoordinateTransformer_.def("errorCodeIfVoxelPositionOutOfRange", static_cast<int(IJKCoordinateTransformer::*)(const native::DoubleVector3 &) const>(&IJKCoordinateTransformer::ErrorCodeIfVoxelPositionOutOfRange), py::arg("voxelPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_ErrorCodeIfVoxelPositionOutOfRange));

//AUTOGEN-END   

// IMPLEMENTED :  IJKCoordinateTransformer_.def("IJKGrid"                     , static_cast<const native::IJKGridDefinition &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::IJKGrid), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKGrid));
// IMPLEMENTED :  IJKCoordinateTransformer_.def("IJKSize"                     , static_cast<const native::IntVector3 &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::IJKSize), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKSize));
// IMPLEMENTED :  IJKCoordinateTransformer_.def("IJKToVoxelDimensionMap"      , static_cast<const native::IntVector3 &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::IJKToVoxelDimensionMap), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKToVoxelDimensionMap));
// IMPLEMENTED :  IJKCoordinateTransformer_.def("IJKToWorldTransform"         , static_cast<const native::DoubleMatrix4x4 &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::IJKToWorldTransform), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKToWorldTransform));
// IMPLEMENTED :  IJKCoordinateTransformer_.def("worldToIJKTransform"         , static_cast<const native::DoubleMatrix4x4 &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::WorldToIJKTransform), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_WorldToIJKTransform));
// IMPLEMENTED :  IJKCoordinateTransformer_.def("IJKAnnotationStart"          , static_cast<const native::DoubleVector3 &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::IJKAnnotationStart), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKAnnotationStart));
// IMPLEMENTED :  IJKCoordinateTransformer_.def("IJKAnnotationEnd"            , static_cast<const native::DoubleVector3 &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::IJKAnnotationEnd), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKAnnotationEnd));
// IMPLEMENTED :  IJKCoordinateTransformer_.def("annotationsDefined"          , static_cast<bool(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::AnnotationsDefined), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_AnnotationsDefined));
  
  IJKCoordinateTransformer_.def_property_readonly("IJKGrid"                     , static_cast<const native::IJKGridDefinition &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::IJKGrid), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKGrid));
  IJKCoordinateTransformer_.def_property_readonly("IJKSize"                     , static_cast<const native::IntVector3 &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::IJKSize), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKSize));
  IJKCoordinateTransformer_.def_property_readonly("IJKToVoxelDimensionMap"      , static_cast<const native::IntVector3 &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::IJKToVoxelDimensionMap), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKToVoxelDimensionMap));
  IJKCoordinateTransformer_.def_property_readonly("IJKToWorldTransform"         , static_cast<const native::DoubleMatrix4x4 &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::IJKToWorldTransform), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKToWorldTransform));
  IJKCoordinateTransformer_.def_property_readonly("worldToIJKTransform"         , static_cast<const native::DoubleMatrix4x4 &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::WorldToIJKTransform), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_WorldToIJKTransform));
  IJKCoordinateTransformer_.def_property_readonly("IJKAnnotationStart"          , static_cast<const native::DoubleVector3 &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::IJKAnnotationStart), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKAnnotationStart));
  IJKCoordinateTransformer_.def_property_readonly("IJKAnnotationEnd"            , static_cast<const native::DoubleVector3 &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::IJKAnnotationEnd), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKAnnotationEnd));
  IJKCoordinateTransformer_.def_property_readonly("annotationsDefined"          , static_cast<bool(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::AnnotationsDefined), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_AnnotationsDefined));
}

