/****************************************************************************
** Copyright 2021 The Open Group
** Copyright 2021 Bluware, Inc.
**
** Licensed under the Apache License, Version 2.0 (the "License");
** you may not use this file except in compliance with the License.
** You may obtain a copy of the License at
**
**     http://www.apache.org/licenses/LICENSE-2.0
**
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS,
** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
** See the License for the specific language governing permissions and
** limitations under the License.
****************************************************************************/

#include "PyIJKCoordinateTransformer.h"
#include <OpenVDS/IJKCoordinateTransformer.h>

using namespace native;
void 
PyIJKCoordinateTransformer::initModule(py::module& m)
{
//AUTOGEN-BEGIN
  // IJKCoordinateTransformer
  py::class_<IJKCoordinateTransformer> 
    IJKCoordinateTransformer_(m,"IJKCoordinateTransformer", OPENVDS_DOCSTRING(IJKCoordinateTransformer));

  IJKCoordinateTransformer_.def(py::init<                              >(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKCoordinateTransformer));
  IJKCoordinateTransformer_.def(py::init<const native::IJKGridDefinition &, const native::IntVector3 &>(), py::arg("ijkGridDefinition").none(false), py::arg("ijkSize").none(false), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKCoordinateTransformer_2));
  IJKCoordinateTransformer_.def(py::init<const native::IJKGridDefinition &, const native::IntVector3 &, const native::IntVector3 &>(), py::arg("ijkGridDefinition").none(false), py::arg("ijkSize").none(false), py::arg("ijkToVoxelDimensionMap").none(false), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKCoordinateTransformer_3));
  IJKCoordinateTransformer_.def(py::init<const native::VDSIJKGridDefinition &, const native::IntVector3 &>(), py::arg("vdsIJKGridDefinition").none(false), py::arg("ijkSize").none(false), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKCoordinateTransformer_4));
  IJKCoordinateTransformer_.def(py::init<const native::IJKGridDefinition &, const native::IntVector3 &, const native::DoubleVector3 &, const native::DoubleVector3 &>(), py::arg("ijkGridDefinition").none(false), py::arg("ijkSize").none(false), py::arg("ijkAnnotationStart").none(false), py::arg("ijkAnnotationEnd").none(false), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKCoordinateTransformer_5));
  IJKCoordinateTransformer_.def(py::init<const native::IJKGridDefinition &, const native::IntVector3 &, const native::IntVector3 &, const native::DoubleVector3 &, const native::DoubleVector3 &>(), py::arg("ijkGridDefinition").none(false), py::arg("ijkSize").none(false), py::arg("ijkToVoxelDimensionMap").none(false), py::arg("ijkAnnotationStart").none(false), py::arg("ijkAnnotationEnd").none(false), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKCoordinateTransformer_6));
  IJKCoordinateTransformer_.def(py::init<const native::VDSIJKGridDefinition &, const native::IntVector3 &, const native::DoubleVector3 &, const native::DoubleVector3 &>(), py::arg("vdsIJKGridDefinition").none(false), py::arg("ijkSize").none(false), py::arg("ijkAnnotationStart").none(false), py::arg("ijkAnnotationEnd").none(false), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKCoordinateTransformer_7));
  IJKCoordinateTransformer_.def(py::init<native::VolumeDataLayout *    >(), py::arg("layout").none(false), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKCoordinateTransformer_8));
  IJKCoordinateTransformer_.def("IJKPositionToWorld"          , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType ijkPosition) { return (DoubleVector3Adapter::AdaptedType)(self->IJKPositionToWorld(ijkPosition)); }, py::arg("ijkPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKPositionToWorld));
  IJKCoordinateTransformer_.def("IJKIndexToWorld"             , [](IJKCoordinateTransformer* self, IntVector3Adapter::AdaptedType ijkIndex) { return (DoubleVector3Adapter::AdaptedType)(self->IJKIndexToWorld(ijkIndex)); }, py::arg("ijkIndex").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKIndexToWorld));
  IJKCoordinateTransformer_.def("IJKPositionToAnnotation"     , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType ijkPosition) { return (DoubleVector3Adapter::AdaptedType)(self->IJKPositionToAnnotation(ijkPosition)); }, py::arg("ijkPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKPositionToAnnotation));
  IJKCoordinateTransformer_.def("IJKIndexToAnnotation"        , [](IJKCoordinateTransformer* self, IntVector3Adapter::AdaptedType ijkIndex) { return (DoubleVector3Adapter::AdaptedType)(self->IJKIndexToAnnotation(ijkIndex)); }, py::arg("ijkIndex").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKIndexToAnnotation));
  IJKCoordinateTransformer_.def("IJKPositionToVoxelPosition"  , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType ijkPosition) { return (DoubleVector3Adapter::AdaptedType)(self->IJKPositionToVoxelPosition(ijkPosition)); }, py::arg("ijkPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKPositionToVoxelPosition));
  IJKCoordinateTransformer_.def("IJKIndexToVoxelIndex"        , [](IJKCoordinateTransformer* self, IntVector3Adapter::AdaptedType ijkIndex) { return (IntVector3Adapter::AdaptedType)(self->IJKIndexToVoxelIndex(ijkIndex)); }, py::arg("ijkIndex").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKIndexToVoxelIndex));
  IJKCoordinateTransformer_.def("worldToIJKPosition"          , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType worldPosition) { return (DoubleVector3Adapter::AdaptedType)(self->WorldToIJKPosition(worldPosition)); }, py::arg("worldPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_WorldToIJKPosition));
  IJKCoordinateTransformer_.def("worldToIJKIndex"             , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType worldPosition) { return (IntVector3Adapter::AdaptedType)(self->WorldToIJKIndex(worldPosition)); }, py::arg("worldPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_WorldToIJKIndex));
  IJKCoordinateTransformer_.def("worldToAnnotation"           , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType worldPosition) { return (DoubleVector3Adapter::AdaptedType)(self->WorldToAnnotation(worldPosition)); }, py::arg("worldPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_WorldToAnnotation));
  IJKCoordinateTransformer_.def("worldToVoxelPosition"        , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType worldPosition) { return (DoubleVector3Adapter::AdaptedType)(self->WorldToVoxelPosition(worldPosition)); }, py::arg("worldPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_WorldToVoxelPosition));
  IJKCoordinateTransformer_.def("worldToVoxelIndex"           , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType worldPosition) { return (IntVector3Adapter::AdaptedType)(self->WorldToVoxelIndex(worldPosition)); }, py::arg("worldPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_WorldToVoxelIndex));
  IJKCoordinateTransformer_.def("annotationToIJKPosition"     , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType annotationPosition) { return (DoubleVector3Adapter::AdaptedType)(self->AnnotationToIJKPosition(annotationPosition)); }, py::arg("annotationPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_AnnotationToIJKPosition));
  IJKCoordinateTransformer_.def("annotationToIJKIndex"        , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType annotationPosition) { return (IntVector3Adapter::AdaptedType)(self->AnnotationToIJKIndex(annotationPosition)); }, py::arg("annotationPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_AnnotationToIJKIndex));
  IJKCoordinateTransformer_.def("annotationToWorld"           , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType annotationPosition) { return (DoubleVector3Adapter::AdaptedType)(self->AnnotationToWorld(annotationPosition)); }, py::arg("annotationPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_AnnotationToWorld));
  IJKCoordinateTransformer_.def("annotationToVoxelPosition"   , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType annotationPosition) { return (DoubleVector3Adapter::AdaptedType)(self->AnnotationToVoxelPosition(annotationPosition)); }, py::arg("annotationPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_AnnotationToVoxelPosition));
  IJKCoordinateTransformer_.def("annotationToVoxelIndex"      , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType annotationPosition) { return (IntVector3Adapter::AdaptedType)(self->AnnotationToVoxelIndex(annotationPosition)); }, py::arg("annotationPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_AnnotationToVoxelIndex));
  IJKCoordinateTransformer_.def("voxelPositionToIJKPosition"  , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType voxelPosition) { return (DoubleVector3Adapter::AdaptedType)(self->VoxelPositionToIJKPosition(voxelPosition)); }, py::arg("voxelPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_VoxelPositionToIJKPosition));
  IJKCoordinateTransformer_.def("voxelIndexToIJKIndex"        , [](IJKCoordinateTransformer* self, IntVector3Adapter::AdaptedType voxelIndex) { return (IntVector3Adapter::AdaptedType)(self->VoxelIndexToIJKIndex(voxelIndex)); }, py::arg("voxelIndex").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_VoxelIndexToIJKIndex));
  IJKCoordinateTransformer_.def("voxelPositionToWorld"        , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType voxelPosition) { return (DoubleVector3Adapter::AdaptedType)(self->VoxelPositionToWorld(voxelPosition)); }, py::arg("voxelPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_VoxelPositionToWorld));
  IJKCoordinateTransformer_.def("voxelIndexToWorld"           , [](IJKCoordinateTransformer* self, IntVector3Adapter::AdaptedType voxelIndex) { return (DoubleVector3Adapter::AdaptedType)(self->VoxelIndexToWorld(voxelIndex)); }, py::arg("voxelIndex").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_VoxelIndexToWorld));
  IJKCoordinateTransformer_.def("voxelPositionToAnnotation"   , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType voxelPosition) { return (DoubleVector3Adapter::AdaptedType)(self->VoxelPositionToAnnotation(voxelPosition)); }, py::arg("voxelPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_VoxelPositionToAnnotation));
  IJKCoordinateTransformer_.def("voxelIndexToAnnotation"      , [](IJKCoordinateTransformer* self, IntVector3Adapter::AdaptedType voxelIndex) { return (DoubleVector3Adapter::AdaptedType)(self->VoxelIndexToAnnotation(voxelIndex)); }, py::arg("voxelIndex").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_VoxelIndexToAnnotation));
  IJKCoordinateTransformer_.def("isIJKPositionOutOfRange"     , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType ijkPosition) { return self->IsIJKPositionOutOfRange(ijkPosition); }, py::arg("ijkPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IsIJKPositionOutOfRange));
  IJKCoordinateTransformer_.def("isIJKIndexOutOfRange"        , [](IJKCoordinateTransformer* self, IntVector3Adapter::AdaptedType ijkIndex) { return self->IsIJKIndexOutOfRange(ijkIndex); }, py::arg("ijkIndex").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IsIJKIndexOutOfRange));
  IJKCoordinateTransformer_.def("isVoxelPositionOutOfRange"   , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType voxelPosition) { return self->IsVoxelPositionOutOfRange(voxelPosition); }, py::arg("voxelPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IsVoxelPositionOutOfRange));
  IJKCoordinateTransformer_.def("isVoxelIndexOutOfRange"      , [](IJKCoordinateTransformer* self, IntVector3Adapter::AdaptedType voxelIndex) { return self->IsVoxelIndexOutOfRange(voxelIndex); }, py::arg("voxelIndex").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IsVoxelIndexOutOfRange));
  IJKCoordinateTransformer_.def("convertIJKPositionToIndex"   , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType ijkPosition) { return (IntVector3Adapter::AdaptedType)(self->ConvertIJKPositionToIndex(ijkPosition)); }, py::arg("ijkPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_ConvertIJKPositionToIndex));
  IJKCoordinateTransformer_.def("convertVoxelPositionToIndex" , [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType voxelPosition) { return (IntVector3Adapter::AdaptedType)(self->ConvertVoxelPositionToIndex(voxelPosition)); }, py::arg("voxelPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_ConvertVoxelPositionToIndex));
  IJKCoordinateTransformer_.def(py::self == py::self);
  IJKCoordinateTransformer_.def("errorCodeIfIJKPositionOutOfRange", [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType ijkPosition) { return self->ErrorCodeIfIJKPositionOutOfRange(ijkPosition); }, py::arg("ijkPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_ErrorCodeIfIJKPositionOutOfRange));
  IJKCoordinateTransformer_.def("errorCodeIfVoxelPositionOutOfRange", [](IJKCoordinateTransformer* self, DoubleVector3Adapter::AdaptedType voxelPosition) { return self->ErrorCodeIfVoxelPositionOutOfRange(voxelPosition); }, py::arg("voxelPosition").none(false), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_ErrorCodeIfVoxelPositionOutOfRange));

//AUTOGEN-END   

// IMPLEMENTED :  IJKCoordinateTransformer_.def("IJKGrid"                     , static_cast<const native::IJKGridDefinition &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::IJKGrid), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKGrid));
// IMPLEMENTED :  IJKCoordinateTransformer_.def("IJKSize"                     , [](IJKCoordinateTransformer* self) { return (IntVector3Adapter::AdaptedType)(self->IJKSize()); }, py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKSize));
// IMPLEMENTED :  IJKCoordinateTransformer_.def("IJKToVoxelDimensionMap"      , [](IJKCoordinateTransformer* self) { return (IntVector3Adapter::AdaptedType)(self->IJKToVoxelDimensionMap()); }, py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKToVoxelDimensionMap));
// IMPLEMENTED :  IJKCoordinateTransformer_.def("IJKToWorldTransform"         , static_cast<const native::DoubleMatrix4x4 &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::IJKToWorldTransform), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKToWorldTransform));
// IMPLEMENTED :  IJKCoordinateTransformer_.def("worldToIJKTransform"         , static_cast<const native::DoubleMatrix4x4 &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::WorldToIJKTransform), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_WorldToIJKTransform));
// IMPLEMENTED :  IJKCoordinateTransformer_.def("IJKAnnotationStart"          , [](IJKCoordinateTransformer* self) { return (DoubleVector3Adapter::AdaptedType)(self->IJKAnnotationStart()); }, py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKAnnotationStart));
// IMPLEMENTED :  IJKCoordinateTransformer_.def("IJKAnnotationEnd"            , [](IJKCoordinateTransformer* self) { return (DoubleVector3Adapter::AdaptedType)(self->IJKAnnotationEnd()); }, py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKAnnotationEnd));
// IMPLEMENTED :  IJKCoordinateTransformer_.def("annotationsDefined"          , static_cast<bool(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::AnnotationsDefined), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_AnnotationsDefined));
  
  IJKCoordinateTransformer_.def_property_readonly("IJKGrid"                     , static_cast<const native::IJKGridDefinition &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::IJKGrid), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKGrid));
  IJKCoordinateTransformer_.def_property_readonly("IJKSize"                     , [](IJKCoordinateTransformer* self) { return (IntVector3Adapter::AdaptedType)(self->IJKSize()); }, py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKSize));
  IJKCoordinateTransformer_.def_property_readonly("IJKToVoxelDimensionMap"      , [](IJKCoordinateTransformer* self) { return (IntVector3Adapter::AdaptedType)(self->IJKToVoxelDimensionMap()); }, py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKToVoxelDimensionMap));
  IJKCoordinateTransformer_.def_property_readonly("IJKToWorldTransform"         , static_cast<const native::DoubleMatrix4x4 &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::IJKToWorldTransform), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKToWorldTransform));
  IJKCoordinateTransformer_.def_property_readonly("worldToIJKTransform"         , static_cast<const native::DoubleMatrix4x4 &(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::WorldToIJKTransform), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_WorldToIJKTransform));
  IJKCoordinateTransformer_.def_property_readonly("IJKAnnotationStart"          , [](IJKCoordinateTransformer* self) { return (DoubleVector3Adapter::AdaptedType)(self->IJKAnnotationStart()); }, py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKAnnotationStart));
  IJKCoordinateTransformer_.def_property_readonly("IJKAnnotationEnd"            , [](IJKCoordinateTransformer* self) { return (DoubleVector3Adapter::AdaptedType)(self->IJKAnnotationEnd()); }, py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_IJKAnnotationEnd));
  IJKCoordinateTransformer_.def_property_readonly("annotationsDefined"          , static_cast<bool(IJKCoordinateTransformer::*)() const>(&IJKCoordinateTransformer::AnnotationsDefined), py::call_guard<py::gil_scoped_release>(), OPENVDS_DOCSTRING(IJKCoordinateTransformer_AnnotationsDefined));
}

