/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;

/**
 * Options for opening a VDS in AWS
 * 
 */
public class AWSOpenOptions extends OpenOptions {

    native private static long ctorImpl();
    
    public AWSOpenOptions() {
    
        super(ctorImpl());
    
    }

    native private static long ctor2Impl(String bucket, String key, String region, String endpointOverride, int connectionTimeoutMs, int requestTimeoutMs, boolean disableInitApi);
    
    /**
     * AWSOpenOptions constructor
     * 
     * @param bucket The bucket of the VDS
     * @param key The key prefix of the VDS
     * @param region The region of the bucket of the VDS
     * @param endpointOverride This parameter allows to override the endpoint url
     * @param connectionTimeoutMs This parameter allows to override the time a connection can spend on connecting to AWS
     * @param requestTimeoutMs This paramter allows to override the time a request can take
     */
    public AWSOpenOptions(String bucket, String key, String region, String endpointOverride, int connectionTimeoutMs, int requestTimeoutMs, boolean disableInitApi) {
    
        super(ctor2Impl(bucket, key, region, endpointOverride, connectionTimeoutMs, requestTimeoutMs, disableInitApi));
    
    }


    private native String getBucketImpl(long native_object);
    public String getBucket() {
        return getBucketImpl(this.getNativeObject());
    }


    private native String getKeyImpl(long native_object);
    public String getKey() {
        return getKeyImpl(this.getNativeObject());
    }


    private native String getRegionImpl(long native_object);
    public String getRegion() {
        return getRegionImpl(this.getNativeObject());
    }


    private native String getEndpointOverrideImpl(long native_object);
    public String getEndpointOverride() {
        return getEndpointOverrideImpl(this.getNativeObject());
    }


    private native String getAccessKeyIdImpl(long native_object);
    public String getAccessKeyId() {
        return getAccessKeyIdImpl(this.getNativeObject());
    }


    private native String getSecretKeyImpl(long native_object);
    public String getSecretKey() {
        return getSecretKeyImpl(this.getNativeObject());
    }


    private native String getSessionTokenImpl(long native_object);
    public String getSessionToken() {
        return getSessionTokenImpl(this.getNativeObject());
    }


    private native String getExpirationImpl(long native_object);
    public String getExpiration() {
        return getExpirationImpl(this.getNativeObject());
    }


    private native String getLogFilenamePrefixImpl(long native_object);
    public String getLogFilenamePrefix() {
        return getLogFilenamePrefixImpl(this.getNativeObject());
    }


    private native String getLoglevelImpl(long native_object);
    public String getLoglevel() {
        return getLoglevelImpl(this.getNativeObject());
    }


    private native int getConnectionTimeoutMsImpl(long native_object);
    public int getConnectionTimeoutMs() {
        return getConnectionTimeoutMsImpl(this.getNativeObject());
    }


    private native int getRequestTimeoutMsImpl(long native_object);
    public int getRequestTimeoutMs() {
        return getRequestTimeoutMsImpl(this.getNativeObject());
    }


    private native boolean getDisableInitApiImpl(long native_object);
    public boolean getDisableInitApi() {
        return getDisableInitApiImpl(this.getNativeObject());
    }

    AWSOpenOptions(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static AWSOpenOptions fromNativeObject(long nativeobject) {
        return new AWSOpenOptions(nativeobject);
    }




}
