/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;

/**
 * Options for opening a VDS with presigned Azure url
 * 
 */
public class AzurePresignedOpenOptions extends OpenOptions {

    native private static long ctorImpl();
    
    public AzurePresignedOpenOptions() {
    
        super(ctorImpl());
    
    }

    native private static long ctor2Impl(String baseUrl, String urlSuffix);
    
    /**
     * AzurePresignedOpenOptions constructor
     * 
     * @param baseUrl The base url for the VDS
     * @param urlSuffix The suffix of the presigned url
     */
    public AzurePresignedOpenOptions(String baseUrl, String urlSuffix) {
    
        super(ctor2Impl(baseUrl, urlSuffix));
    
    }

    AzurePresignedOpenOptions(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static AzurePresignedOpenOptions fromNativeObject(long nativeobject) {
        return new AzurePresignedOpenOptions(nativeobject);
    }




}
