/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;

/**
 * Options for opening a VDS in Azure
 * 
 */
public class AzureOpenOptions extends OpenOptions {

    native private static long ctorImpl();
    
    public AzureOpenOptions() {
    
        super(ctorImpl());
    
    }

    native private static long ctor2Impl(String connectionString, String container, String blob);
    
    /**
     * AzureOpenOptions constructor
     * 
     * @param connectionString The connectionString for the VDS
     * @param container The container of the VDS
     * @param blob The blob prefix of the VDS
     */
    public AzureOpenOptions(String connectionString, String container, String blob) {
    
        super(ctor2Impl(connectionString, container, blob));
    
    }

    native private static long ctor3Impl(String connectionString, String container, String blob, int parallelism_factor, int max_execution_time);
    
    /**
     * AzureOpenOptions constructor
     * 
     * @param connectionString The connectionString for the VDS
     * @param container The container of the VDS
     * @param blob The blob prefix of the VDS
     * @param parallelism_factor The parallelism factor setting for the Azure Blob Storage library
     * @param max_execution_time The max execution time setting for the Azure Blob Storage library
     */
    public AzureOpenOptions(String connectionString, String container, String blob, int parallelism_factor, int max_execution_time) {
    
        super(ctor3Impl(connectionString, container, blob, parallelism_factor, max_execution_time));
    
    }

    ///AUTOGEN-OK: CXX_METHOD AzureOpenOptionsBearer static OpenVDS::AzureOpenOptions (const std::string &, const std::string &, const std::string &, const std::string &) FUNCTIONPROTO
    native private static long AzureOpenOptionsBearerImpl(String accountName, String bearerToken, String container, String blob);

    /**
     * AzureOpenOptions factory function for bearer token based authentication
     * 
     * @param bearerToken The bearer token
     * @param container The container of the VDS
     * @param blob The blob prefix of the VDS
     * @return A valid AzureOpenOptions
     */
    public static AzureOpenOptions azureOpenOptionsBearer(String accountName, String bearerToken, String container, String blob) {
        return AzureOpenOptions.fromNativeObject(AzureOpenOptionsBearerImpl(accountName, bearerToken, container, blob));
    }

    AzureOpenOptions(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static AzureOpenOptions fromNativeObject(long nativeobject) {
        return new AzureOpenOptions(nativeobject);
    }




}
