//=============================================================================
// <copyright>
// Copyright (c) 2021 Bluware Inc. All rights reserved.
//
// All rights are reserved. Reproduction or transmission in whole or in part,
// in any form or by any means, electronic, mechanical or otherwise,
// is prohibited without the prior written permission of the copyright owner.
// </copyright>
//=============================================================================

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public class DMSOpenOptions extends OpenOptions {

    native private static long ctorImpl();
    
    public DMSOpenOptions() {
    
        super(ctorImpl());
    
    }

    native private static long ctor2Impl(String sdAuthorityUrl, String sdApiKey, String sdToken, String datasetPath, int logLevel, String authTokenUrl, String refreshToken, String clientId, String clientSecret, String scopes, boolean useFileNameForSingleFileDatasets);
    
    public DMSOpenOptions(String sdAuthorityUrl, String sdApiKey, String sdToken, String datasetPath, int logLevel, String authTokenUrl, String refreshToken, String clientId, String clientSecret, String scopes, boolean useFileNameForSingleFileDatasets) {
    
        super(ctor2Impl(sdAuthorityUrl, sdApiKey, sdToken, datasetPath, logLevel, authTokenUrl, refreshToken, clientId, clientSecret, scopes, useFileNameForSingleFileDatasets));
    
    }

    DMSOpenOptions(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static DMSOpenOptions fromNativeObject(long nativeobject) {
        return new DMSOpenOptions(nativeobject);
    }




}
