/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public class DMSOpenOptions extends OpenOptions {

    native private static long ctorImpl();
    
    public DMSOpenOptions() {
    
        super(ctorImpl());
    
    }

    native private static long ctor2Impl(String sdAuthorityUrl, String sdApiKey, String sdToken, String datasetPath, int logLevel, String authTokenUrl, String refreshToken, String clientId, String clientSecret, String scopes, boolean useFileNameForSingleFileDatasets);
    
    public DMSOpenOptions(String sdAuthorityUrl, String sdApiKey, String sdToken, String datasetPath, int logLevel, String authTokenUrl, String refreshToken, String clientId, String clientSecret, String scopes, boolean useFileNameForSingleFileDatasets) {
    
        super(ctor2Impl(sdAuthorityUrl, sdApiKey, sdToken, datasetPath, logLevel, authTokenUrl, refreshToken, clientId, clientSecret, scopes, useFileNameForSingleFileDatasets));
    
    }

    ///AUTOGEN-OK: FIELD_DECL sdAuthorityUrl std::string RECORD
    native private String getSdAuthorityUrlImpl(long native_object);
    public String getSdAuthorityUrl() {
        return getSdAuthorityUrlImpl(getNativeObject());
    }

    ///AUTOGEN-OK: FIELD_DECL sdApiKey std::string RECORD
    native private String getSdApiKeyImpl(long native_object);
    public String getSdApiKey() {
        return getSdApiKeyImpl(getNativeObject());
    }

    ///AUTOGEN-OK: FIELD_DECL sdToken std::string RECORD
    native private String getSdTokenImpl(long native_object);
    public String getSdToken() {
        return getSdTokenImpl(getNativeObject());
    }

    ///AUTOGEN-OK: FIELD_DECL datasetPath std::string RECORD
    native private String getDatasetPathImpl(long native_object);
    public String getDatasetPath() {
        return getDatasetPathImpl(getNativeObject());
    }

    ///AUTOGEN-OK: FIELD_DECL logLevel int INT
    native private int getLogLevelImpl(long native_object);
    public int getLogLevel() {
        return getLogLevelImpl(getNativeObject());
    }

    ///AUTOGEN-OK: FIELD_DECL authTokenUrl std::string RECORD
    native private String getAuthTokenUrlImpl(long native_object);
    public String getAuthTokenUrl() {
        return getAuthTokenUrlImpl(getNativeObject());
    }

    ///AUTOGEN-OK: FIELD_DECL refreshToken std::string RECORD
    native private String getRefreshTokenImpl(long native_object);
    public String getRefreshToken() {
        return getRefreshTokenImpl(getNativeObject());
    }

    ///AUTOGEN-OK: FIELD_DECL clientId std::string RECORD
    native private String getClientIdImpl(long native_object);
    public String getClientId() {
        return getClientIdImpl(getNativeObject());
    }

    ///AUTOGEN-OK: FIELD_DECL clientSecret std::string RECORD
    native private String getClientSecretImpl(long native_object);
    public String getClientSecret() {
        return getClientSecretImpl(getNativeObject());
    }

    ///AUTOGEN-OK: FIELD_DECL scopes std::string RECORD
    native private String getScopesImpl(long native_object);
    public String getScopes() {
        return getScopesImpl(getNativeObject());
    }

    ///AUTOGEN-OK: FIELD_DECL useFileNameForSingleFileDatasets bool BOOL
    native private boolean getUseFileNameForSingleFileDatasetsImpl(long native_object);
    public boolean getUseFileNameForSingleFileDatasets() {
        return getUseFileNameForSingleFileDatasetsImpl(getNativeObject());
    }

    DMSOpenOptions(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static DMSOpenOptions fromNativeObject(long nativeobject) {
        return new DMSOpenOptions(nativeobject);
    }




}
