
/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.opengroup.openvds;
import java.nio.*;

// THIS FILE WAS AUTOGENERATED BY 'make-vector-classes.py' DO NOT EDIT!

public class FloatVector3 extends ByteBufferBackedObject {

    public FloatVector3() {
        this.createByteBuffer(Float.BYTES * 3 * 1);
    }

    public FloatVector3(float x, float y, float z) {
        this.createByteBuffer(Float.BYTES * 3);
        this.set(x, y, z);
    }

    public FloatVector3(java.nio.ByteBuffer bytebuffer, int byteoffset) {
        super(bytebuffer, byteoffset, Float.BYTES * 3);
    }

    public FloatVector3(FloatVector3 rhs) {
        this.createByteBuffer(Float.BYTES * 3);
        this.set(rhs.getX(), rhs.getY(), rhs.getZ());
    }

    public FloatVector3(float[] array) {
        if (array == null) {
            throw new IllegalArgumentException("array may not be null.");
        }
        if (array.length != 3) {
            throw new IllegalArgumentException("array must be of length 3. ");
        }
        this.createByteBuffer(Float.BYTES * 3 * 1);
        this.getManagedBuffer().put(array);
    }

    public boolean equals(Object other) {
        if (other == this) return true;
        if (other == null) return false;
        if (getClass() != other.getClass()) return false;
        FloatVector3 real_other = (FloatVector3)other;
        return (this.getX() == real_other.getX() &&
                this.getY() == real_other.getY() &&
                this.getZ() == real_other.getZ());
    }

    void put(ManagedBuffer managedbuffer, int byteoffset) {
        managedbuffer.putFloat(0 * Float.BYTES + byteoffset, this.getX());
        managedbuffer.putFloat(1 * Float.BYTES + byteoffset, this.getY());
        managedbuffer.putFloat(2 * Float.BYTES + byteoffset, this.getZ());
    }

    public void set(float x, float y, float z) {
        this.getManagedBuffer().putFloat(0 * Float.BYTES, x);
        this.getManagedBuffer().putFloat(1 * Float.BYTES, y);
        this.getManagedBuffer().putFloat(2 * Float.BYTES, z);
    }

    public void setX(float value) {
        this.getManagedBuffer().putFloat(0 * Float.BYTES, value);
    }


    public void setY(float value) {
        this.getManagedBuffer().putFloat(1 * Float.BYTES, value);
    }


    public void setZ(float value) {
        this.getManagedBuffer().putFloat(2 * Float.BYTES, value);
    }

    public float getX() {
        return this.getManagedBuffer().getFloat(0 * Float.BYTES);
    }


    public float getY() {
        return this.getManagedBuffer().getFloat(1 * Float.BYTES);
    }


    public float getZ() {
        return this.getManagedBuffer().getFloat(2 * Float.BYTES);
    }

    public String toString() {
        String value = "(";
        for (int i = 0; i < 3; ++i)
        {
            if (i > 0)
                value = value + ", ";
            value = value + this.getManagedBuffer().getFloat(i * Float.BYTES);
        }
        value = value + ")";
        return value;
    }

    public float[] toArray() {
        return new float[]{ getX(), getY(), getZ() };
    }

    public static final int BYTES = Float.BYTES * 3 * 1;
}

