//=============================================================================
// <copyright>
// Copyright (c) 2021 Bluware Inc. All rights reserved.
//
// All rights are reserved. Reproduction or transmission in whole or in part,
// in any form or by any means, electronic, mechanical or otherwise,
// is prohibited without the prior written permission of the copyright owner.
// </copyright>
//=============================================================================

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;

/**
 * Credentials for opening a VDS in Google Cloud Storage
 * by the string containing json with credentials
 * Using signed URL mechanism
 * 
 */
public class GoogleCredentialsSignedUrlJson extends ManagedBase {

    native private static long ctorImpl(String region, String json);
    
    /**
     * GoogleCredentialsSignedUrlJson constructor
     * 
     * @param region The string containing the region required for signature generation
     * @param json The string containing json with credentials
     */
    public GoogleCredentialsSignedUrlJson(String region, String json) {
    
        super(ctorImpl(region, json));
    
    }




    GoogleCredentialsSignedUrlJson(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static GoogleCredentialsSignedUrlJson fromNativeObject(long nativeobject) {
        return new GoogleCredentialsSignedUrlJson(nativeobject);
    }




}
