//=============================================================================
// <copyright>
// Copyright (c) 2021 Bluware Inc. All rights reserved.
//
// All rights are reserved. Reproduction or transmission in whole or in part,
// in any form or by any means, electronic, mechanical or otherwise,
// is prohibited without the prior written permission of the copyright owner.
// </copyright>
//=============================================================================

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;

/**
 * Options for opening a VDS in Google Cloud Storage
 * 
 */
public class GoogleOpenOptions extends OpenOptions {
    
    public enum CredentialsType {
    
            Default(0),
            AccessToken(1),
            Path(2),
            Json(3),
            SignedUrl(16),
            SignedUrlPath(18),
            SignedUrlJson(19);
    
        private final int value;
    
        CredentialsType(int value) {
            this.value = value;
        }
    
        public int value() {
            return this.value;
        }
    
        public static CredentialsType fromInt(int value) {
            switch(value) {
            case 0: return Default;
            case 1: return AccessToken;
            case 2: return Path;
            case 3: return Json;
            case 16: return SignedUrl;
            case 18: return SignedUrlPath;
            case 19: return SignedUrlJson;
            }
            return CredentialsType.values()[0];
        }
    
    }

    native private static long ctorImpl();
    
    public GoogleOpenOptions() {
    
        super(ctorImpl());
    
    }

    native private static long ctor2Impl(String bucket, String pathPrefix);
    
    /**
     * GoogleOpenOptions constructor
     * 
     * @param bucket The bucket of the VDS
     * @param pathPrefix The prefix of the VDS
     */
    public GoogleOpenOptions(String bucket, String pathPrefix) {
    
        super(ctor2Impl(bucket, pathPrefix));
    
    }

    native private static long ctor3Impl(String bucket, String pathPrefix, long credentials);
    
    public GoogleOpenOptions(String bucket, String pathPrefix, GoogleCredentialsToken credentials) {
    
        super(ctor3Impl(bucket, pathPrefix, credentials.getNativeObject()));
    
    }

    native private static long ctor4Impl(String bucket, String pathPrefix, long credentials);
    
    public GoogleOpenOptions(String bucket, String pathPrefix, GoogleCredentialsPath credentials) {
    
        super(ctor4Impl(bucket, pathPrefix, credentials.getNativeObject()));
    
    }

    native private static long ctor5Impl(String bucket, String pathPrefix, long credentials);
    
    public GoogleOpenOptions(String bucket, String pathPrefix, GoogleCredentialsJson credentials) {
    
        super(ctor5Impl(bucket, pathPrefix, credentials.getNativeObject()));
    
    }

    native private static long ctor6Impl(String bucket, String pathPrefix, long credentials);
    
    public GoogleOpenOptions(String bucket, String pathPrefix, GoogleCredentialsSignedUrl credentials) {
    
        super(ctor6Impl(bucket, pathPrefix, credentials.getNativeObject()));
    
    }

    native private static long ctor7Impl(String bucket, String pathPrefix, long credentials);
    
    public GoogleOpenOptions(String bucket, String pathPrefix, GoogleCredentialsSignedUrlPath credentials) {
    
        super(ctor7Impl(bucket, pathPrefix, credentials.getNativeObject()));
    
    }

    native private static long ctor8Impl(String bucket, String pathPrefix, long credentials);
    
    public GoogleOpenOptions(String bucket, String pathPrefix, GoogleCredentialsSignedUrlJson credentials) {
    
        super(ctor8Impl(bucket, pathPrefix, credentials.getNativeObject()));
    
    }

    ///AUTOGEN-OK: CXX_METHOD SetSignedUrl bool () FUNCTIONPROTO
    native private boolean SetSignedUrlImpl(long native_object);
    public boolean setSignedUrl() {
        return SetSignedUrlImpl(getNativeObject());
    }

    GoogleOpenOptions(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static GoogleOpenOptions fromNativeObject(long nativeobject) {
        return new GoogleOpenOptions(nativeobject);
    }




}
