/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;

/**
 * Options for opening a VDS in Google Cloud Storage
 * 
 */
public class GoogleOpenOptions extends OpenOptions {
    
    public enum CredentialsType {
    
            Default(0),
            AccessToken(1),
            Path(2),
            Json(3),
            SignedUrl(16),
            SignedUrlPath(18),
            SignedUrlJson(19);
    
        private final int value;
    
        CredentialsType(int value) {
            this.value = value;
        }
    
        public int value() {
            return this.value;
        }
    
        public static CredentialsType fromInt(int value) {
            if (value == 0) return Default;
            if (value == 1) return AccessToken;
            if (value == 2) return Path;
            if (value == 3) return Json;
            if (value == 16) return SignedUrl;
            if (value == 18) return SignedUrlPath;
            if (value == 19) return SignedUrlJson;
            return CredentialsType.values()[0];
        }
    
    }

    ///AUTOGEN-OK: FIELD_DECL credentialsType OpenVDS::GoogleOpenOptions::CredentialsType ENUM
    native private long getCredentialsTypeImpl(long native_object);
    public GoogleOpenOptions.CredentialsType getCredentialsType() {
        return GoogleOpenOptions.CredentialsType.fromInt((int)getCredentialsTypeImpl(getNativeObject()));
    }

    ///AUTOGEN-OK: FIELD_DECL bucket std::string RECORD
    native private String getBucketImpl(long native_object);
    public String getBucket() {
        return getBucketImpl(getNativeObject());
    }

    ///AUTOGEN-OK: FIELD_DECL pathPrefix std::string RECORD
    native private String getPathPrefixImpl(long native_object);
    public String getPathPrefix() {
        return getPathPrefixImpl(getNativeObject());
    }

    ///AUTOGEN-OK: FIELD_DECL credentials std::string RECORD
    native private String getCredentialsImpl(long native_object);
    public String getCredentials() {
        return getCredentialsImpl(getNativeObject());
    }

    ///AUTOGEN-OK: FIELD_DECL storageClass std::string RECORD
    native private String getStorageClassImpl(long native_object);
    public String getStorageClass() {
        return getStorageClassImpl(getNativeObject());
    }

    ///AUTOGEN-OK: FIELD_DECL region std::string RECORD
    native private String getRegionImpl(long native_object);
    public String getRegion() {
        return getRegionImpl(getNativeObject());
    }

    native private static long ctorImpl();
    
    public GoogleOpenOptions() {
    
        super(ctorImpl());
    
    }

    native private static long ctor2Impl(String bucket, String pathPrefix);
    
    /**
     * GoogleOpenOptions constructor
     * 
     * @param bucket The bucket of the VDS
     * @param pathPrefix The prefix of the VDS
     */
    public GoogleOpenOptions(String bucket, String pathPrefix) {
    
        super(ctor2Impl(bucket, pathPrefix));
    
    }

    native private static long ctor3Impl(String bucket, String pathPrefix, long credentials);
    
    public GoogleOpenOptions(String bucket, String pathPrefix, GoogleCredentialsToken credentials) {
    
        super(ctor3Impl(bucket, pathPrefix, credentials.getNativeObject()));
    
    }

    native private static long ctor4Impl(String bucket, String pathPrefix, long credentials);
    
    public GoogleOpenOptions(String bucket, String pathPrefix, GoogleCredentialsPath credentials) {
    
        super(ctor4Impl(bucket, pathPrefix, credentials.getNativeObject()));
    
    }

    native private static long ctor5Impl(String bucket, String pathPrefix, long credentials);
    
    public GoogleOpenOptions(String bucket, String pathPrefix, GoogleCredentialsJson credentials) {
    
        super(ctor5Impl(bucket, pathPrefix, credentials.getNativeObject()));
    
    }

    native private static long ctor6Impl(String bucket, String pathPrefix, long credentials);
    
    public GoogleOpenOptions(String bucket, String pathPrefix, GoogleCredentialsSignedUrl credentials) {
    
        super(ctor6Impl(bucket, pathPrefix, credentials.getNativeObject()));
    
    }

    native private static long ctor7Impl(String bucket, String pathPrefix, long credentials);
    
    public GoogleOpenOptions(String bucket, String pathPrefix, GoogleCredentialsSignedUrlPath credentials) {
    
        super(ctor7Impl(bucket, pathPrefix, credentials.getNativeObject()));
    
    }

    native private static long ctor8Impl(String bucket, String pathPrefix, long credentials);
    
    public GoogleOpenOptions(String bucket, String pathPrefix, GoogleCredentialsSignedUrlJson credentials) {
    
        super(ctor8Impl(bucket, pathPrefix, credentials.getNativeObject()));
    
    }

    ///AUTOGEN-OK: CXX_METHOD SetSignedUrl bool () FUNCTIONPROTO
    native private boolean SetSignedUrlImpl(long native_object);
    public boolean setSignedUrl() {
        return SetSignedUrlImpl(getNativeObject());
    }

    GoogleOpenOptions(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject, boolean isDisposing);

    @Override
    protected void onDisposing(long native_object, boolean isDisposing) {
        dtorImpl(native_object, isDisposing);
    }

    static GoogleOpenOptions fromNativeObject(long nativeobject) {
        return new GoogleOpenOptions(nativeobject);
    }




}
