//=============================================================================
// <copyright>
// Copyright (c) 2021 Bluware Inc. All rights reserved.
//
// All rights are reserved. Reproduction or transmission in whole or in part,
// in any form or by any means, electronic, mechanical or otherwise,
// is prohibited without the prior written permission of the copyright owner.
// </copyright>
//=============================================================================

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;

/**
 * Credentials for opening a VDS in Google Cloud Storage
 * by the string containing json with credentials
 * Using OAuth
 * 
 */
public class GoogleCredentialsJson extends ManagedBase {

    native private static long ctorImpl(String json);
    
    /**
     * GoogleCredentialsJson constructor
     * 
     * @param json The string containing json with credentials
     */
    public GoogleCredentialsJson(String json) {
    
        super(ctorImpl(json));
    
    }


    GoogleCredentialsJson(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static GoogleCredentialsJson fromNativeObject(long nativeobject) {
        return new GoogleCredentialsJson(nativeobject);
    }




}
