/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;

/**
 * Credentials for opening a VDS in Google Cloud Storage
 * by using the string containing an access token
 * Using OAuth
 * 
 */
public class GoogleCredentialsToken extends ManagedBase {

    native private static long ctorImpl(String token);
    
    /**
     * GoogleCredentialsToken constructor
     * 
     * @param token The string containing an access token
     */
    public GoogleCredentialsToken(String token) {
    
        super(ctorImpl(token));
    
    }


    GoogleCredentialsToken(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static GoogleCredentialsToken fromNativeObject(long nativeobject) {
        return new GoogleCredentialsToken(nativeobject);
    }




}
