/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;

/**
 * Options for opening a VDS with a plain http url.
 * If there are query parameters in then they will be appended to the different sub urls.
 * The resulting IO backend will not support uploading data.
 * 
 */
public class HttpOpenOptions extends OpenOptions {

    ///AUTOGEN-OK: FIELD_DECL url std::string RECORD
    native private String getUrlImpl(long native_object);
    public String getUrl() {
        return getUrlImpl(getNativeObject());
    }

    native private static long ctorImpl();
    
    public HttpOpenOptions() {
    
        super(ctorImpl());
    
    }

    native private static long ctor2Impl(String url);
    
    /**
     * HttpOpenOptions constructor
     * 
     * @param url The http base url of the VDS
     */
    public HttpOpenOptions(String url) {
    
        super(ctor2Impl(ManagedBase.requireNonNull(url, "url may not be null")));
    
    }

    HttpOpenOptions(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject, boolean isDisposing);

    @Override
    protected void onDisposing(long native_object, boolean isDisposing) {
        dtorImpl(native_object, isDisposing);
    }

    static HttpOpenOptions fromNativeObject(long nativeobject) {
        if (nativeobject == 0) {
           return null;
        }
        return new HttpOpenOptions(nativeobject);
    }




}
