//=============================================================================
// <copyright>
// Copyright (c) 2021 Bluware Inc. All rights reserved.
//
// All rights are reserved. Reproduction or transmission in whole or in part,
// in any form or by any means, electronic, mechanical or otherwise,
// is prohibited without the prior written permission of the copyright owner.
// </copyright>
//=============================================================================

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;

/**
 * Options for opening a VDS with a plain http url.
 * If there are query parameters in then they will be appended to the different sub urls.
 * The resulting IO backend will not support uploading data.
 * 
 */
public class HttpOpenOptions extends OpenOptions {

    native private static long ctorImpl();
    
    public HttpOpenOptions() {
    
        super(ctorImpl());
    
    }

    native private static long ctor2Impl(String url);
    
    /**
     * HttpOpenOptions constructor
     * 
     * @param url The http base url of the VDS
     */
    public HttpOpenOptions(String url) {
    
        super(ctor2Impl(url));
    
    }

    HttpOpenOptions(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static HttpOpenOptions fromNativeObject(long nativeobject) {
        return new HttpOpenOptions(nativeobject);
    }




}
