/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;

/**
 * IJKCoordinateTransformer may be used to transform between the following three-dimensional index and coordinate systems of a volume:
 * 
 * IJK Index - a 3D index into the volume based on IJK dimensions.
 * Dimensions I and J are usually horizontal directions, whereas K is usually the vertical direction.
 * Transforms are provided to/from integer IJK indexes and also floating-point IJK positions.
 * ///
 * World Coordinate - a world position, related to IJK through the IJK grid definition provided on construction.
 * ///
 * Annotation Coordinate - a coordinate position based on the annotation axes of the volume (inline, crossline, depth, time, etc.).
 * The order of annotation coordinate values correspond to the volume axes for each IJK dimension.
 * That is, the annotation coordinate X value specifies the coordinate for the annotation axis corresponding to the I direction, and so on.
 * When used with a VDS, annotation coordinates are based on the VDS axis descriptors.
 * 
 * Voxel Index - a 3D index into the volume based on volume data dimesions, where
 * dimension 0 is the data dimension that changes the fastest,
 * dimension 1 is the data dimension that changes second fastest, etc.
 * Transforms are provided to/from integer voxel indexes and also floating-point voxel positions.
 * When used with a VDS, voxel index 0 refers to dimension 0, ranging from 0 to Dimension0Size - 1, and so on.
 * The relationship between IJK dimensions and voxel dimensions is controlled by the IJK dimension map provided at construction.
 * If the dimension map is (0, 1, 2), the IJK dimensions are the same as voxel dimensions.
 * However, it is often the case that the dimension map is not (0, 1, 2), and so IJK dimensions are not the same as voxel dimensions, especially when used with a VDS.
 * When used with a VDS, the dimension map is often set to (2, 1, 0), meaning that IJK corresponds to voxel dimensions (2, 1, 0).
 * However, this is not a strict rule, and the dimension map will generally be defined based on the VDS axis descriptors.
 * If a particular VDS axis is given the name "I", "J", or "K", that axis index will be considered as dimension I, J, or K. This is not very common.
 * If a particular VDS axis is given the name "Inline", it will be considered as dimension I.
 * If a particular VDS axis is given the name "Crossline", it will be considered as dimension J.
 * If a particular VDS axis is given the name "Time", "Depth", or "Sample", it will be considered as dimension K.
 * 
 */
public class IJKCoordinateTransformer extends ManagedBase {

    native private static long ctorImpl();
    
    public IJKCoordinateTransformer() {
    
        super(ctorImpl());
    
    }

    native private static long ctor2Impl(ByteBuffer ijkGridDefinition, long ijkGridDefinition_byteoffset, ByteBuffer ijkSize, long ijkSize_byteoffset);
    
    public IJKCoordinateTransformer(IJKGridDefinition ijkGridDefinition, IntVector3 ijkSize) {
    
        super(ctor2Impl(ManagedBase.requireNonNull(ijkGridDefinition, "ijkGridDefinition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkGridDefinition, "ijkGridDefinition may not be null").getByteBufferOffset(), ManagedBase.requireNonNull(ijkSize, "ijkSize may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkSize, "ijkSize may not be null").getByteBufferOffset()));
    
    }

    native private static long ctor3Impl(ByteBuffer ijkGridDefinition, long ijkGridDefinition_byteoffset, ByteBuffer ijkSize, long ijkSize_byteoffset, ByteBuffer ijkToVoxelDimensionMap, long ijkToVoxelDimensionMap_byteoffset);
    
    public IJKCoordinateTransformer(IJKGridDefinition ijkGridDefinition, IntVector3 ijkSize, IntVector3 ijkToVoxelDimensionMap) {
    
        super(ctor3Impl(ManagedBase.requireNonNull(ijkGridDefinition, "ijkGridDefinition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkGridDefinition, "ijkGridDefinition may not be null").getByteBufferOffset(), ManagedBase.requireNonNull(ijkSize, "ijkSize may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkSize, "ijkSize may not be null").getByteBufferOffset(), ManagedBase.requireNonNull(ijkToVoxelDimensionMap, "ijkToVoxelDimensionMap may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkToVoxelDimensionMap, "ijkToVoxelDimensionMap may not be null").getByteBufferOffset()));
    
    }

    native private static long ctor4Impl(ByteBuffer vdsIJKGridDefinition, long vdsIJKGridDefinition_byteoffset, ByteBuffer ijkSize, long ijkSize_byteoffset);
    
    public IJKCoordinateTransformer(VDSIJKGridDefinition vdsIJKGridDefinition, IntVector3 ijkSize) {
    
        super(ctor4Impl(ManagedBase.requireNonNull(vdsIJKGridDefinition, "vdsIJKGridDefinition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(vdsIJKGridDefinition, "vdsIJKGridDefinition may not be null").getByteBufferOffset(), ManagedBase.requireNonNull(ijkSize, "ijkSize may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkSize, "ijkSize may not be null").getByteBufferOffset()));
    
    }

    native private static long ctor5Impl(ByteBuffer ijkGridDefinition, long ijkGridDefinition_byteoffset, ByteBuffer ijkSize, long ijkSize_byteoffset, ByteBuffer ijkAnnotationStart, long ijkAnnotationStart_byteoffset, ByteBuffer ijkAnnotationEnd, long ijkAnnotationEnd_byteoffset);
    
    public IJKCoordinateTransformer(IJKGridDefinition ijkGridDefinition, IntVector3 ijkSize, DoubleVector3 ijkAnnotationStart, DoubleVector3 ijkAnnotationEnd) {
    
        super(ctor5Impl(ManagedBase.requireNonNull(ijkGridDefinition, "ijkGridDefinition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkGridDefinition, "ijkGridDefinition may not be null").getByteBufferOffset(), ManagedBase.requireNonNull(ijkSize, "ijkSize may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkSize, "ijkSize may not be null").getByteBufferOffset(), ManagedBase.requireNonNull(ijkAnnotationStart, "ijkAnnotationStart may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkAnnotationStart, "ijkAnnotationStart may not be null").getByteBufferOffset(), ManagedBase.requireNonNull(ijkAnnotationEnd, "ijkAnnotationEnd may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkAnnotationEnd, "ijkAnnotationEnd may not be null").getByteBufferOffset()));
    
    }

    native private static long ctor6Impl(ByteBuffer ijkGridDefinition, long ijkGridDefinition_byteoffset, ByteBuffer ijkSize, long ijkSize_byteoffset, ByteBuffer ijkToVoxelDimensionMap, long ijkToVoxelDimensionMap_byteoffset, ByteBuffer ijkAnnotationStart, long ijkAnnotationStart_byteoffset, ByteBuffer ijkAnnotationEnd, long ijkAnnotationEnd_byteoffset);
    
    public IJKCoordinateTransformer(IJKGridDefinition ijkGridDefinition, IntVector3 ijkSize, IntVector3 ijkToVoxelDimensionMap, DoubleVector3 ijkAnnotationStart, DoubleVector3 ijkAnnotationEnd) {
    
        super(ctor6Impl(ManagedBase.requireNonNull(ijkGridDefinition, "ijkGridDefinition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkGridDefinition, "ijkGridDefinition may not be null").getByteBufferOffset(), ManagedBase.requireNonNull(ijkSize, "ijkSize may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkSize, "ijkSize may not be null").getByteBufferOffset(), ManagedBase.requireNonNull(ijkToVoxelDimensionMap, "ijkToVoxelDimensionMap may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkToVoxelDimensionMap, "ijkToVoxelDimensionMap may not be null").getByteBufferOffset(), ManagedBase.requireNonNull(ijkAnnotationStart, "ijkAnnotationStart may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkAnnotationStart, "ijkAnnotationStart may not be null").getByteBufferOffset(), ManagedBase.requireNonNull(ijkAnnotationEnd, "ijkAnnotationEnd may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkAnnotationEnd, "ijkAnnotationEnd may not be null").getByteBufferOffset()));
    
    }

    native private static long ctor7Impl(ByteBuffer vdsIJKGridDefinition, long vdsIJKGridDefinition_byteoffset, ByteBuffer ijkSize, long ijkSize_byteoffset, ByteBuffer ijkAnnotationStart, long ijkAnnotationStart_byteoffset, ByteBuffer ijkAnnotationEnd, long ijkAnnotationEnd_byteoffset);
    
    public IJKCoordinateTransformer(VDSIJKGridDefinition vdsIJKGridDefinition, IntVector3 ijkSize, DoubleVector3 ijkAnnotationStart, DoubleVector3 ijkAnnotationEnd) {
    
        super(ctor7Impl(ManagedBase.requireNonNull(vdsIJKGridDefinition, "vdsIJKGridDefinition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(vdsIJKGridDefinition, "vdsIJKGridDefinition may not be null").getByteBufferOffset(), ManagedBase.requireNonNull(ijkSize, "ijkSize may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkSize, "ijkSize may not be null").getByteBufferOffset(), ManagedBase.requireNonNull(ijkAnnotationStart, "ijkAnnotationStart may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkAnnotationStart, "ijkAnnotationStart may not be null").getByteBufferOffset(), ManagedBase.requireNonNull(ijkAnnotationEnd, "ijkAnnotationEnd may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkAnnotationEnd, "ijkAnnotationEnd may not be null").getByteBufferOffset()));
    
    }

    ///AUTOGEN-OK: CXX_METHOD IJKGrid const OpenVDS::IJKGridDefinition &() const FUNCTIONPROTO
    native private void IJKGridImpl(long native_object, ByteBuffer result, long result_byteoffset);

    /**
     * The IJK grid definition relating IJK coordinates to world XYZ coordinates
     * 
     */
    public IJKGridDefinition IJKGrid() {
        IJKGridDefinition result = new IJKGridDefinition();
        IJKGridImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD IJKSize const OpenVDS::Vector<int, 3> &() const FUNCTIONPROTO
    native private void IJKSizeImpl(long native_object, ByteBuffer result, long result_byteoffset);

    /**
     * The number of voxels in each IJK dimension
     * 
     */
    public IntVector3 IJKSize() {
        IntVector3 result = new IntVector3();
        IJKSizeImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD IJKToVoxelDimensionMap const OpenVDS::Vector<int, 3> &() const FUNCTIONPROTO
    native private void IJKToVoxelDimensionMapImpl(long native_object, ByteBuffer result, long result_byteoffset);

    /**
     * Mapping from IJK to voxel volume dimensions
     * 
     */
    public IntVector3 IJKToVoxelDimensionMap() {
        IntVector3 result = new IntVector3();
        IJKToVoxelDimensionMapImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD IJKToWorldTransform const OpenVDS::Matrix<double, 4> &() const FUNCTIONPROTO
    native private void IJKToWorldTransformImpl(long native_object, ByteBuffer result, long result_byteoffset);

    /**
     * The matrix used to transform from IJK coordinates to world coordinates
     * 
     */
    public DoubleMatrix4x4 IJKToWorldTransform() {
        DoubleMatrix4x4 result = new DoubleMatrix4x4();
        IJKToWorldTransformImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD WorldToIJKTransform const OpenVDS::Matrix<double, 4> &() const FUNCTIONPROTO
    native private void WorldToIJKTransformImpl(long native_object, ByteBuffer result, long result_byteoffset);

    /**
     * The matrix used to transform from world coordinates to IJK coordinates
     * 
     */
    public DoubleMatrix4x4 worldToIJKTransform() {
        DoubleMatrix4x4 result = new DoubleMatrix4x4();
        WorldToIJKTransformImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD IJKAnnotationStart const OpenVDS::Vector<double, 3> &() const FUNCTIONPROTO
    native private void IJKAnnotationStartImpl(long native_object, ByteBuffer result, long result_byteoffset);

    /**
     * The annotation start coordinates, corresponding to min IJK index (i.e. 0, 0, 0)
     * 
     */
    public DoubleVector3 IJKAnnotationStart() {
        DoubleVector3 result = new DoubleVector3();
        IJKAnnotationStartImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD IJKAnnotationEnd const OpenVDS::Vector<double, 3> &() const FUNCTIONPROTO
    native private void IJKAnnotationEndImpl(long native_object, ByteBuffer result, long result_byteoffset);

    /**
     * The annotation end coordinates, corresponding to max IJK index (i.e. IJKSize - (1, 1, 1))
     * 
     */
    public DoubleVector3 IJKAnnotationEnd() {
        DoubleVector3 result = new DoubleVector3();
        IJKAnnotationEndImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD AnnotationsDefined bool () const FUNCTIONPROTO
    native private boolean AnnotationsDefinedImpl(long native_object);

    /**
     * Whether or not the annotation start/end coordinates are set, which defines the annotation coordinate system
     * 
     */
    public boolean annotationsDefined() {
        return AnnotationsDefinedImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD IJKPositionToWorld OpenVDS::Vector<double, 3> (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private void IJKPositionToWorldImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer ijkPosition, long ijkPosition_byteoffset);

    /**
     * Transform the given IJK position to a world position
     * 
     */
    public DoubleVector3 IJKPositionToWorld(DoubleVector3 ijkPosition) {
        DoubleVector3 result = new DoubleVector3();
        IJKPositionToWorldImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(ijkPosition, "ijkPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkPosition, "ijkPosition may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD IJKIndexToWorld OpenVDS::Vector<double, 3> (const OpenVDS::Vector<int, 3> &) const FUNCTIONPROTO
    native private void IJKIndexToWorldImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer ijkIndex, long ijkIndex_byteoffset);

    /**
     * Transform the given IJK index to a world position
     * 
     */
    public DoubleVector3 IJKIndexToWorld(IntVector3 ijkIndex) {
        DoubleVector3 result = new DoubleVector3();
        IJKIndexToWorldImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(ijkIndex, "ijkIndex may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkIndex, "ijkIndex may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD IJKPositionToAnnotation OpenVDS::Vector<double, 3> (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private void IJKPositionToAnnotationImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer ijkPosition, long ijkPosition_byteoffset);

    /**
     * Transform the given IJK position to an annotation position
     * 
     */
    public DoubleVector3 IJKPositionToAnnotation(DoubleVector3 ijkPosition) {
        DoubleVector3 result = new DoubleVector3();
        IJKPositionToAnnotationImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(ijkPosition, "ijkPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkPosition, "ijkPosition may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD IJKIndexToAnnotation OpenVDS::Vector<double, 3> (const OpenVDS::Vector<int, 3> &) const FUNCTIONPROTO
    native private void IJKIndexToAnnotationImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer ijkIndex, long ijkIndex_byteoffset);

    /**
     * Transform the given IJK index to an annotation position
     * 
     */
    public DoubleVector3 IJKIndexToAnnotation(IntVector3 ijkIndex) {
        DoubleVector3 result = new DoubleVector3();
        IJKIndexToAnnotationImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(ijkIndex, "ijkIndex may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkIndex, "ijkIndex may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD IJKPositionToVoxelPosition OpenVDS::Vector<double, 3> (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private void IJKPositionToVoxelPositionImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer ijkPosition, long ijkPosition_byteoffset);

    /**
     * Transform the given IJK position to a voxel position
     * 
     */
    public DoubleVector3 IJKPositionToVoxelPosition(DoubleVector3 ijkPosition) {
        DoubleVector3 result = new DoubleVector3();
        IJKPositionToVoxelPositionImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(ijkPosition, "ijkPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkPosition, "ijkPosition may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD IJKIndexToVoxelIndex OpenVDS::Vector<int, 3> (const OpenVDS::Vector<int, 3> &) const FUNCTIONPROTO
    native private void IJKIndexToVoxelIndexImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer ijkIndex, long ijkIndex_byteoffset);

    /**
     * Transform the given IJK index to a voxel index
     * 
     */
    public IntVector3 IJKIndexToVoxelIndex(IntVector3 ijkIndex) {
        IntVector3 result = new IntVector3();
        IJKIndexToVoxelIndexImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(ijkIndex, "ijkIndex may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkIndex, "ijkIndex may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD WorldToIJKPosition OpenVDS::Vector<double, 3> (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private void WorldToIJKPositionImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer worldPosition, long worldPosition_byteoffset);

    /**
     * Transform the given world position to a IJK position
     * 
     */
    public DoubleVector3 worldToIJKPosition(DoubleVector3 worldPosition) {
        DoubleVector3 result = new DoubleVector3();
        WorldToIJKPositionImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(worldPosition, "worldPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(worldPosition, "worldPosition may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD WorldToIJKIndex OpenVDS::Vector<int, 3> (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private void WorldToIJKIndexImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer worldPosition, long worldPosition_byteoffset);

    /**
     * Transform the given world position to a IJK index
     * 
     */
    public IntVector3 worldToIJKIndex(DoubleVector3 worldPosition) {
        IntVector3 result = new IntVector3();
        WorldToIJKIndexImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(worldPosition, "worldPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(worldPosition, "worldPosition may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD WorldToAnnotation OpenVDS::Vector<double, 3> (OpenVDS::Vector<double, 3>) const FUNCTIONPROTO
    native private void WorldToAnnotationImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer worldPosition, long worldPosition_byteoffset);

    /**
     * Transform the given world position to an annotation position
     * 
     */
    public DoubleVector3 worldToAnnotation(DoubleVector3 worldPosition) {
        DoubleVector3 result = new DoubleVector3();
        WorldToAnnotationImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(worldPosition, "worldPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(worldPosition, "worldPosition may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD WorldToVoxelPosition OpenVDS::Vector<double, 3> (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private void WorldToVoxelPositionImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer worldPosition, long worldPosition_byteoffset);

    /**
     * Transform the given world position to a voxel position
     * 
     */
    public DoubleVector3 worldToVoxelPosition(DoubleVector3 worldPosition) {
        DoubleVector3 result = new DoubleVector3();
        WorldToVoxelPositionImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(worldPosition, "worldPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(worldPosition, "worldPosition may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD WorldToVoxelIndex OpenVDS::Vector<int, 3> (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private void WorldToVoxelIndexImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer worldPosition, long worldPosition_byteoffset);

    /**
     * Transform the given world position to a voxel index
     * 
     */
    public IntVector3 worldToVoxelIndex(DoubleVector3 worldPosition) {
        IntVector3 result = new IntVector3();
        WorldToVoxelIndexImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(worldPosition, "worldPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(worldPosition, "worldPosition may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD AnnotationToIJKPosition OpenVDS::Vector<double, 3> (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private void AnnotationToIJKPositionImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer annotationPosition, long annotationPosition_byteoffset);

    /**
     * Transform the given annotation position to a IJK position
     * 
     */
    public DoubleVector3 annotationToIJKPosition(DoubleVector3 annotationPosition) {
        DoubleVector3 result = new DoubleVector3();
        AnnotationToIJKPositionImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(annotationPosition, "annotationPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(annotationPosition, "annotationPosition may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD AnnotationToIJKIndex OpenVDS::Vector<int, 3> (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private void AnnotationToIJKIndexImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer annotationPosition, long annotationPosition_byteoffset);

    /**
     * Transform the given annotation position to a IJK index
     * 
     */
    public IntVector3 annotationToIJKIndex(DoubleVector3 annotationPosition) {
        IntVector3 result = new IntVector3();
        AnnotationToIJKIndexImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(annotationPosition, "annotationPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(annotationPosition, "annotationPosition may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD AnnotationToWorld OpenVDS::Vector<double, 3> (OpenVDS::Vector<double, 3>) const FUNCTIONPROTO
    native private void AnnotationToWorldImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer annotationPosition, long annotationPosition_byteoffset);

    /**
     * Transform the given annotation position to a world position
     * 
     */
    public DoubleVector3 annotationToWorld(DoubleVector3 annotationPosition) {
        DoubleVector3 result = new DoubleVector3();
        AnnotationToWorldImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(annotationPosition, "annotationPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(annotationPosition, "annotationPosition may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD AnnotationToVoxelPosition OpenVDS::Vector<double, 3> (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private void AnnotationToVoxelPositionImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer annotationPosition, long annotationPosition_byteoffset);

    /**
     * Transform the given annotation position to a voxel position
     * 
     */
    public DoubleVector3 annotationToVoxelPosition(DoubleVector3 annotationPosition) {
        DoubleVector3 result = new DoubleVector3();
        AnnotationToVoxelPositionImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(annotationPosition, "annotationPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(annotationPosition, "annotationPosition may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD AnnotationToVoxelIndex OpenVDS::Vector<int, 3> (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private void AnnotationToVoxelIndexImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer annotationPosition, long annotationPosition_byteoffset);

    /**
     * Transform the given annotation position to a voxel index
     * 
     */
    public IntVector3 annotationToVoxelIndex(DoubleVector3 annotationPosition) {
        IntVector3 result = new IntVector3();
        AnnotationToVoxelIndexImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(annotationPosition, "annotationPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(annotationPosition, "annotationPosition may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD VoxelPositionToIJKPosition OpenVDS::Vector<double, 3> (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private void VoxelPositionToIJKPositionImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer voxelPosition, long voxelPosition_byteoffset);

    /**
     * Transform the given voxel position to an IJK position
     * 
     */
    public DoubleVector3 voxelPositionToIJKPosition(DoubleVector3 voxelPosition) {
        DoubleVector3 result = new DoubleVector3();
        VoxelPositionToIJKPositionImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(voxelPosition, "voxelPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(voxelPosition, "voxelPosition may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD VoxelIndexToIJKIndex OpenVDS::Vector<int, 3> (const OpenVDS::Vector<int, 3> &) const FUNCTIONPROTO
    native private void VoxelIndexToIJKIndexImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer voxelIndex, long voxelIndex_byteoffset);

    /**
     * Transform the given voxel index to an IJK index
     * 
     */
    public IntVector3 voxelIndexToIJKIndex(IntVector3 voxelIndex) {
        IntVector3 result = new IntVector3();
        VoxelIndexToIJKIndexImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(voxelIndex, "voxelIndex may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(voxelIndex, "voxelIndex may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD VoxelPositionToWorld OpenVDS::Vector<double, 3> (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private void VoxelPositionToWorldImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer voxelPosition, long voxelPosition_byteoffset);

    /**
     * Transform the given voxel position to a world position
     * 
     */
    public DoubleVector3 voxelPositionToWorld(DoubleVector3 voxelPosition) {
        DoubleVector3 result = new DoubleVector3();
        VoxelPositionToWorldImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(voxelPosition, "voxelPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(voxelPosition, "voxelPosition may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD VoxelIndexToWorld OpenVDS::Vector<double, 3> (const OpenVDS::Vector<int, 3> &) const FUNCTIONPROTO
    native private void VoxelIndexToWorldImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer voxelIndex, long voxelIndex_byteoffset);

    /**
     * Transform the given voxel index to a world position
     * 
     */
    public DoubleVector3 voxelIndexToWorld(IntVector3 voxelIndex) {
        DoubleVector3 result = new DoubleVector3();
        VoxelIndexToWorldImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(voxelIndex, "voxelIndex may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(voxelIndex, "voxelIndex may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD VoxelPositionToAnnotation OpenVDS::Vector<double, 3> (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private void VoxelPositionToAnnotationImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer voxelPosition, long voxelPosition_byteoffset);

    /**
     * Transform the given voxel position to an annotation position
     * 
     */
    public DoubleVector3 voxelPositionToAnnotation(DoubleVector3 voxelPosition) {
        DoubleVector3 result = new DoubleVector3();
        VoxelPositionToAnnotationImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(voxelPosition, "voxelPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(voxelPosition, "voxelPosition may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD VoxelIndexToAnnotation OpenVDS::Vector<double, 3> (const OpenVDS::Vector<int, 3> &) const FUNCTIONPROTO
    native private void VoxelIndexToAnnotationImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer voxelIndex, long voxelIndex_byteoffset);

    /**
     * Transform the given voxel index to an annotation position
     * 
     */
    public DoubleVector3 voxelIndexToAnnotation(IntVector3 voxelIndex) {
        DoubleVector3 result = new DoubleVector3();
        VoxelIndexToAnnotationImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(voxelIndex, "voxelIndex may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(voxelIndex, "voxelIndex may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD IsIJKPositionOutOfRange bool (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private boolean IsIJKPositionOutOfRangeImpl(long native_object, ByteBuffer ijkPosition, long ijkPosition_byteoffset);

    /**
     * Determine whether the given IJK position is out of range
     * 
     */
    public boolean isIJKPositionOutOfRange(DoubleVector3 ijkPosition) {
        return IsIJKPositionOutOfRangeImpl(getNativeObject(), ManagedBase.requireNonNull(ijkPosition, "ijkPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkPosition, "ijkPosition may not be null").getByteBufferOffset());
    }

    ///AUTOGEN-OK: CXX_METHOD IsIJKIndexOutOfRange bool (const OpenVDS::Vector<int, 3> &) const FUNCTIONPROTO
    native private boolean IsIJKIndexOutOfRangeImpl(long native_object, ByteBuffer ijkIndex, long ijkIndex_byteoffset);

    /**
     * Determine whether the given IJK index is out of range
     * 
     */
    public boolean isIJKIndexOutOfRange(IntVector3 ijkIndex) {
        return IsIJKIndexOutOfRangeImpl(getNativeObject(), ManagedBase.requireNonNull(ijkIndex, "ijkIndex may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkIndex, "ijkIndex may not be null").getByteBufferOffset());
    }

    ///AUTOGEN-OK: CXX_METHOD IsVoxelPositionOutOfRange bool (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private boolean IsVoxelPositionOutOfRangeImpl(long native_object, ByteBuffer voxelPosition, long voxelPosition_byteoffset);

    /**
     * Determine whether the given voxel position is out of range
     * 
     */
    public boolean isVoxelPositionOutOfRange(DoubleVector3 voxelPosition) {
        return IsVoxelPositionOutOfRangeImpl(getNativeObject(), ManagedBase.requireNonNull(voxelPosition, "voxelPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(voxelPosition, "voxelPosition may not be null").getByteBufferOffset());
    }

    ///AUTOGEN-OK: CXX_METHOD IsVoxelIndexOutOfRange bool (const OpenVDS::Vector<int, 3> &) const FUNCTIONPROTO
    native private boolean IsVoxelIndexOutOfRangeImpl(long native_object, ByteBuffer voxelIndex, long voxelIndex_byteoffset);

    /**
     * Determine whether the given voxel index is out of range
     * 
     */
    public boolean isVoxelIndexOutOfRange(IntVector3 voxelIndex) {
        return IsVoxelIndexOutOfRangeImpl(getNativeObject(), ManagedBase.requireNonNull(voxelIndex, "voxelIndex may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(voxelIndex, "voxelIndex may not be null").getByteBufferOffset());
    }

    ///AUTOGEN-OK: CXX_METHOD ConvertIJKPositionToIndex OpenVDS::Vector<int, 3> (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private void ConvertIJKPositionToIndexImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer ijkPosition, long ijkPosition_byteoffset);

    /**
     * Convert the given IJK position to IJK index.
     * Return (-1, -1, -1) if any component is outside valid range.
     * 
     */
    public IntVector3 convertIJKPositionToIndex(DoubleVector3 ijkPosition) {
        IntVector3 result = new IntVector3();
        ConvertIJKPositionToIndexImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(ijkPosition, "ijkPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkPosition, "ijkPosition may not be null").getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD ConvertVoxelPositionToIndex OpenVDS::Vector<int, 3> (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private void ConvertVoxelPositionToIndexImpl(long native_object, ByteBuffer result, long result_byteoffset, ByteBuffer voxelPosition, long voxelPosition_byteoffset);

    /**
     * Convert the given voxel position to voxel index.
     * Return (-1, -1, -1) if any component is outside valid range.
     * 
     */
    public IntVector3 convertVoxelPositionToIndex(DoubleVector3 voxelPosition) {
        IntVector3 result = new IntVector3();
        ConvertVoxelPositionToIndexImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), ManagedBase.requireNonNull(voxelPosition, "voxelPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(voxelPosition, "voxelPosition may not be null").getByteBufferOffset());
        return result;
    }

    native private boolean operatorEQImpl(long nativeobject, long othernativeobject);
    
    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null)
            return false;
        if (getClass() != o.getClass())
            return false;
        IJKCoordinateTransformer other = (IJKCoordinateTransformer)o;
        return operatorEQImpl(getNativeObject(), other.getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD ErrorCodeIfIJKPositionOutOfRange int (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private int ErrorCodeIfIJKPositionOutOfRangeImpl(long native_object, ByteBuffer ijkPosition, long ijkPosition_byteoffset);
    public int errorCodeIfIJKPositionOutOfRange(DoubleVector3 ijkPosition) {
        return ErrorCodeIfIJKPositionOutOfRangeImpl(getNativeObject(), ManagedBase.requireNonNull(ijkPosition, "ijkPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(ijkPosition, "ijkPosition may not be null").getByteBufferOffset());
    }

    ///AUTOGEN-OK: CXX_METHOD ErrorCodeIfVoxelPositionOutOfRange int (const OpenVDS::Vector<double, 3> &) const FUNCTIONPROTO
    native private int ErrorCodeIfVoxelPositionOutOfRangeImpl(long native_object, ByteBuffer voxelPosition, long voxelPosition_byteoffset);
    public int errorCodeIfVoxelPositionOutOfRange(DoubleVector3 voxelPosition) {
        return ErrorCodeIfVoxelPositionOutOfRangeImpl(getNativeObject(), ManagedBase.requireNonNull(voxelPosition, "voxelPosition may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(voxelPosition, "voxelPosition may not be null").getByteBufferOffset());
    }

    IJKCoordinateTransformer(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject, boolean isDisposing);

    @Override
    protected void onDisposing(long native_object, boolean isDisposing) {
        dtorImpl(native_object, isDisposing);
    }

    static IJKCoordinateTransformer fromNativeObject(long nativeobject) {
        return new IJKCoordinateTransformer(nativeobject);
    }




}
