
/*
 * Copyright 2021 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.opengroup.openvds;
import java.nio.*;

// THIS FILE WAS AUTOGENERATED BY 'make-vector-classes.py' DO NOT EDIT!

public class IJKGridDefinition extends ByteBufferBackedObject {

    public IJKGridDefinition() {
        this.createByteBuffer(Double.BYTES * 3 * 4);
    }

    public DoubleVector3 getOrigin() {
        return new DoubleVector3(this.getBackingByteBuffer(), this.getByteBufferOffset() + Double.BYTES * 3 * 0);
    }


    public DoubleVector3 getIUnitStep() {
        return new DoubleVector3(this.getBackingByteBuffer(), this.getByteBufferOffset() + Double.BYTES * 3 * 1);
    }


    public DoubleVector3 getJUnitStep() {
        return new DoubleVector3(this.getBackingByteBuffer(), this.getByteBufferOffset() + Double.BYTES * 3 * 2);
    }


    public DoubleVector3 getKUnitStep() {
        return new DoubleVector3(this.getBackingByteBuffer(), this.getByteBufferOffset() + Double.BYTES * 3 * 3);
    }

    public void setOrigin(DoubleVector3 value) {
          this.getOrigin().put(this.getByteBufferProxy(), this.getByteBufferOffset() + Double.BYTES * 3 * 0);
    }


    public void setIUnitStep(DoubleVector3 value) {
          this.getIUnitStep().put(this.getByteBufferProxy(), this.getByteBufferOffset() + Double.BYTES * 3 * 1);
    }


    public void setJUnitStep(DoubleVector3 value) {
          this.getJUnitStep().put(this.getByteBufferProxy(), this.getByteBufferOffset() + Double.BYTES * 3 * 2);
    }


    public void setKUnitStep(DoubleVector3 value) {
          this.getKUnitStep().put(this.getByteBufferProxy(), this.getByteBufferOffset() + Double.BYTES * 3 * 3);
    }

    public String toString() {
        String value = "(";
        for (int i = 0; i < 3; ++i)
        {
            if (i > 0)
                value = value + ", ";
            value = value + "Origin(" + this.getOrigin().toString() + ")";
            value = value + "IUnitStep(" + this.getIUnitStep().toString() + ")";
            value = value + "JUnitStep(" + this.getJUnitStep().toString() + ")";
            value = value + "KUnitStep(" + this.getKUnitStep().toString() + ")";
        }
        value = value + ")";
        return value;
    }

    public boolean equals(Object other) {
        if (other == this) return true;
        if (other == null) return false;
        if (getClass() != other.getClass()) return false;
        IJKGridDefinition real_other = (IJKGridDefinition)other;
        return (this.getOrigin().equals(real_other.getOrigin()) &&
                this.getIUnitStep().equals(real_other.getIUnitStep()) &&
                this.getJUnitStep().equals(real_other.getJUnitStep()) &&
                this.getKUnitStep().equals(real_other.getKUnitStep()));
    }

    public static final int BYTES = Double.BYTES * 3 * 4;
}

