//=============================================================================
// <copyright>
// Copyright (c) 2021 Bluware Inc. All rights reserved.
//
// All rights are reserved. Reproduction or transmission in whole or in part,
// in any form or by any means, electronic, mechanical or otherwise,
// is prohibited without the prior written permission of the copyright owner.
// </copyright>
//=============================================================================

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public class IndexRegionFloatVector3 extends ManagedBase {

    native private static long ctorImpl();
    
    public IndexRegionFloatVector3() {
    
        super(ctorImpl());
    
    }

    native private static long ctor2Impl(ByteBuffer Min, long Min_byteoffset, ByteBuffer Max, long Max_byteoffset);
    
    public IndexRegionFloatVector3(FloatVector3 Min, FloatVector3 Max) {
    
        super(ctor2Impl(Min.getBackingByteBuffer(), Min.getByteBufferOffset(), Max.getBackingByteBuffer(), Max.getByteBufferOffset()));
    
    }

    ///AUTOGEN-OK: CXX_METHOD GetMin const type-parameter-0-0 &() const FUNCTIONPROTO
    native private void GetMinImpl(long native_object, ByteBuffer result, long result_byteoffset);
    public FloatVector3 getMin() {
        FloatVector3 result = new FloatVector3();
        GetMinImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD GetMax const type-parameter-0-0 &() const FUNCTIONPROTO
    native private void GetMaxImpl(long native_object, ByteBuffer result, long result_byteoffset);
    public FloatVector3 getMax() {
        FloatVector3 result = new FloatVector3();
        GetMaxImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset());
        return result;
    }

    IndexRegionFloatVector3(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static IndexRegionFloatVector3 fromNativeObject(long nativeobject) {
        return new IndexRegionFloatVector3(nativeobject);
    }




}
