/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public class IndexRegionFloatVector4 extends ManagedBase {

    ///AUTOGEN-OK: FIELD_DECL Min type-parameter-0-0 UNEXPOSED
    native private void getMinImpl(long native_object, ByteBuffer result, long result_byteoffset);
    public FloatVector4 getMin() {
        FloatVector4 result = new FloatVector4();
        getMinImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: FIELD_DECL Max type-parameter-0-0 UNEXPOSED
    native private void getMaxImpl(long native_object, ByteBuffer result, long result_byteoffset);
    public FloatVector4 getMax() {
        FloatVector4 result = new FloatVector4();
        getMaxImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset());
        return result;
    }

    native private static long ctorImpl();
    
    public IndexRegionFloatVector4() {
    
        super(ctorImpl());
    
    }

    native private static long ctor2Impl(ByteBuffer Min, long Min_byteoffset, ByteBuffer Max, long Max_byteoffset);
    
    public IndexRegionFloatVector4(FloatVector4 Min, FloatVector4 Max) {
    
        super(ctor2Impl(ManagedBase.requireNonNull(Min, "Min may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(Min, "Min may not be null").getByteBufferOffset(), ManagedBase.requireNonNull(Max, "Max may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(Max, "Max may not be null").getByteBufferOffset()));
    
    }

    IndexRegionFloatVector4(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject, boolean isDisposing);

    @Override
    protected void onDisposing(long native_object, boolean isDisposing) {
        dtorImpl(native_object, isDisposing);
    }

    static IndexRegionFloatVector4 fromNativeObject(long nativeobject) {
        return new IndexRegionFloatVector4(nativeobject);
    }




}
