//=============================================================================
// <copyright>
// Copyright (c) 2021 Bluware Inc. All rights reserved.
//
// All rights are reserved. Reproduction or transmission in whole or in part,
// in any form or by any means, electronic, mechanical or otherwise,
// is prohibited without the prior written permission of the copyright owner.
// </copyright>
//=============================================================================

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public enum InterpolationMethod {

    /**
     * Snap to the closest sample
     */
    Nearest(0),
    /**
     * Linear interpolation
     */
    Linear(1),
    /**
     * Cubic interpolation
     */
    Cubic(2),
    /**
     * Angular interpolation (same as linear but wraps around the value range)
     */
    Angular(3),
    /**
     * Triangular interpolation used to interpolate heightmap data
     */
    Triangular(4);

    private final int value;

    InterpolationMethod(int value) {
        this.value = value;
    }

    public int value() {
        return this.value;
    }

    public static InterpolationMethod fromInt(int value) {
        if (value == 0) return Nearest;
        if (value == 1) return Linear;
        if (value == 2) return Cubic;
        if (value == 3) return Angular;
        if (value == 4) return Triangular;
        return InterpolationMethod.values()[0];
    }

}
