/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public class KnownMetadata extends ManagedBase {

    ///AUTOGEN-OK: CXX_METHOD CategorySurveyCoordinateSystem static const char *() FUNCTIONPROTO
    native private static String CategorySurveyCoordinateSystemImpl();

    /**
     * The metadata in the survey coordinate system category contains either information used to transform from an Inline/Crossline annotation system to XY (Easting, Northing) coordinates
     * or information used to transform from an I/J/K annotation system to XYZ coordinates.
     * 
     */
    public static String categorySurveyCoordinateSystem() {
        return CategorySurveyCoordinateSystemImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemOrigin static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemOriginImpl();

    /**
     * The XY position of the origin of the annotation (Inline/Crossline/Time) coordinate system.
     * 
     */
    public static MetadataKey surveyCoordinateSystemOrigin() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemOriginImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemInlineSpacing static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemInlineSpacingImpl();

    /**
     * The XY spacing between units in the Inline annotation dimension.
     * 
     */
    public static MetadataKey surveyCoordinateSystemInlineSpacing() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemInlineSpacingImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemCrosslineSpacing static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemCrosslineSpacingImpl();

    /**
     * The XY spacing between units in the Crossline annotation dimension.
     * 
     */
    public static MetadataKey surveyCoordinateSystemCrosslineSpacing() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemCrosslineSpacingImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemGridPoint0 static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemGridPoint0Impl();

    /**
     * An optional reference point in the grid, the annotation coordinates for this point are GridPoint0Inline and GridPoint0Crossline
     * 
     */
    public static MetadataKey surveyCoordinateSystemGridPoint0() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemGridPoint0Impl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemGridPoint0Inline static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemGridPoint0InlineImpl();

    /**
     * The inline annotation coordinate for the point defined by GridPoint0
     * 
     */
    public static MetadataKey surveyCoordinateSystemGridPoint0Inline() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemGridPoint0InlineImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemGridPoint0Crossline static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemGridPoint0CrosslineImpl();

    /**
     * The inline annotation coordinate for the point defined by GridPoint0
     * 
     */
    public static MetadataKey surveyCoordinateSystemGridPoint0Crossline() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemGridPoint0CrosslineImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemGridPoint1 static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemGridPoint1Impl();

    /**
     * An optional reference point in the grid, the annotation coordinates for this point are GridPoint1Inline and GridPoint1Crossline
     * 
     */
    public static MetadataKey surveyCoordinateSystemGridPoint1() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemGridPoint1Impl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemGridPoint1Inline static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemGridPoint1InlineImpl();

    /**
     * The inline annotation coordinate for the point defined by GridPoint1
     * 
     */
    public static MetadataKey surveyCoordinateSystemGridPoint1Inline() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemGridPoint1InlineImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemGridPoint1Crossline static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemGridPoint1CrosslineImpl();

    /**
     * The inline annotation coordinate for the point defined by GridPoint1
     * 
     */
    public static MetadataKey surveyCoordinateSystemGridPoint1Crossline() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemGridPoint1CrosslineImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemGridPoint2 static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemGridPoint2Impl();

    /**
     * An optional reference point in the grid, the annotation coordinates for this point are GridPoint2Inline and GridPoint2Crossline
     * 
     */
    public static MetadataKey surveyCoordinateSystemGridPoint2() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemGridPoint2Impl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemGridPoint2Inline static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemGridPoint2InlineImpl();

    /**
     * The inline annotation coordinate for the point defined by GridPoint2
     * 
     */
    public static MetadataKey surveyCoordinateSystemGridPoint2Inline() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemGridPoint2InlineImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemGridPoint2Crossline static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemGridPoint2CrosslineImpl();

    /**
     * The inline annotation coordinate for the point defined by GridPoint2
     * 
     */
    public static MetadataKey surveyCoordinateSystemGridPoint2Crossline() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemGridPoint2CrosslineImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemGridPoint3 static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemGridPoint3Impl();

    /**
     * An optional reference point in the grid, the annotation coordinates for this point are GridPoint3Inline and GridPoint3Crossline
     * 
     */
    public static MetadataKey surveyCoordinateSystemGridPoint3() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemGridPoint3Impl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemGridPoint3Inline static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemGridPoint3InlineImpl();

    /**
     * The inline annotation coordinate for the point defined by GridPoint3
     * 
     */
    public static MetadataKey surveyCoordinateSystemGridPoint3Inline() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemGridPoint3InlineImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemGridPoint3Crossline static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemGridPoint3CrosslineImpl();

    /**
     * The inline annotation coordinate for the point defined by GridPoint3
     * 
     */
    public static MetadataKey surveyCoordinateSystemGridPoint3Crossline() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemGridPoint3CrosslineImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemIJKOrigin static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemIJKOriginImpl();

    /**
     * The XYZ position of the origin of the annotation (I/J/K) coordinate system.
     * 
     */
    public static MetadataKey surveyCoordinateSystemIJKOrigin() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemIJKOriginImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemIStepVector static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemIStepVectorImpl();

    /**
     * The step vector corresponding to dimension named 'I'
     * 
     */
    public static MetadataKey surveyCoordinateSystemIStepVector() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemIStepVectorImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemJStepVector static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemJStepVectorImpl();

    /**
     * The step vector corresponding to dimension named 'J'
     * 
     */
    public static MetadataKey surveyCoordinateSystemJStepVector() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemJStepVectorImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemKStepVector static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemKStepVectorImpl();

    /**
     * The step vector corresponding to dimension named 'K'
     * 
     */
    public static MetadataKey surveyCoordinateSystemKStepVector() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemKStepVectorImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemUnit static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemUnitImpl();

    /**
     * The unit of the coordinate system
     * 
     */
    public static MetadataKey surveyCoordinateSystemUnit() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemUnitImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SurveyCoordinateSystemCRSWkt static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SurveyCoordinateSystemCRSWktImpl();

    /**
     * The well-known text representation of the coordinate reference system
     * 
     */
    public static MetadataKey surveyCoordinateSystemCRSWkt() {
        return MetadataKey.fromNativeObject(SurveyCoordinateSystemCRSWktImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD CategoryTraceCoordinates static const char *() FUNCTIONPROTO
    native private static String CategoryTraceCoordinatesImpl();

    /**
     * The metadata in the TraceCoordinates category is used for positioning of 2D seismic. It relates to the 'Trace' dimension of the VDS where the annotation coordinate is used to look up in the arrays in this category.
     * This allows using the same positions with subsetted and interpolated or decimated data.
     * 
     */
    public static String categoryTraceCoordinates() {
        return CategoryTraceCoordinatesImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD TracePositions static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long TracePositionsImpl();

    /**
     * An array of DoubleVector2 defining the position for each trace, where (0, 0) is treated as an undefined position.
     * 
     */
    public static MetadataKey tracePositions() {
        return MetadataKey.fromNativeObject(TracePositionsImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD TraceVerticalOffsets static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long TraceVerticalOffsetsImpl();

    /**
     * An array of doubles defining the offset for each trace from the vertical start position in the Time/Depth/Sample dimension of the VDS
     * 
     */
    public static MetadataKey traceVerticalOffsets() {
        return MetadataKey.fromNativeObject(TraceVerticalOffsetsImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD EnergySourcePointNumbers static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long EnergySourcePointNumbersImpl();

    /**
     * An array of scalar int32 values defining the energy source point number for each trace.
     * 
     */
    public static MetadataKey energySourcePointNumbers() {
        return MetadataKey.fromNativeObject(EnergySourcePointNumbersImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD EnsembleNumbers static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long EnsembleNumbersImpl();

    /**
     * An array of scalar int32 values defining the ensemble number for each trace.
     * 
     */
    public static MetadataKey ensembleNumbers() {
        return MetadataKey.fromNativeObject(EnsembleNumbersImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD CategoryWrittenRegion static const char *() FUNCTIONPROTO
    native private static String CategoryWrittenRegionImpl();

    /**
     * The metadata in the WrittenRegion category is used to indicate which area is written in a sparsely populated VDS.
     * The guarantee is that values outside the written area will be NoValue if UseNoValue is true, and ValueRange.Min if UseNoValue is false.
     * 
     */
    public static String categoryWrittenRegion() {
        return CategoryWrittenRegionImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD WrittenRegion static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long WrittenRegionImpl();

    /**
     * An array of scalar int32 values defining the 6D min and max (NDBox) of the written region
     * 
     */
    public static MetadataKey writtenRegion() {
        return MetadataKey.fromNativeObject(WrittenRegionImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD CategoryImportInformation static const char *() FUNCTIONPROTO
    native private static String CategoryImportInformationImpl();

    /**
     * The metadata in the ImportInformation category contains information about the initial import to VDS. That is,
     * information about the original file (file name, last modification time etc.) and when/how it
     * was imported. The intended use is e.g. to give a default file name for an export operation or
     * to inform the user about whether the VDS was imported from some particular file.
     * 
     */
    public static String categoryImportInformation() {
        return CategoryImportInformationImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD ImportInformationDisplayName static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long ImportInformationDisplayNameImpl();

    /**
     * An informative name that can be displayed to a user but is not necessarily a valid file name.
     * 
     */
    public static MetadataKey importInformationDisplayName() {
        return MetadataKey.fromNativeObject(ImportInformationDisplayNameImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD ImportInformationInputFileName static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long ImportInformationInputFileNameImpl();

    /**
     * The original input file name. In cases where the input is not a simple file this should still be a valid file name that can be used as the default for a subsequent export operation.
     * 
     */
    public static MetadataKey importInformationInputFileName() {
        return MetadataKey.fromNativeObject(ImportInformationInputFileNameImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD ImportInformationInputFileSize static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long ImportInformationInputFileSizeImpl();

    /**
     * The total size (in bytes) of the input file(s), which is an integer stored as a double because there is no 64-bit integer metadata type.
     * 
     */
    public static MetadataKey importInformationInputFileSize() {
        return MetadataKey.fromNativeObject(ImportInformationInputFileSizeImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD ImportInformationInputTimeStamp static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long ImportInformationInputTimeStampImpl();

    /**
     * The last modified time of the input in ISO8601 format.
     * 
     */
    public static MetadataKey importInformationInputTimeStamp() {
        return MetadataKey.fromNativeObject(ImportInformationInputTimeStampImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD ImportInformationImportTimeStamp static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long ImportInformationImportTimeStampImpl();

    /**
     * The time in ISO8601 format when the data was imported to VDS.
     * 
     */
    public static MetadataKey importInformationImportTimeStamp() {
        return MetadataKey.fromNativeObject(ImportInformationImportTimeStampImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD CategorySEGY static const char *() FUNCTIONPROTO
    native private static String CategorySEGYImpl();

    /**
     * The metadata in the SEGY category is intended to capture information required to re-create the original SEG-Y file. It is only present if the VDS was imported from a SEG-Y file.
     * 
     */
    public static String categorySEGY() {
        return CategorySEGYImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD SEGYTextHeader static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SEGYTextHeaderImpl();

    /**
     * The original text header of the SEG-Y file
     * 
     */
    public static MetadataKey SEGYTextHeader() {
        return MetadataKey.fromNativeObject(SEGYTextHeaderImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SEGYBinaryHeader static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SEGYBinaryHeaderImpl();

    /**
     * The original binary header of the SEG-Y file
     * 
     */
    public static MetadataKey SEGYBinaryHeader() {
        return MetadataKey.fromNativeObject(SEGYBinaryHeaderImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SEGYEndianness static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SEGYEndiannessImpl();

    /**
     * The endianness of the SEG-Y file (0=BigEndian)(1=LittleEndian)
     * 
     */
    public static MetadataKey SEGYEndianness() {
        return MetadataKey.fromNativeObject(SEGYEndiannessImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SEGYDataEndianness static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SEGYDataEndiannessImpl();

    /**
     * The endianness of the data samples in the SEG-Y file if different from the header endianness. This is a non-standard feature, but some SEG-Y files use it. (0=BigEndian)(1=LittleEndian)
     * 
     */
    public static MetadataKey SEGYDataEndianness() {
        return MetadataKey.fromNativeObject(SEGYDataEndiannessImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SEGYDataSampleFormatCode static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SEGYDataSampleFormatCodeImpl();

    /**
     * The data sample format code of the data samples imported from the SEG-Y file. (0=Unknown)(1=IBMFloat)(2=Int32)(3=Int16)(4=FixedPoint)(5=IEEEFloat)(6=IEEEDouble)(7=Int24)(8=Int8)(9=Int64)(10=UInt32)(11=UInt16)(12=UInt64)(15=UInt24)(16=UInt8)
     * 
     */
    public static MetadataKey SEGYDataSampleFormatCode() {
        return MetadataKey.fromNativeObject(SEGYDataSampleFormatCodeImpl());
    }

    ///AUTOGEN-OK: CXX_METHOD SEGYPrimaryKey static OpenVDS::MetadataKey () FUNCTIONPROTO
    native private static long SEGYPrimaryKeyImpl();

    /**
     * The primary key (i.e. sort order) of the original SEG-Y file. VDSs are expected to transpose crossline-oriented seismic to use the standard (Sample, Crossline, Inline) axis triple, so in order to export the file in the original order we need to know which dimension to loop over.
     * 
     */
    public static MetadataKey SEGYPrimaryKey() {
        return MetadataKey.fromNativeObject(SEGYPrimaryKeyImpl());
    }

    KnownMetadata(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject, boolean isDisposing);

    @Override
    protected void onDisposing(long native_object, boolean isDisposing) {
        dtorImpl(native_object, isDisposing);
    }

    static KnownMetadata fromNativeObject(long nativeobject) {
        return new KnownMetadata(nativeobject);
    }




}
