//=============================================================================
// <copyright>
// Copyright (c) 2021 Bluware Inc. All rights reserved.
//
// All rights are reserved. Reproduction or transmission in whole or in part,
// in any form or by any means, electronic, mechanical or otherwise,
// is prohibited without the prior written permission of the copyright owner.
// </copyright>
//=============================================================================

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public class KnownUnitNames extends ManagedBase {

    ///AUTOGEN-OK: CXX_METHOD Meter static const char *() FUNCTIONPROTO
    native private static String MeterImpl();

    /**
     * String representing the SI meter unit
     * 
     */
    public static String meter() {
        return MeterImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD Millisecond static const char *() FUNCTIONPROTO
    native private static String MillisecondImpl();

    /**
     * String representing the SI milliseconds unit
     * 
     */
    public static String millisecond() {
        return MillisecondImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD Foot static const char *() FUNCTIONPROTO
    native private static String FootImpl();

    /**
     * String representing the foot unit
     * 
     */
    public static String foot() {
        return FootImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD USSurveyFoot static const char *() FUNCTIONPROTO
    native private static String USSurveyFootImpl();

    /**
     * String representing the US survey foot unit
     * 
     */
    public static String USSurveyFoot() {
        return USSurveyFootImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD Second static const char *() FUNCTIONPROTO
    native private static String SecondImpl();

    /**
     * String representing the SI second unit
     * 
     */
    public static String second() {
        return SecondImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD MetersPerSecond static const char *() FUNCTIONPROTO
    native private static String MetersPerSecondImpl();

    /**
     * String representing the meters per second unit
     * 
     */
    public static String metersPerSecond() {
        return MetersPerSecondImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD FeetPerSecond static const char *() FUNCTIONPROTO
    native private static String FeetPerSecondImpl();

    /**
     * String representing the feet per second unit
     * 
     */
    public static String feetPerSecond() {
        return FeetPerSecondImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD USSurveyFeetPerSecond static const char *() FUNCTIONPROTO
    native private static String USSurveyFeetPerSecondImpl();

    /**
     * String representing the US survey feet per second unit
     * 
     */
    public static String USSurveyFeetPerSecond() {
        return USSurveyFeetPerSecondImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD Unitless static const char *() FUNCTIONPROTO
    native private static String UnitlessImpl();

    /**
     * String representing unitless
     * 
     */
    public static String unitless() {
        return UnitlessImpl();
    }

    KnownUnitNames(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static KnownUnitNames fromNativeObject(long nativeobject) {
        return new KnownUnitNames(nativeobject);
    }




}
