/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public class KnownUnitNames extends ManagedBase {

    ///AUTOGEN-OK: CXX_METHOD Meter static const char *() FUNCTIONPROTO
    native private static String MeterImpl();

    /**
     * String representing the SI meter unit
     * 
     */
    public static String meter() {
        return MeterImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD Millisecond static const char *() FUNCTIONPROTO
    native private static String MillisecondImpl();

    /**
     * String representing the SI milliseconds unit
     * 
     */
    public static String millisecond() {
        return MillisecondImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD Foot static const char *() FUNCTIONPROTO
    native private static String FootImpl();

    /**
     * String representing the foot unit
     * 
     */
    public static String foot() {
        return FootImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD USSurveyFoot static const char *() FUNCTIONPROTO
    native private static String USSurveyFootImpl();

    /**
     * String representing the US survey foot unit
     * 
     */
    public static String USSurveyFoot() {
        return USSurveyFootImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD Second static const char *() FUNCTIONPROTO
    native private static String SecondImpl();

    /**
     * String representing the SI second unit
     * 
     */
    public static String second() {
        return SecondImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD MetersPerSecond static const char *() FUNCTIONPROTO
    native private static String MetersPerSecondImpl();

    /**
     * String representing the meters per second unit
     * 
     */
    public static String metersPerSecond() {
        return MetersPerSecondImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD FeetPerSecond static const char *() FUNCTIONPROTO
    native private static String FeetPerSecondImpl();

    /**
     * String representing the feet per second unit
     * 
     */
    public static String feetPerSecond() {
        return FeetPerSecondImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD USSurveyFeetPerSecond static const char *() FUNCTIONPROTO
    native private static String USSurveyFeetPerSecondImpl();

    /**
     * String representing the US survey feet per second unit
     * 
     */
    public static String USSurveyFeetPerSecond() {
        return USSurveyFeetPerSecondImpl();
    }

    ///AUTOGEN-OK: CXX_METHOD Unitless static const char *() FUNCTIONPROTO
    native private static String UnitlessImpl();

    /**
     * String representing unitless
     * 
     */
    public static String unitless() {
        return UnitlessImpl();
    }

    KnownUnitNames(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject, boolean isDisposing);

    @Override
    protected void onDisposing(long native_object, boolean isDisposing) {
        dtorImpl(native_object, isDisposing);
    }

    static KnownUnitNames fromNativeObject(long nativeobject) {
        if (nativeobject == 0) {
           return null;
        }
        return new KnownUnitNames(nativeobject);
    }




}
