//=============================================================================
// <copyright>
// Copyright (c) 2021 Bluware Inc. All rights reserved.
//
// All rights are reserved. Reproduction or transmission in whole or in part,
// in any form or by any means, electronic, mechanical or otherwise,
// is prohibited without the prior written permission of the copyright owner.
// </copyright>
//=============================================================================

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;

/**
 * A metadata key uniquely identifies a metadata item
 * 
 */
public class MetadataKey extends ManagedBase {

    native private static long ctorImpl();
    
    /**
     * Default constructor
     * 
     */
    public MetadataKey() {
    
        super(ctorImpl());
    
    }

    native private static long ctor2Impl(long type, String category, String name);
    
    /**
     * Constructor
     * 
     * @param type The type of the metadata that this key identifies. The possible types are (Int, Float, Double, {Int,Float,Double}Vector{2,3,4}, String or BLOB).
     * @param category The category of the metadata that this key identifies. A category is a collection of related metadata items, e.g. SurveyCoordinateSystem consists of Origin, InlineSpacing, CrosslineSpacing and Unit metadata.
     * @param name The name of the metadata that this key identifies
     */
    public MetadataKey(MetadataType type, String category, String name) {
    
        super(ctor2Impl(type.value(), category, name));
    
    }

    ///AUTOGEN-OK: CXX_METHOD GetType OpenVDS::MetadataType () const FUNCTIONPROTO
    native private long GetTypeImpl(long native_object);

    /**
     * Get the type of metadata that this key identifies
     * 
     * @return The type of the metadata that this key identifies
     */
    public MetadataType getType() {
        return MetadataType.fromInt((int)GetTypeImpl(getNativeObject()));
    }

    ///AUTOGEN-OK: CXX_METHOD GetCategory const char *() const FUNCTIONPROTO
    native private String GetCategoryImpl(long native_object);

    /**
     * Get the category of metadata that this key identifies
     * 
     * @return The category of the metadata that this key identifies
     */
    public String getCategory() {
        return GetCategoryImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetName const char *() const FUNCTIONPROTO
    native private String GetNameImpl(long native_object);

    /**
     * Get the name of metadata that this key identifies
     * 
     * @return The name of the metadata that this key identifies
     */
    public String getName() {
        return GetNameImpl(getNativeObject());
    }

    native private boolean operatorEQImpl(long nativeobject, long othernativeobject);
    
    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null)
            return false;
        if (getClass() != o.getClass())
            return false;
        MetadataKey other = (MetadataKey)o;
        return operatorEQImpl(getNativeObject(), other.getNativeObject());
    }

    MetadataKey(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static MetadataKey fromNativeObject(long nativeobject) {
        return new MetadataKey(nativeobject);
    }




}
