/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;

/**
 * Interface for read access to Metadata
 * 
 */
public class MetadataReadAccess extends ManagedBase {

    ///AUTOGEN-OK: CXX_METHOD IsMetadataIntAvailable bool (const char *, const char *) const FUNCTIONPROTO
    native private boolean IsMetadataIntAvailableImpl(long native_object, String category, String name);

    /**
     * Returns true if a metadata int with the given category and name is available
     * 
     */
    public boolean isMetadataIntAvailable(String category, String name) {
        return IsMetadataIntAvailableImpl(getNativeObject(), category, name);
    }

    ///AUTOGEN-OK: CXX_METHOD IsMetadataIntVector2Available bool (const char *, const char *) const FUNCTIONPROTO
    native private boolean IsMetadataIntVector2AvailableImpl(long native_object, String category, String name);

    /**
     * Returns true if a metadata IntVector2 with the given category and name is available
     * 
     */
    public boolean isMetadataIntVector2Available(String category, String name) {
        return IsMetadataIntVector2AvailableImpl(getNativeObject(), category, name);
    }

    ///AUTOGEN-OK: CXX_METHOD IsMetadataIntVector3Available bool (const char *, const char *) const FUNCTIONPROTO
    native private boolean IsMetadataIntVector3AvailableImpl(long native_object, String category, String name);

    /**
     * Returns true if a metadata IntVector3 with the given category and name is available
     * 
     */
    public boolean isMetadataIntVector3Available(String category, String name) {
        return IsMetadataIntVector3AvailableImpl(getNativeObject(), category, name);
    }

    ///AUTOGEN-OK: CXX_METHOD IsMetadataIntVector4Available bool (const char *, const char *) const FUNCTIONPROTO
    native private boolean IsMetadataIntVector4AvailableImpl(long native_object, String category, String name);

    /**
     * Returns true if a metadata IntVector4 with the given category and name is available
     * 
     */
    public boolean isMetadataIntVector4Available(String category, String name) {
        return IsMetadataIntVector4AvailableImpl(getNativeObject(), category, name);
    }

    ///AUTOGEN-OK: CXX_METHOD IsMetadataFloatAvailable bool (const char *, const char *) const FUNCTIONPROTO
    native private boolean IsMetadataFloatAvailableImpl(long native_object, String category, String name);

    /**
     * Returns true if a metadata float with the given category and name is available
     * 
     */
    public boolean isMetadataFloatAvailable(String category, String name) {
        return IsMetadataFloatAvailableImpl(getNativeObject(), category, name);
    }

    ///AUTOGEN-OK: CXX_METHOD IsMetadataFloatVector2Available bool (const char *, const char *) const FUNCTIONPROTO
    native private boolean IsMetadataFloatVector2AvailableImpl(long native_object, String category, String name);

    /**
     * Returns true if a metadata FloatVector2 with the given category and name is available
     * 
     */
    public boolean isMetadataFloatVector2Available(String category, String name) {
        return IsMetadataFloatVector2AvailableImpl(getNativeObject(), category, name);
    }

    ///AUTOGEN-OK: CXX_METHOD IsMetadataFloatVector3Available bool (const char *, const char *) const FUNCTIONPROTO
    native private boolean IsMetadataFloatVector3AvailableImpl(long native_object, String category, String name);

    /**
     * Returns true if a metadata FloatVector3 with the given category and name is available
     * 
     */
    public boolean isMetadataFloatVector3Available(String category, String name) {
        return IsMetadataFloatVector3AvailableImpl(getNativeObject(), category, name);
    }

    ///AUTOGEN-OK: CXX_METHOD IsMetadataFloatVector4Available bool (const char *, const char *) const FUNCTIONPROTO
    native private boolean IsMetadataFloatVector4AvailableImpl(long native_object, String category, String name);

    /**
     * Returns true if a metadata FloatVector4 with the given category and name is available
     * 
     */
    public boolean isMetadataFloatVector4Available(String category, String name) {
        return IsMetadataFloatVector4AvailableImpl(getNativeObject(), category, name);
    }

    ///AUTOGEN-OK: CXX_METHOD IsMetadataDoubleAvailable bool (const char *, const char *) const FUNCTIONPROTO
    native private boolean IsMetadataDoubleAvailableImpl(long native_object, String category, String name);

    /**
     * Returns true if a metadata double with the given category and name is available
     * 
     */
    public boolean isMetadataDoubleAvailable(String category, String name) {
        return IsMetadataDoubleAvailableImpl(getNativeObject(), category, name);
    }

    ///AUTOGEN-OK: CXX_METHOD IsMetadataDoubleVector2Available bool (const char *, const char *) const FUNCTIONPROTO
    native private boolean IsMetadataDoubleVector2AvailableImpl(long native_object, String category, String name);

    /**
     * Returns true if a metadata DoubleVector2 with the given category and name is available
     * 
     */
    public boolean isMetadataDoubleVector2Available(String category, String name) {
        return IsMetadataDoubleVector2AvailableImpl(getNativeObject(), category, name);
    }

    ///AUTOGEN-OK: CXX_METHOD IsMetadataDoubleVector3Available bool (const char *, const char *) const FUNCTIONPROTO
    native private boolean IsMetadataDoubleVector3AvailableImpl(long native_object, String category, String name);

    /**
     * Returns true if a metadata DoubleVector3 with the given category and name is available
     * 
     */
    public boolean isMetadataDoubleVector3Available(String category, String name) {
        return IsMetadataDoubleVector3AvailableImpl(getNativeObject(), category, name);
    }

    ///AUTOGEN-OK: CXX_METHOD IsMetadataDoubleVector4Available bool (const char *, const char *) const FUNCTIONPROTO
    native private boolean IsMetadataDoubleVector4AvailableImpl(long native_object, String category, String name);

    /**
     * Returns true if a metadata DoubleVector4 with the given category and name is available
     * 
     */
    public boolean isMetadataDoubleVector4Available(String category, String name) {
        return IsMetadataDoubleVector4AvailableImpl(getNativeObject(), category, name);
    }

    ///AUTOGEN-OK: CXX_METHOD IsMetadataStringAvailable bool (const char *, const char *) const FUNCTIONPROTO
    native private boolean IsMetadataStringAvailableImpl(long native_object, String category, String name);

    /**
     * Returns true if a metadata string with the given category and name is available
     * 
     */
    public boolean isMetadataStringAvailable(String category, String name) {
        return IsMetadataStringAvailableImpl(getNativeObject(), category, name);
    }

    ///AUTOGEN-OK: CXX_METHOD IsMetadataBLOBAvailable bool (const char *, const char *) const FUNCTIONPROTO
    native private boolean IsMetadataBLOBAvailableImpl(long native_object, String category, String name);

    /**
     * Returns true if a metadata BLOB with the given category and name is available
     * 
     */
    public boolean isMetadataBLOBAvailable(String category, String name) {
        return IsMetadataBLOBAvailableImpl(getNativeObject(), category, name);
    }

    ///AUTOGEN-OK: CXX_METHOD GetMetadataInt int (const char *, const char *) const FUNCTIONPROTO
    native private int GetMetadataIntImpl(long native_object, String category, String name);

    /**
     * Returns the metadata int with the given category and name
     * 
     */
    public int getMetadataInt(String category, String name) {
        return GetMetadataIntImpl(getNativeObject(), category, name);
    }

    ///AUTOGEN-OK: CXX_METHOD GetMetadataIntVector2 OpenVDS::Vector<int, 2> (const char *, const char *) const FUNCTIONPROTO
    native private void GetMetadataIntVector2Impl(long native_object, ByteBuffer result, long result_byteoffset, String category, String name);

    /**
     * Returns the metadata IntVector2 with the given category and name
     * 
     */
    public IntVector2 getMetadataIntVector2(String category, String name) {
        IntVector2 result = new IntVector2();
        GetMetadataIntVector2Impl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), category, name);
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD GetMetadataIntVector3 OpenVDS::Vector<int, 3> (const char *, const char *) const FUNCTIONPROTO
    native private void GetMetadataIntVector3Impl(long native_object, ByteBuffer result, long result_byteoffset, String category, String name);

    /**
     * Returns the metadata IntVector3 with the given category and name
     * 
     */
    public IntVector3 getMetadataIntVector3(String category, String name) {
        IntVector3 result = new IntVector3();
        GetMetadataIntVector3Impl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), category, name);
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD GetMetadataIntVector4 OpenVDS::Vector<int, 4> (const char *, const char *) const FUNCTIONPROTO
    native private void GetMetadataIntVector4Impl(long native_object, ByteBuffer result, long result_byteoffset, String category, String name);

    /**
     * Returns the metadata IntVector4 with the given category and name
     * 
     */
    public IntVector4 getMetadataIntVector4(String category, String name) {
        IntVector4 result = new IntVector4();
        GetMetadataIntVector4Impl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), category, name);
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD GetMetadataFloat float (const char *, const char *) const FUNCTIONPROTO
    native private float GetMetadataFloatImpl(long native_object, String category, String name);

    /**
     * Returns the metadata float with the given category and name
     * 
     */
    public float getMetadataFloat(String category, String name) {
        return GetMetadataFloatImpl(getNativeObject(), category, name);
    }

    ///AUTOGEN-OK: CXX_METHOD GetMetadataFloatVector2 OpenVDS::Vector<float, 2> (const char *, const char *) const FUNCTIONPROTO
    native private void GetMetadataFloatVector2Impl(long native_object, ByteBuffer result, long result_byteoffset, String category, String name);

    /**
     * Returns the metadata FloatVector2 with the given category and name
     * 
     */
    public FloatVector2 getMetadataFloatVector2(String category, String name) {
        FloatVector2 result = new FloatVector2();
        GetMetadataFloatVector2Impl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), category, name);
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD GetMetadataFloatVector3 OpenVDS::Vector<float, 3> (const char *, const char *) const FUNCTIONPROTO
    native private void GetMetadataFloatVector3Impl(long native_object, ByteBuffer result, long result_byteoffset, String category, String name);

    /**
     * Returns the metadata FloatVector3 with the given category and name
     * 
     */
    public FloatVector3 getMetadataFloatVector3(String category, String name) {
        FloatVector3 result = new FloatVector3();
        GetMetadataFloatVector3Impl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), category, name);
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD GetMetadataFloatVector4 OpenVDS::Vector<float, 4> (const char *, const char *) const FUNCTIONPROTO
    native private void GetMetadataFloatVector4Impl(long native_object, ByteBuffer result, long result_byteoffset, String category, String name);

    /**
     * Returns the metadata FloatVector4 with the given category and name
     * 
     */
    public FloatVector4 getMetadataFloatVector4(String category, String name) {
        FloatVector4 result = new FloatVector4();
        GetMetadataFloatVector4Impl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), category, name);
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD GetMetadataDouble double (const char *, const char *) const FUNCTIONPROTO
    native private double GetMetadataDoubleImpl(long native_object, String category, String name);

    /**
     * Returns the metadata double with the given category and name
     * 
     */
    public double getMetadataDouble(String category, String name) {
        return GetMetadataDoubleImpl(getNativeObject(), category, name);
    }

    ///AUTOGEN-OK: CXX_METHOD GetMetadataDoubleVector2 OpenVDS::Vector<double, 2> (const char *, const char *) const FUNCTIONPROTO
    native private void GetMetadataDoubleVector2Impl(long native_object, ByteBuffer result, long result_byteoffset, String category, String name);

    /**
     * Returns the metadata DoubleVector2 with the given category and name
     * 
     */
    public DoubleVector2 getMetadataDoubleVector2(String category, String name) {
        DoubleVector2 result = new DoubleVector2();
        GetMetadataDoubleVector2Impl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), category, name);
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD GetMetadataDoubleVector3 OpenVDS::Vector<double, 3> (const char *, const char *) const FUNCTIONPROTO
    native private void GetMetadataDoubleVector3Impl(long native_object, ByteBuffer result, long result_byteoffset, String category, String name);

    /**
     * Returns the metadata DoubleVector3 with the given category and name
     * 
     */
    public DoubleVector3 getMetadataDoubleVector3(String category, String name) {
        DoubleVector3 result = new DoubleVector3();
        GetMetadataDoubleVector3Impl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), category, name);
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD GetMetadataDoubleVector4 OpenVDS::Vector<double, 4> (const char *, const char *) const FUNCTIONPROTO
    native private void GetMetadataDoubleVector4Impl(long native_object, ByteBuffer result, long result_byteoffset, String category, String name);

    /**
     * Returns the metadata DoubleVector4 with the given category and name
     * 
     */
    public DoubleVector4 getMetadataDoubleVector4(String category, String name) {
        DoubleVector4 result = new DoubleVector4();
        GetMetadataDoubleVector4Impl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset(), category, name);
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD GetMetadataString const char *(const char *, const char *) const FUNCTIONPROTO
    native private String GetMetadataStringImpl(long native_object, String category, String name);

    /**
     * Returns the metadata string with the given category and name
     * 
     */
    public String getMetadataString(String category, String name) {
        return GetMetadataStringImpl(getNativeObject(), category, name);
    }

    MetadataReadAccess(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject, boolean isDisposing);

    @Override
    protected void onDisposing(long native_object, boolean isDisposing) {
        dtorImpl(native_object, isDisposing);
    }

    static MetadataReadAccess fromNativeObject(long nativeobject) {
        return new MetadataReadAccess(nativeobject);
    }




    native int[] GetMetadataKeyTypesImpl(long native_object);
    native String[] GetMetadataKeyCategoriesImpl(long native_object);
    native String[] GetMetadataKeyNamesImpl(long native_object);

    /**
     * Get metadata keys.
     * 
     * @return The metadata keys
     */
    public MetadataKey[] getMetadataKeys () {
        int[] metadataKeyTypes = GetMetadataKeyTypesImpl(getNativeObject());
        String[] metadataKeyCategories = GetMetadataKeyCategoriesImpl(getNativeObject());
        String[] metadataKeyNames = GetMetadataKeyNamesImpl(getNativeObject());

        int nMetadataKey = metadataKeyTypes.length;
        MetadataKey[] metadataKeys = new MetadataKey[nMetadataKey];

        for (int iMetadataKey = 0; iMetadataKey < nMetadataKey; iMetadataKey++) {
            metadataKeys[iMetadataKey] = new MetadataKey(MetadataType.fromInt(metadataKeyTypes[iMetadataKey]), metadataKeyCategories[iMetadataKey], metadataKeyNames[iMetadataKey]);
        }

        return metadataKeys;
    }
	
	private static native byte[] GetMetadataBLOBImpl(long native_handle, String category, String name);
	
	public byte[] getMetadataBLOB(String category, String name) {
		return GetMetadataBLOBImpl(getNativeObject(), category, name);
	}
	
}
