
/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.opengroup.openvds;
import java.nio.*;

// THIS FILE WAS AUTOGENERATED BY 'make-vector-classes.py' DO NOT EDIT!

public class NDPos extends ByteBufferBackedObject {

    public NDPos() {
        this.createByteBuffer(Float.BYTES * 6 * 1);
    }

    public NDPos(float pos0, float pos1, float pos2, float pos3, float pos4, float pos5) {
        this.createByteBuffer(Float.BYTES * 6);
        this.set(pos0, pos1, pos2, pos3, pos4, pos5);
    }

    public NDPos(java.nio.ByteBuffer bytebuffer, int byteoffset) {
        super(bytebuffer, byteoffset, Float.BYTES * 6);
    }

    public NDPos(NDPos rhs) {
        this.createByteBuffer(Float.BYTES * 6);
        this.set(rhs.getPos0(), rhs.getPos1(), rhs.getPos2(), rhs.getPos3(), rhs.getPos4(), rhs.getPos5());
    }

    public boolean equals(Object other) {
        if (other == this) return true;
        if (other == null) return false;
        if (getClass() != other.getClass()) return false;
        NDPos real_other = (NDPos)other;
        return (this.getPos0() == real_other.getPos0() &&
                this.getPos1() == real_other.getPos1() &&
                this.getPos2() == real_other.getPos2() &&
                this.getPos3() == real_other.getPos3() &&
                this.getPos4() == real_other.getPos4() &&
                this.getPos5() == real_other.getPos5());
    }

    void put(ByteBufferProxy bytebufferproxy, int byteoffset) {
        bytebufferproxy.putFloat(0 * Float.BYTES + byteoffset, this.getPos0());
        bytebufferproxy.putFloat(1 * Float.BYTES + byteoffset, this.getPos1());
        bytebufferproxy.putFloat(2 * Float.BYTES + byteoffset, this.getPos2());
        bytebufferproxy.putFloat(3 * Float.BYTES + byteoffset, this.getPos3());
        bytebufferproxy.putFloat(4 * Float.BYTES + byteoffset, this.getPos4());
        bytebufferproxy.putFloat(5 * Float.BYTES + byteoffset, this.getPos5());
    }

    public void set(float pos0, float pos1, float pos2, float pos3, float pos4, float pos5) {
        this.getByteBufferProxy().putFloat(0 * Float.BYTES, pos0);
        this.getByteBufferProxy().putFloat(1 * Float.BYTES, pos1);
        this.getByteBufferProxy().putFloat(2 * Float.BYTES, pos2);
        this.getByteBufferProxy().putFloat(3 * Float.BYTES, pos3);
        this.getByteBufferProxy().putFloat(4 * Float.BYTES, pos4);
        this.getByteBufferProxy().putFloat(5 * Float.BYTES, pos5);
    }

    public void setPos0(float value) {
        this.getByteBufferProxy().putFloat(0 * Float.BYTES, value);
    }


    public void setPos1(float value) {
        this.getByteBufferProxy().putFloat(1 * Float.BYTES, value);
    }


    public void setPos2(float value) {
        this.getByteBufferProxy().putFloat(2 * Float.BYTES, value);
    }


    public void setPos3(float value) {
        this.getByteBufferProxy().putFloat(3 * Float.BYTES, value);
    }


    public void setPos4(float value) {
        this.getByteBufferProxy().putFloat(4 * Float.BYTES, value);
    }


    public void setPos5(float value) {
        this.getByteBufferProxy().putFloat(5 * Float.BYTES, value);
    }

    public float getPos0() {
        return this.getByteBufferProxy().getFloat(0 * Float.BYTES);
    }


    public float getPos1() {
        return this.getByteBufferProxy().getFloat(1 * Float.BYTES);
    }


    public float getPos2() {
        return this.getByteBufferProxy().getFloat(2 * Float.BYTES);
    }


    public float getPos3() {
        return this.getByteBufferProxy().getFloat(3 * Float.BYTES);
    }


    public float getPos4() {
        return this.getByteBufferProxy().getFloat(4 * Float.BYTES);
    }


    public float getPos5() {
        return this.getByteBufferProxy().getFloat(5 * Float.BYTES);
    }

    public String toString() {
        String value = "(";
        for (int i = 0; i < 6; ++i)
        {
            if (i > 0)
                value = value + ", ";
            value = value + this.getByteBufferProxy().getFloat(i * Float.BYTES);
        }
        value = value + ")";
        return value;
    }

    public float[] toArray() {
        return new float[]{ getPos0(), getPos1(), getPos2(), getPos3(), getPos4(), getPos5() };
    }

    public static final int BYTES = Float.BYTES * 6 * 1;
}

