//=============================================================================
// <copyright>
// Copyright (c) 2021 Bluware Inc. All rights reserved.
//
// All rights are reserved. Reproduction or transmission in whole or in part,
// in any form or by any means, electronic, mechanical or otherwise,
// is prohibited without the prior written permission of the copyright owner.
// </copyright>
//=============================================================================

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public class OpenOptions extends ManagedBase {
    
    public enum ConnectionType {
    
            AWS(0),
            Azure(1),
            AzureSdkForCpp(2),
            AzurePresigned(3),
            GoogleStorage(4),
            DMS(5),
            Http(6),
            VDSFile(7),
            InMemory(8),
            Other(9),
            ConnectionTypeCount(10);
    
        private final int value;
    
        ConnectionType(int value) {
            this.value = value;
        }
    
        public int value() {
            return this.value;
        }
    
        public static ConnectionType fromInt(int value) {
            if (value == 0) return AWS;
            if (value == 1) return Azure;
            if (value == 2) return AzureSdkForCpp;
            if (value == 3) return AzurePresigned;
            if (value == 4) return GoogleStorage;
            if (value == 5) return DMS;
            if (value == 6) return Http;
            if (value == 7) return VDSFile;
            if (value == 8) return InMemory;
            if (value == 9) return Other;
            if (value == 10) return ConnectionTypeCount;
            return ConnectionType.values()[0];
        }
    
    }

    OpenOptions(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static OpenOptions fromNativeObject(long nativeobject) {
        return new OpenOptions(nativeobject);
    }




}
