/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;

/**
 * Describes a channel of a VDS
 * 
 */
public class VolumeDataChannelDescriptor extends ManagedBase {
    
    public enum Flags {
    
            Default(0),
        /**
         * This channel contains discrete data
         */
        DiscreteData(1),
        /**
         * Do not allow lossy compression on this channel
         */
        NoLossyCompression(2),
        /**
         * This channel is not renderable
         */
        NotRenderable(4),
        /**
         * Use Zip when compressing this channel
         */
        NoLossyCompressionUseZip(10);
    
        private final int value;
    
        Flags(int value) {
            this.value = value;
        }
    
        public int value() {
            return this.value;
        }
    
        public static Flags fromInt(int value) {
            if (value == 0) return Default;
            if (value == 1) return DiscreteData;
            if (value == 2) return NoLossyCompression;
            if (value == 4) return NotRenderable;
            if (value == 10) return NoLossyCompressionUseZip;
            return Flags.values()[0];
        }
    
    }
    
    public enum Format {
    
        /**
         * The DataBlock can be in any format
         */
        Format_Any(-1),
        /**
         * data is in packed 1-bit format
         */
        Format_1Bit(0),
        /**
         * data is in unsigned 8 bit
         */
        Format_U8(1),
        /**
         * data is in unsigned 16 bit
         */
        Format_U16(2),
        /**
         * data is in 32 bit float
         */
        Format_R32(3),
        /**
         * data is in unsigned 32 bit
         */
        Format_U32(4),
        /**
         * data is in 64 bit double
         */
        Format_R64(5),
        /**
         * data is in unsigned 64 bit
         */
        Format_U64(6);
    
        private final int value;
    
        Format(int value) {
            this.value = value;
        }
    
        public int value() {
            return this.value;
        }
    
        public static Format fromInt(int value) {
            if (value == -1) return Format_Any;
            if (value == 0) return Format_1Bit;
            if (value == 1) return Format_U8;
            if (value == 2) return Format_U16;
            if (value == 3) return Format_R32;
            if (value == 4) return Format_U32;
            if (value == 5) return Format_R64;
            if (value == 6) return Format_U64;
            return Format.values()[0];
        }
    
    }
    
    public enum Components {
    
            Components_1(1),
            Components_2(2),
            Components_4(4);
    
        private final int value;
    
        Components(int value) {
            this.value = value;
        }
    
        public int value() {
            return this.value;
        }
    
        public static Components fromInt(int value) {
            if (value == 1) return Components_1;
            if (value == 2) return Components_2;
            if (value == 4) return Components_4;
            return Components.values()[0];
        }
    
    }

    native private static long ctorImpl();
    
    public VolumeDataChannelDescriptor() {
    
        super(ctorImpl());
    
    }

    native private static long ctor2Impl(long format, long components, String name, String unit, float valueRangeMin, float valueRangeMax);
    
    public VolumeDataChannelDescriptor(VolumeDataChannelDescriptor.Format format, VolumeDataChannelDescriptor.Components components, String name, String unit, float valueRangeMin, float valueRangeMax) {
    
        super(ctor2Impl(ManagedBase.requireNonNull(format, "format may not be null").value(), ManagedBase.requireNonNull(components, "components may not be null").value(), ManagedBase.requireNonNull(name, "name may not be null"), ManagedBase.requireNonNull(unit, "unit may not be null"), valueRangeMin, valueRangeMax));
    
    }

    native private static long ctor3Impl(long format, long components, String name, String unit, float valueRangeMin, float valueRangeMax, long mapping);
    
    /**
     * @param format the data format for this channel
     * @param components the vector count for this channel
     * @param name the name of this channel
     * @param unit the unit of this channel
     * @param valueRangeMin the value range minimum of this channel
     * @param valueRangeMax the value range maximum of this channel
     * @param mapping the mapping for this channel
     */
    public VolumeDataChannelDescriptor(VolumeDataChannelDescriptor.Format format, VolumeDataChannelDescriptor.Components components, String name, String unit, float valueRangeMin, float valueRangeMax, VolumeDataMapping mapping) {
    
        super(ctor3Impl(ManagedBase.requireNonNull(format, "format may not be null").value(), ManagedBase.requireNonNull(components, "components may not be null").value(), ManagedBase.requireNonNull(name, "name may not be null"), ManagedBase.requireNonNull(unit, "unit may not be null"), valueRangeMin, valueRangeMax, ManagedBase.requireNonNull(mapping, "mapping may not be null").value()));
    
    }

    native private static long ctor4Impl(long format, long components, String name, String unit, float valueRangeMin, float valueRangeMax, long flags);
    
    /**
     * @param format the data format for this channel
     * @param components the vector count for this channel
     * @param name the name of this channel
     * @param unit the unit of this channel
     * @param valueRangeMin the value range minimum of this channel
     * @param valueRangeMax the value range maximum of this channel
     * @param flags the flags for this channel
     */
    public VolumeDataChannelDescriptor(VolumeDataChannelDescriptor.Format format, VolumeDataChannelDescriptor.Components components, String name, String unit, float valueRangeMin, float valueRangeMax, VolumeDataChannelDescriptor.Flags flags) {
    
        super(ctor4Impl(ManagedBase.requireNonNull(format, "format may not be null").value(), ManagedBase.requireNonNull(components, "components may not be null").value(), ManagedBase.requireNonNull(name, "name may not be null"), ManagedBase.requireNonNull(unit, "unit may not be null"), valueRangeMin, valueRangeMax, ManagedBase.requireNonNull(flags, "flags may not be null").value()));
    
    }

    native private static long ctor5Impl(long format, long components, String name, String unit, float valueRangeMin, float valueRangeMax, long mapping, long flags);
    
    /**
     * @param format the data format for this channel
     * @param components the vector count for this channel
     * @param name the name of this channel
     * @param unit the unit of this channel
     * @param valueRangeMin the value range minimum of this channel
     * @param valueRangeMax the value range maximum of this channel
     * @param mapping the mapping for this channel
     * @param flags the flags for this channel
     */
    public VolumeDataChannelDescriptor(VolumeDataChannelDescriptor.Format format, VolumeDataChannelDescriptor.Components components, String name, String unit, float valueRangeMin, float valueRangeMax, VolumeDataMapping mapping, VolumeDataChannelDescriptor.Flags flags) {
    
        super(ctor5Impl(ManagedBase.requireNonNull(format, "format may not be null").value(), ManagedBase.requireNonNull(components, "components may not be null").value(), ManagedBase.requireNonNull(name, "name may not be null"), ManagedBase.requireNonNull(unit, "unit may not be null"), valueRangeMin, valueRangeMax, ManagedBase.requireNonNull(mapping, "mapping may not be null").value(), ManagedBase.requireNonNull(flags, "flags may not be null").value()));
    
    }

    native private static long ctor6Impl(long format, long components, String name, String unit, float valueRangeMin, float valueRangeMax, long mapping, int mappedValueCount, long flags, float integerScale, float integerOffset);
    
    /**
     * @param format the data format for this channel
     * @param components the vector count for this channel
     * @param name the name of this channel
     * @param unit the unit of this channel
     * @param valueRangeMin the value range minimum of this channel
     * @param valueRangeMax the value range maximum of this channel
     * @param mapping the mapping for this channel
     * @param mappedValueCount When using per trace mapping, the number of values to store per trace
     * @param flags the flags for this channel
     * @param integerScale the scale to use for integer types
     * @param integerOffset the offset to use for integer types
     */
    public VolumeDataChannelDescriptor(VolumeDataChannelDescriptor.Format format, VolumeDataChannelDescriptor.Components components, String name, String unit, float valueRangeMin, float valueRangeMax, VolumeDataMapping mapping, int mappedValueCount, VolumeDataChannelDescriptor.Flags flags, float integerScale, float integerOffset) {
    
        super(ctor6Impl(ManagedBase.requireNonNull(format, "format may not be null").value(), ManagedBase.requireNonNull(components, "components may not be null").value(), ManagedBase.requireNonNull(name, "name may not be null"), ManagedBase.requireNonNull(unit, "unit may not be null"), valueRangeMin, valueRangeMax, ManagedBase.requireNonNull(mapping, "mapping may not be null").value(), mappedValueCount, ManagedBase.requireNonNull(flags, "flags may not be null").value(), integerScale, integerOffset));
    
    }

    native private static long ctor7Impl(long format, long components, String name, String unit, float valueRangeMin, float valueRangeMax, float noValue);
    
    /**
     * @param format the data format for this channel
     * @param components the vector count for this channel
     * @param name the name of this channel
     * @param unit the unit of this channel
     * @param valueRangeMin the value range minimum of this channel
     * @param valueRangeMax the value range maximum of this channel
     * @param noValue the No Value for this channel
     */
    public VolumeDataChannelDescriptor(VolumeDataChannelDescriptor.Format format, VolumeDataChannelDescriptor.Components components, String name, String unit, float valueRangeMin, float valueRangeMax, float noValue) {
    
        super(ctor7Impl(ManagedBase.requireNonNull(format, "format may not be null").value(), ManagedBase.requireNonNull(components, "components may not be null").value(), ManagedBase.requireNonNull(name, "name may not be null"), ManagedBase.requireNonNull(unit, "unit may not be null"), valueRangeMin, valueRangeMax, noValue));
    
    }

    native private static long ctor8Impl(long format, long components, String name, String unit, float valueRangeMin, float valueRangeMax, float noValue, long mapping, long flags);
    
    /**
     * @param format the data format for this channel
     * @param components the vector count for this channel
     * @param name the name of this channel
     * @param unit the unit of this channel
     * @param valueRangeMin the value range minimum of this channel
     * @param valueRangeMax the value range maximum of this channel
     * @param noValue the No Value for this channel
     * @param mapping the mapping for this channel
     * @param flags the flags for this channel
     */
    public VolumeDataChannelDescriptor(VolumeDataChannelDescriptor.Format format, VolumeDataChannelDescriptor.Components components, String name, String unit, float valueRangeMin, float valueRangeMax, float noValue, VolumeDataMapping mapping, VolumeDataChannelDescriptor.Flags flags) {
    
        super(ctor8Impl(ManagedBase.requireNonNull(format, "format may not be null").value(), ManagedBase.requireNonNull(components, "components may not be null").value(), ManagedBase.requireNonNull(name, "name may not be null"), ManagedBase.requireNonNull(unit, "unit may not be null"), valueRangeMin, valueRangeMax, noValue, ManagedBase.requireNonNull(mapping, "mapping may not be null").value(), ManagedBase.requireNonNull(flags, "flags may not be null").value()));
    
    }

    native private static long ctor9Impl(long format, long components, String name, String unit, float valueRangeMin, float valueRangeMax, long mapping, int mappedValueCount, long flags, float noValue, float integerScale, float integerOffset);
    
    /**
     * @param format the data format for this channel
     * @param components the vector count for this channel
     * @param name the name of this channel
     * @param unit the unit of this channel
     * @param valueRangeMin the value range minimum of this channel
     * @param valueRangeMax the value range maximum of this channel
     * @param mapping the mapping for this channel
     * @param mappedValueCount When using per trace mapping, the number of values to store per trace
     * @param flags the flags for this channel
     * @param noValue the No Value for this channel
     * @param integerScale the scale to use for integer types
     * @param integerOffset the offset to use for integer types
     */
    public VolumeDataChannelDescriptor(VolumeDataChannelDescriptor.Format format, VolumeDataChannelDescriptor.Components components, String name, String unit, float valueRangeMin, float valueRangeMax, VolumeDataMapping mapping, int mappedValueCount, VolumeDataChannelDescriptor.Flags flags, float noValue, float integerScale, float integerOffset) {
    
        super(ctor9Impl(ManagedBase.requireNonNull(format, "format may not be null").value(), ManagedBase.requireNonNull(components, "components may not be null").value(), ManagedBase.requireNonNull(name, "name may not be null"), ManagedBase.requireNonNull(unit, "unit may not be null"), valueRangeMin, valueRangeMax, ManagedBase.requireNonNull(mapping, "mapping may not be null").value(), mappedValueCount, ManagedBase.requireNonNull(flags, "flags may not be null").value(), noValue, integerScale, integerOffset));
    
    }

    ///AUTOGEN-OK: CXX_METHOD GetFormat OpenVDS::VolumeDataChannelDescriptor::Format () const FUNCTIONPROTO
    native private long GetFormatImpl(long native_object);
    public VolumeDataChannelDescriptor.Format getFormat() {
        return VolumeDataChannelDescriptor.Format.fromInt((int)GetFormatImpl(getNativeObject()));
    }

    ///AUTOGEN-OK: CXX_METHOD GetComponents OpenVDS::VolumeDataChannelDescriptor::Components () const FUNCTIONPROTO
    native private long GetComponentsImpl(long native_object);
    public VolumeDataChannelDescriptor.Components getComponents() {
        return VolumeDataChannelDescriptor.Components.fromInt((int)GetComponentsImpl(getNativeObject()));
    }

    ///AUTOGEN-OK: CXX_METHOD IsDiscrete bool () const FUNCTIONPROTO
    native private boolean IsDiscreteImpl(long native_object);
    public boolean isDiscrete() {
        return IsDiscreteImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD IsRenderable bool () const FUNCTIONPROTO
    native private boolean IsRenderableImpl(long native_object);
    public boolean isRenderable() {
        return IsRenderableImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD IsAllowLossyCompression bool () const FUNCTIONPROTO
    native private boolean IsAllowLossyCompressionImpl(long native_object);
    public boolean isAllowLossyCompression() {
        return IsAllowLossyCompressionImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD IsUseZipForLosslessCompression bool () const FUNCTIONPROTO
    native private boolean IsUseZipForLosslessCompressionImpl(long native_object);
    public boolean isUseZipForLosslessCompression() {
        return IsUseZipForLosslessCompressionImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetName const char *() const FUNCTIONPROTO
    native private String GetNameImpl(long native_object);
    public String getName() {
        return GetNameImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetUnit const char *() const FUNCTIONPROTO
    native private String GetUnitImpl(long native_object);
    public String getUnit() {
        return GetUnitImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetValueRange const OpenVDS::Range<float> &() const FUNCTIONPROTO
    native private void GetValueRangeImpl(long native_object, ByteBuffer result, long result_byteoffset);
    public FloatRange getValueRange() {
        FloatRange result = new FloatRange();
        GetValueRangeImpl(getNativeObject(), result.getBackingByteBuffer(), result.getByteBufferOffset());
        return result;
    }

    ///AUTOGEN-OK: CXX_METHOD GetValueRangeMin float () const FUNCTIONPROTO
    native private float GetValueRangeMinImpl(long native_object);
    public float getValueRangeMin() {
        return GetValueRangeMinImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetValueRangeMax float () const FUNCTIONPROTO
    native private float GetValueRangeMaxImpl(long native_object);
    public float getValueRangeMax() {
        return GetValueRangeMaxImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetMapping OpenVDS::VolumeDataMapping () const FUNCTIONPROTO
    native private long GetMappingImpl(long native_object);
    public VolumeDataMapping getMapping() {
        return VolumeDataMapping.fromInt((long)GetMappingImpl(getNativeObject()));
    }

    ///AUTOGEN-OK: CXX_METHOD GetMappedValueCount int () const FUNCTIONPROTO
    native private int GetMappedValueCountImpl(long native_object);
    public int getMappedValueCount() {
        return GetMappedValueCountImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD IsUseNoValue bool () const FUNCTIONPROTO
    native private boolean IsUseNoValueImpl(long native_object);
    public boolean isUseNoValue() {
        return IsUseNoValueImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetNoValue float () const FUNCTIONPROTO
    native private float GetNoValueImpl(long native_object);
    public float getNoValue() {
        return GetNoValueImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetIntegerScale float () const FUNCTIONPROTO
    native private float GetIntegerScaleImpl(long native_object);
    public float getIntegerScale() {
        return GetIntegerScaleImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetIntegerOffset float () const FUNCTIONPROTO
    native private float GetIntegerOffsetImpl(long native_object);
    public float getIntegerOffset() {
        return GetIntegerOffsetImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD TraceMappedVolumeDataChannelDescriptor static OpenVDS::VolumeDataChannelDescriptor (OpenVDS::VolumeDataChannelDescriptor::Format, OpenVDS::VolumeDataChannelDescriptor::Components, const char *, const char *, float, float, int, OpenVDS::VolumeDataChannelDescriptor::Flags) FUNCTIONPROTO
    native private static long TraceMappedVolumeDataChannelDescriptorImpl(long format, long components, String name, String unit, float valueRangeMin, float valueRangeMax, int mappedValueCount, long flags);
    public static VolumeDataChannelDescriptor traceMappedVolumeDataChannelDescriptor(VolumeDataChannelDescriptor.Format format, VolumeDataChannelDescriptor.Components components, String name, String unit, float valueRangeMin, float valueRangeMax, int mappedValueCount, VolumeDataChannelDescriptor.Flags flags) {
        return VolumeDataChannelDescriptor.fromNativeObject(TraceMappedVolumeDataChannelDescriptorImpl(ManagedBase.requireNonNull(format, "format may not be null").value(), ManagedBase.requireNonNull(components, "components may not be null").value(), ManagedBase.requireNonNull(name, "name may not be null"), ManagedBase.requireNonNull(unit, "unit may not be null"), valueRangeMin, valueRangeMax, mappedValueCount, ManagedBase.requireNonNull(flags, "flags may not be null").value()));
    }

    ///AUTOGEN-OK: CXX_METHOD TraceMappedVolumeDataChannelDescriptor static OpenVDS::VolumeDataChannelDescriptor (OpenVDS::VolumeDataChannelDescriptor::Format, OpenVDS::VolumeDataChannelDescriptor::Components, const char *, const char *, float, float, int, OpenVDS::VolumeDataChannelDescriptor::Flags, float) FUNCTIONPROTO
    native private static long TraceMappedVolumeDataChannelDescriptor2Impl(long format, long components, String name, String unit, float valueRangeMin, float valueRangeMax, int mappedValueCount, long flags, float noValue);
    public static VolumeDataChannelDescriptor traceMappedVolumeDataChannelDescriptor(VolumeDataChannelDescriptor.Format format, VolumeDataChannelDescriptor.Components components, String name, String unit, float valueRangeMin, float valueRangeMax, int mappedValueCount, VolumeDataChannelDescriptor.Flags flags, float noValue) {
        return VolumeDataChannelDescriptor.fromNativeObject(TraceMappedVolumeDataChannelDescriptor2Impl(ManagedBase.requireNonNull(format, "format may not be null").value(), ManagedBase.requireNonNull(components, "components may not be null").value(), ManagedBase.requireNonNull(name, "name may not be null"), ManagedBase.requireNonNull(unit, "unit may not be null"), valueRangeMin, valueRangeMax, mappedValueCount, ManagedBase.requireNonNull(flags, "flags may not be null").value(), noValue));
    }

    VolumeDataChannelDescriptor(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject, boolean isDisposing);

    @Override
    protected void onDisposing(long native_object, boolean isDisposing) {
        dtorImpl(native_object, isDisposing);
    }

    static VolumeDataChannelDescriptor fromNativeObject(long nativeobject) {
        if (nativeobject == 0) {
           return null;
        }
        return new VolumeDataChannelDescriptor(nativeobject);
    }




}
