//=============================================================================
// <copyright>
// Copyright (c) 2021 Bluware Inc. All rights reserved.
//
// All rights are reserved. Reproduction or transmission in whole or in part,
// in any form or by any means, electronic, mechanical or otherwise,
// is prohibited without the prior written permission of the copyright owner.
// </copyright>
//=============================================================================

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public class VolumeDataRequest extends ManagedBase {

    native private static long ctorImpl();
    
    public VolumeDataRequest() {
    
        super(ctorImpl());
    
    }

    ///AUTOGEN-OK: CXX_METHOD ValidateRequest void () FUNCTIONPROTO
    native private void ValidateRequestImpl(long native_object);

    /**
     * Check if the request object is valid. Throws an InvalidOperation exception if the request object is not valid.
     * 
     */
    public void validateRequest() {
        ValidateRequestImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD RequestID int64_t () const FUNCTIONPROTO
    native private long RequestIDImpl(long native_object);

    /**
     * Get the ID of the request.
     * 
     * @return The ID of the request.
     */
    public long requestID() {
        return RequestIDImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD IsCompleted bool () FUNCTIONPROTO
    native private boolean IsCompletedImpl(long native_object);

    /**
     * Check if the request completed successfully. If the request completed, the buffer now contains valid data.
     * 
     * @return The request is active until either IsCompleted, IsCanceled or WaitForCompletion returns true.
     */
    public boolean isCompleted() {
        return IsCompletedImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD IsCanceled bool () FUNCTIONPROTO
    native private boolean IsCanceledImpl(long native_object);

    /**
     * Check if the request was canceled (e.g. the VDS was invalidated before the request was processed). If the request was canceled, the buffer does not contain valid data.
     * 
     * @return The request is active until either IsCompleted, IsCanceled or WaitForCompletion returns true.
     */
    public boolean isCanceled() {
        return IsCanceledImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD WaitForCompletion bool (int) FUNCTIONPROTO
    native private boolean WaitForCompletionImpl(long native_object, int millisecondsBeforeTimeout);

    /**
     * Wait for the VolumeDataRequest to complete successfully. If the request completed, the buffer now contains valid data.
     * 
     * @param millisecondsBeforeTimeout The number of milliseconds to wait before timing out (optional). A value of 0 indicates there is no timeout and we will wait for
however long it takes. Note that the request is not automatically canceled if the wait times out, you can also use this mechanism
to e.g. update a progress bar while waiting. If you want to cancel the request you have to explicitly call CancelRequest() and
then wait for the request to stop writing to the buffer.
     * @return The request is active until either IsCompleted, IsCanceled or WaitForCompletion returns true.
Whenever WaitForCompletion returns false you need to call IsCanceled() to know if that was because of a timeout or if the request was canceled.
     */
    public boolean waitForCompletion(int millisecondsBeforeTimeout) {
        return WaitForCompletionImpl(getNativeObject(), millisecondsBeforeTimeout);
    }

    ///AUTOGEN-OK: CXX_METHOD Cancel void () FUNCTIONPROTO
    native private void CancelImpl(long native_object);

    /**
     * Try to cancel the request. You still have to call WaitForCompletion/IsCanceled to make sure the buffer is not being written to and to take the job out of the system.
     * It is possible that the request has completed concurrently with the call to Cancel in which case WaitForCompletion will return true.
     * 
     */
    public void cancel() {
        CancelImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD CancelAndWaitForCompletion void () FUNCTIONPROTO
    native private void CancelAndWaitForCompletionImpl(long native_object);

    /**
     * Cancel the request and wait for it to complete. This call will block until the request has completed so you can be sure the buffer is not being written to and the job is taken out of the system.
     * 
     */
    public void cancelAndWaitForCompletion() {
        CancelAndWaitForCompletionImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetCompletionFactor float () FUNCTIONPROTO
    native private float GetCompletionFactorImpl(long native_object);

    /**
     * Get the completion factor (between 0 and 1) of the request.
     * 
     * @return A factor (between 0 and 1) indicating how much of the request has been completed.
     */
    public float getCompletionFactor() {
        return GetCompletionFactorImpl(getNativeObject());
    }

    ///AUTOGEN-FAIL: CXX_METHOD Buffer void *() const FUNCTIONPROTO

    ///AUTOGEN-OK: CXX_METHOD BufferByteSize int64_t () const FUNCTIONPROTO
    native private long BufferByteSizeImpl(long native_object);

    /**
     * Get the size of the buffer the request is writing to.
     * 
     * @return The size of the buffer the request is writing to.
     */
    public long bufferByteSize() {
        return BufferByteSizeImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD BufferDataType OpenVDS::VolumeDataChannelDescriptor::Format () const FUNCTIONPROTO
    native private long BufferDataTypeImpl(long native_object);

    /**
     * Get the volume data format of the buffer the request is writing to.
     * 
     * @return The volume data format of the buffer the request is writing to.
     */
    public VolumeDataChannelDescriptor.Format bufferDataType() {
        return VolumeDataChannelDescriptor.Format.fromInt((int)BufferDataTypeImpl(getNativeObject()));
    }

    VolumeDataRequest(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static VolumeDataRequest fromNativeObject(long nativeobject) {
        return new VolumeDataRequest(nativeobject);
    }




}
