/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public class VolumeDataPage extends ManagedBase {

    ///AUTOGEN-OK: CXX_METHOD GetVolumeDataPageAccessor OpenVDS::VolumeDataPageAccessor &() const FUNCTIONPROTO
    native private long GetVolumeDataPageAccessorImpl(long native_object);
    public VolumeDataPageAccessor getVolumeDataPageAccessor() {
        return VolumeDataPageAccessor.fromNativeObject(GetVolumeDataPageAccessorImpl(getNativeObject()));
    }

    ///AUTOGEN-OK: CXX_METHOD GetMinMax void (int (&)[6], int (&)[6]) const FUNCTIONPROTO
    native private void GetMinMaxImpl(long native_object, int[] min, int[] max);
    public void getMinMax(int[] min, int[] max) {
        if (min.length != 6) throw new IllegalArgumentException("Array \"min\" must have length 6");
        if (max.length != 6) throw new IllegalArgumentException("Array \"max\" must have length 6");
        GetMinMaxImpl(getNativeObject(), min, max);
    }

    ///AUTOGEN-OK: CXX_METHOD GetMinMaxExcludingMargin void (int (&)[6], int (&)[6]) const FUNCTIONPROTO
    native private void GetMinMaxExcludingMarginImpl(long native_object, int[] minExcludingMargin, int[] maxExcludingMargin);
    public void getMinMaxExcludingMargin(int[] minExcludingMargin, int[] maxExcludingMargin) {
        if (minExcludingMargin.length != 6) throw new IllegalArgumentException("Array \"minExcludingMargin\" must have length 6");
        if (maxExcludingMargin.length != 6) throw new IllegalArgumentException("Array \"maxExcludingMargin\" must have length 6");
        GetMinMaxExcludingMarginImpl(getNativeObject(), minExcludingMargin, maxExcludingMargin);
    }

    ///AUTOGEN-FAIL: CXX_METHOD GetBuffer const void *(int (&)[6]) FUNCTIONPROTO

    ///AUTOGEN-FAIL: CXX_METHOD GetWritableBuffer void *(int (&)[6]) FUNCTIONPROTO

    ///AUTOGEN-OK: CXX_METHOD UpdateWrittenRegion void (int const (&)[6], int const (&)[6]) FUNCTIONPROTO
    native private void UpdateWrittenRegionImpl(long native_object, int[] writtenMin, int[] writtenMax);
    public void updateWrittenRegion(int[] writtenMin, int[] writtenMax) {
        if (writtenMin.length != 6) throw new IllegalArgumentException("Array \"writtenMin\" must have length 6");
        if (writtenMax.length != 6) throw new IllegalArgumentException("Array \"writtenMax\" must have length 6");
        UpdateWrittenRegionImpl(getNativeObject(), writtenMin, writtenMax);
    }

    ///AUTOGEN-OK: CXX_METHOD Release void () FUNCTIONPROTO
    native private void ReleaseImpl(long native_object);
    public void release() {
        ReleaseImpl(getNativeObject());
    }

    VolumeDataPage(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static VolumeDataPage fromNativeObject(long nativeobject) {
        return new VolumeDataPage(nativeobject);
    }




}
