/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;

/**
 * A class that provides random read/write access to the voxel values of a VDS
 * 
 */
public class VolumeData2DReadWriteAccessor1Bit extends VolumeData2DReadAccessor1Bit {

    ///AUTOGEN-OK: CXX_METHOD SetValue void (type-parameter-0-0, type-parameter-0-1) FUNCTIONPROTO
    native private void SetValueImpl(long native_object, ByteBuffer index, long index_byteoffset, boolean value);
    public void setValue(IntVector2 index, boolean value) {
        SetValueImpl(getNativeObject(), ManagedBase.requireNonNull(index, "index may not be null").getBackingByteBuffer(), ManagedBase.requireNonNull(index, "index may not be null").getByteBufferOffset(), value);
    }

    ///AUTOGEN-OK: CXX_METHOD Commit void () FUNCTIONPROTO
    native private void CommitImpl(long native_object);
    public void commit() {
        CommitImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD Cancel void () FUNCTIONPROTO
    native private void CancelImpl(long native_object);
    public void cancel() {
        CancelImpl(getNativeObject());
    }

    native private static long ctorImpl();
    
    public VolumeData2DReadWriteAccessor1Bit() {
    
        super(ctorImpl());
    
    }

    VolumeData2DReadWriteAccessor1Bit(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject, boolean isDisposing);

    @Override
    protected void onDisposing(long native_object, boolean isDisposing) {
        dtorImpl(native_object, isDisposing);
    }

    static VolumeData2DReadWriteAccessor1Bit fromNativeObject(long nativeobject) {
        return new VolumeData2DReadWriteAccessor1Bit(nativeobject);
    }




}
