/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public enum VolumeDataFormat {

    /**
     * Volume data can be in any format
     */
    Format_Any(-1),
    /**
     * Volume data is in packed 1-bit format
     */
    Format_1Bit(0),
    /**
     * Volume data is in unsigned 8 bit
     */
    Format_U8(1),
    /**
     * Volume data is in unsigned 16 bit
     */
    Format_U16(2),
    /**
     * Volume data is in 32 bit float
     */
    Format_R32(3),
    /**
     * Volume data is in unsigned 32 bit
     */
    Format_U32(4),
    /**
     * Volume data is in 64 bit double
     */
    Format_R64(5),
    /**
     * Volume data is in unsigned 64 bit
     */
    Format_U64(6);

    private final int value;

    VolumeDataFormat(int value) {
        this.value = value;
    }

    public int value() {
        return this.value;
    }

    public static VolumeDataFormat fromInt(int value) {
        if (value == -1) return Format_Any;
        if (value == 0) return Format_1Bit;
        if (value == 1) return Format_U8;
        if (value == 2) return Format_U16;
        if (value == 3) return Format_R32;
        if (value == 4) return Format_U32;
        if (value == 5) return Format_R64;
        if (value == 6) return Format_U64;
        return VolumeDataFormat.values()[0];
    }

}
