//=============================================================================
// <copyright>
// Copyright (c) 2021 Bluware Inc. All rights reserved.
//
// All rights are reserved. Reproduction or transmission in whole or in part,
// in any form or by any means, electronic, mechanical or otherwise,
// is prohibited without the prior written permission of the copyright owner.
// </copyright>
//=============================================================================

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public class VolumeDataRequestUShort extends VolumeDataRequest {

    ///AUTOGEN-OK: CXX_METHOD Data vector<type-parameter-0-0, allocator<type-parameter-0-0>> &() FUNCTIONPROTO
    native private short[] DataImpl(long native_object);
    public short[] data() {
        return DataImpl(getNativeObject());
    }

    VolumeDataRequestUShort(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static VolumeDataRequestUShort fromNativeObject(long nativeobject) {
        return new VolumeDataRequestUShort(nativeobject);
    }




}
