//=============================================================================
// <copyright>
// Copyright (c) 2021 Bluware Inc. All rights reserved.
//
// All rights are reserved. Reproduction or transmission in whole or in part,
// in any form or by any means, electronic, mechanical or otherwise,
// is prohibited without the prior written permission of the copyright owner.
// </copyright>
//=============================================================================

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public class VolumeDataAccessManager extends ManagedBase {

    native private static long ctorImpl();
    
    public VolumeDataAccessManager() {
    
        super(ctorImpl());
    
    }

    ///AUTOGEN-OK: CXX_METHOD GetVolumeDataLayout const OpenVDS::VolumeDataLayout *() FUNCTIONPROTO
    native private long GetVolumeDataLayoutImpl(long native_object);

    /**
     * Get the VolumeDataLayout object for a VDS.
     * 
     * @return The VolumeDataLayout object associated with the VDS or NULL if there is no valid VolumeDataLayout.
     */
    public VolumeDataLayout getVolumeDataLayout() {
        return VolumeDataLayout.fromNativeObject(GetVolumeDataLayoutImpl(getNativeObject()));
    }

    ///AUTOGEN-OK: CXX_METHOD GetVDSProduceStatus OpenVDS::VDSProduceStatus (OpenVDS::DimensionsND, int, int) const FUNCTIONPROTO
    native private int GetVDSProduceStatusImpl(long native_object, int dimensionsND, int LOD, int channel);

    /**
     * Get the produce status for the specific DimensionsND/LOD/Channel combination.
     * 
     * @param dimensionsND The dimensions group we're getting the produce status for.
     * @param LOD The LOD level we're getting the produce status for.
     * @param channel The channel index we're getting the produce status for.
     * @return The produce status for the specific DimensionsND/LOD/Channel combination.
     */
    public VDSProduceStatus getVDSProduceStatus(DimensionsND dimensionsND, int LOD, int channel) {
        return VDSProduceStatus.fromInt(GetVDSProduceStatusImpl(getNativeObject(), dimensionsND.value(), LOD, channel));
    }

    ///AUTOGEN-OK: CXX_METHOD GetVDSChunkCount int64_t (OpenVDS::DimensionsND, int, int) const FUNCTIONPROTO
    native private long GetVDSChunkCountImpl(long native_object, int dimensionsND, int LOD, int channel);

    /**
     * Get the chunk count for the specific DimensionsND/LOD/Channel combination.
     * 
     * @param dimensionsND The dimensions group we're getting the chunk count for.
     * @param LOD The LOD level we're getting the chunk count status for.
     * @param channel The channel index we're getting the chunk count status for.
     * @return The chunk count for the specific DimensionsND/LOD/Channel combination.
     */
    public long getVDSChunkCount(DimensionsND dimensionsND, int LOD, int channel) {
        return GetVDSChunkCountImpl(getNativeObject(), dimensionsND.value(), LOD, channel);
    }

    ///AUTOGEN-OK: CXX_METHOD CreateVolumeDataPageAccessor OpenVDS::VolumeDataPageAccessor *(OpenVDS::DimensionsND, int, int, int, OpenVDS::VolumeDataPageAccessor::AccessMode, int) FUNCTIONPROTO
    native private long CreateVolumeDataPageAccessorImpl(long native_object, int dimensionsND, int LOD, int channel, int maxPages, int accessMode, int chunkMetadataPageSize);

    /**
     * Create a VolumeDataPageAccessor object for the VDS.
     * 
     * @param dimensionsND The dimensions group that the volume data page accessor will access.
     * @param LOD The LOD level that the volume data page accessor will access.
     * @param channel The channel index that the volume data page accessor will access.
     * @param maxPages The maximum number of pages that the volume data page accessor will cache.
     * @param accessMode This specifies the access mode (ReadOnly/ReadWrite/Create) of the volume data page accessor.
     * @param chunkMetadataPageSize The chunk metadata page size of the layer. This controls how many chunk metadata entries are written per page, and is only used when the access mode is Create.
If this number is too low it will degrade performance, but in certain situations it can be advantageous to make this number a multiple
of the number of chunks in some of the dimensions. Do not change this from the default (1024) unless you know exactly what you are doing.
     * @return A VolumeDataPageAccessor object for the VDS.
     */
    public VolumeDataPageAccessor createVolumeDataPageAccessor(DimensionsND dimensionsND, int LOD, int channel, int maxPages, VolumeDataPageAccessor.AccessMode accessMode, int chunkMetadataPageSize) {
        return VolumeDataPageAccessor.fromNativeObject(CreateVolumeDataPageAccessorImpl(getNativeObject(), dimensionsND.value(), LOD, channel, maxPages, accessMode.value(), chunkMetadataPageSize));
    }

    ///AUTOGEN-OK: CXX_METHOD DestroyVolumeDataPageAccessor void (OpenVDS::VolumeDataPageAccessor *) FUNCTIONPROTO
    native private void DestroyVolumeDataPageAccessorImpl(long native_object, long volumeDataPageAccessor);

    /**
     * Destroy a volume data page accessor object.
     * 
     * @param volumeDataPageAccessor The VolumeDataPageAccessor object to destroy.
     */
    public void destroyVolumeDataPageAccessor(VolumeDataPageAccessor volumeDataPageAccessor) {
        DestroyVolumeDataPageAccessorImpl(getNativeObject(), volumeDataPageAccessor.getNativeObject());
    }


    ///AUTOGEN-OK: CXX_METHOD GetVolumeSubsetBufferSize int64_t (int const (&)[6], int const (&)[6], OpenVDS::VolumeDataChannelDescriptor::Format, int, int) FUNCTIONPROTO
    native private long GetVolumeSubsetBufferSizeImpl(long native_object, int[] minVoxelCoordinates, int[] maxVoxelCoordinates, int format, int LOD, int channel);

    /**
     * Compute the buffer size (in bytes) for a volume subset request.
     * 
     * @param minVoxelCoordinates The minimum voxel coordinates to request in each dimension (inclusive).
     * @param maxVoxelCoordinates The maximum voxel coordinates to request in each dimension (exclusive).
     * @param format Voxel format of the destination buffer.
     * @param LOD The LOD level the requested data is read from.
     * @param channel The channel index the requested data is read from.
     * @return The buffer size needed.
     */
    public long getVolumeSubsetBufferSize(int[] minVoxelCoordinates, int[] maxVoxelCoordinates, VolumeDataChannelDescriptor.Format format, int LOD, int channel) {
        if (minVoxelCoordinates.length != 6) throw new IllegalArgumentException("Array \"minVoxelCoordinates\" must have length 6");
        if (maxVoxelCoordinates.length != 6) throw new IllegalArgumentException("Array \"maxVoxelCoordinates\" must have length 6");
        return GetVolumeSubsetBufferSizeImpl(getNativeObject(), minVoxelCoordinates, maxVoxelCoordinates, format.value(), LOD, channel);
    }

    ///AUTOGEN-OK: CXX_METHOD RequestVolumeSubset std::shared_ptr<OpenVDS::VolumeDataRequest> (void *, int64_t, OpenVDS::DimensionsND, int, int, int const (&)[6], int const (&)[6], OpenVDS::VolumeDataChannelDescriptor::Format, OpenVDS::optional<float>) FUNCTIONPROTO
    native private long RequestVolumeSubsetImpl(long native_object, ByteBuffer buffer, int dimensionsND, int LOD, int channel, int[] minVoxelCoordinates, int[] maxVoxelCoordinates, int format, float replacementNoValue, boolean use_replacementNoValue);

    /**
     * Request a subset of the input VDS.
     * 
     * @param buffer Pointer to a preallocated buffer holding at least as many elements of format as indicated by minVoxelCoordinates and maxVoxelCoordinates.
     * @param dimensionsND The dimensiongroup the requested data is read from.
     * @param LOD The LOD level the requested data is read from.
     * @param channel The channel index the requested data is read from.
     * @param minVoxelCoordinates The minimum voxel coordinates to request in each dimension (inclusive).
     * @param maxVoxelCoordinates The maximum voxel coordinates to request in each dimension (exclusive).
     * @param format Voxel format of the destination buffer.
     * @param replacementNoValue If specified, this value is used to replace regions of the input VDS that has no data.
     * @return A VolumeDataRequest instance encapsulating the request status and buffer.
     */
    public VolumeDataRequest requestVolumeSubset(ByteBuffer buffer, DimensionsND dimensionsND, int LOD, int channel, int[] minVoxelCoordinates, int[] maxVoxelCoordinates, VolumeDataChannelDescriptor.Format format, Float replacementNoValue) {
        if (minVoxelCoordinates.length != 6) throw new IllegalArgumentException("Array \"minVoxelCoordinates\" must have length 6");
        if (maxVoxelCoordinates.length != 6) throw new IllegalArgumentException("Array \"maxVoxelCoordinates\" must have length 6");
        return VolumeDataRequest.fromNativeObject(RequestVolumeSubsetImpl(getNativeObject(), buffer, dimensionsND.value(), LOD, channel, minVoxelCoordinates, maxVoxelCoordinates, format.value(), replacementNoValue == null ? (float)0 : (float)replacementNoValue, replacementNoValue != null));
    }

    ///AUTOGEN-OK: CXX_METHOD RequestVolumeSubset1Bit std::shared_ptr<OpenVDS::VolumeDataRequest_t<unsigned char>> (unsigned char *, int64_t, OpenVDS::DimensionsND, int, int, int const (&)[6], int const (&)[6]) FUNCTIONPROTO
    native private long RequestVolumeSubset1BitImpl(long native_object, ByteBuffer buffer, int dimensionsND, int LOD, int channel, int[] minVoxelCoordinates, int[] maxVoxelCoordinates);

    /**
     * Request a subset of the input VDS.
     * 
     * @param buffer Pointer to a preallocated buffer holding at least as many elements of format as indicated by minVoxelCoordinates and maxVoxelCoordinates.
     * @param dimensionsND The dimensiongroup the requested data is read from.
     * @param LOD The LOD level the requested data is read from.
     * @param channel The channel index the requested data is read from.
     * @param minVoxelCoordinates The minimum voxel coordinates to request in each dimension (inclusive).
     * @param maxVoxelCoordinates The maximum voxel coordinates to request in each dimension (exclusive).
     * @return A VolumeDataRequest instance encapsulating the request status and buffer.
     */
    public VolumeDataRequest1Bit requestVolumeSubset1Bit(ByteBuffer buffer, DimensionsND dimensionsND, int LOD, int channel, int[] minVoxelCoordinates, int[] maxVoxelCoordinates) {
        if (minVoxelCoordinates.length != 6) throw new IllegalArgumentException("Array \"minVoxelCoordinates\" must have length 6");
        if (maxVoxelCoordinates.length != 6) throw new IllegalArgumentException("Array \"maxVoxelCoordinates\" must have length 6");
        return VolumeDataRequest1Bit.fromNativeObject(RequestVolumeSubset1BitImpl(getNativeObject(), buffer, dimensionsND.value(), LOD, channel, minVoxelCoordinates, maxVoxelCoordinates));
    }

    ///AUTOGEN-OK: CXX_METHOD RequestVolumeSubset std::shared_ptr<OpenVDS::VolumeDataRequest> (OpenVDS::DimensionsND, int, int, int const (&)[6], int const (&)[6], OpenVDS::VolumeDataChannelDescriptor::Format, OpenVDS::optional<float>) FUNCTIONPROTO
    native private long RequestVolumeSubset3Impl(long native_object, int dimensionsND, int LOD, int channel, int[] minVoxelCoordinates, int[] maxVoxelCoordinates, int format, float replacementNoValue, boolean use_replacementNoValue);

    /**
     * Request a subset of the input VDS, using an automatically allocated buffer.
     * 
     * @param dimensionsND The dimensiongroup the requested data is read from.
     * @param LOD The LOD level the requested data is read from.
     * @param channel The channel index the requested data is read from.
     * @param minVoxelCoordinates The minimum voxel coordinates to request in each dimension (inclusive).
     * @param maxVoxelCoordinates The maximum voxel coordinates to request in each dimension (exclusive).
     * @param format Voxel format of the destination buffer.
     * @param replacementNoValue If specified, this value is used to replace regions of the input VDS that has no data.
     * @return A VolumeDataRequest instance encapsulating the request status and buffer.
     */
    public VolumeDataRequest requestVolumeSubset(DimensionsND dimensionsND, int LOD, int channel, int[] minVoxelCoordinates, int[] maxVoxelCoordinates, VolumeDataChannelDescriptor.Format format, Float replacementNoValue) {
        if (minVoxelCoordinates.length != 6) throw new IllegalArgumentException("Array \"minVoxelCoordinates\" must have length 6");
        if (maxVoxelCoordinates.length != 6) throw new IllegalArgumentException("Array \"maxVoxelCoordinates\" must have length 6");
        return VolumeDataRequest.fromNativeObject(RequestVolumeSubset3Impl(getNativeObject(), dimensionsND.value(), LOD, channel, minVoxelCoordinates, maxVoxelCoordinates, format.value(), replacementNoValue == null ? (float)0 : (float)replacementNoValue, replacementNoValue != null));
    }

    ///AUTOGEN-OK: CXX_METHOD RequestVolumeSubset1Bit std::shared_ptr<OpenVDS::VolumeDataRequest_t<unsigned char>> (OpenVDS::DimensionsND, int, int, int const (&)[6], int const (&)[6]) FUNCTIONPROTO
    native private long RequestVolumeSubset1Bit2Impl(long native_object, int dimensionsND, int LOD, int channel, int[] minVoxelCoordinates, int[] maxVoxelCoordinates);

    /**
     * Request a subset of the input VDS, using an automatically allocated buffer.
     * 
     * @param dimensionsND The dimensiongroup the requested data is read from.
     * @param LOD The LOD level the requested data is read from.
     * @param channel The channel index the requested data is read from.
     * @param minVoxelCoordinates The minimum voxel coordinates to request in each dimension (inclusive).
     * @param maxVoxelCoordinates The maximum voxel coordinates to request in each dimension (exclusive).
     * @return A VolumeDataRequest instance encapsulating the request status and buffer.
     */
    public VolumeDataRequest1Bit requestVolumeSubset1Bit(DimensionsND dimensionsND, int LOD, int channel, int[] minVoxelCoordinates, int[] maxVoxelCoordinates) {
        if (minVoxelCoordinates.length != 6) throw new IllegalArgumentException("Array \"minVoxelCoordinates\" must have length 6");
        if (maxVoxelCoordinates.length != 6) throw new IllegalArgumentException("Array \"maxVoxelCoordinates\" must have length 6");
        return VolumeDataRequest1Bit.fromNativeObject(RequestVolumeSubset1Bit2Impl(getNativeObject(), dimensionsND.value(), LOD, channel, minVoxelCoordinates, maxVoxelCoordinates));
    }

    ///AUTOGEN-OK: CXX_METHOD GetProjectedVolumeSubsetBufferSize int64_t (int const (&)[6], int const (&)[6], OpenVDS::DimensionsND, OpenVDS::VolumeDataChannelDescriptor::Format, int, int) FUNCTIONPROTO
    native private long GetProjectedVolumeSubsetBufferSizeImpl(long native_object, int[] minVoxelCoordinates, int[] maxVoxelCoordinates, int projectedDimensions, int format, int LOD, int channel);

    /**
     * Compute the buffer size (in bytes) for a projected volume subset request.
     * 
     * @param minVoxelCoordinates The minimum voxel coordinates to request in each dimension (inclusive).
     * @param maxVoxelCoordinates The maximum voxel coordinates to request in each dimension (exclusive).
     * @param projectedDimensions The 2D dimension group that the plane in the source dimensiongroup is projected into. It must be a 2D subset of the source dimensions.
     * @param format Voxel format of the destination buffer.
     * @param LOD The LOD level the requested data is read from.
     * @param channel The channel index the requested data is read from.
     * @return The buffer size needed.
     */
    public long getProjectedVolumeSubsetBufferSize(int[] minVoxelCoordinates, int[] maxVoxelCoordinates, DimensionsND projectedDimensions, VolumeDataChannelDescriptor.Format format, int LOD, int channel) {
        if (minVoxelCoordinates.length != 6) throw new IllegalArgumentException("Array \"minVoxelCoordinates\" must have length 6");
        if (maxVoxelCoordinates.length != 6) throw new IllegalArgumentException("Array \"maxVoxelCoordinates\" must have length 6");
        return GetProjectedVolumeSubsetBufferSizeImpl(getNativeObject(), minVoxelCoordinates, maxVoxelCoordinates, projectedDimensions.value(), format.value(), LOD, channel);
    }

    ///AUTOGEN-OK: CXX_METHOD RequestProjectedVolumeSubset std::shared_ptr<OpenVDS::VolumeDataRequest> (void *, int64_t, OpenVDS::DimensionsND, int, int, int const (&)[6], int const (&)[6], const OpenVDS::Vector<float, 4> &, OpenVDS::DimensionsND, OpenVDS::VolumeDataChannelDescriptor::Format, OpenVDS::InterpolationMethod, OpenVDS::optional<float>) FUNCTIONPROTO
    native private long RequestProjectedVolumeSubsetImpl(long native_object, ByteBuffer buffer, int dimensionsND, int LOD, int channel, int[] minVoxelCoordinates, int[] maxVoxelCoordinates, ByteBuffer voxelPlane, long voxelPlane_byteoffset, int projectedDimensions, int format, int interpolationMethod, float replacementNoValue, boolean use_replacementNoValue);

    /**
     * Request a subset projected from an arbitrary 3D plane through the subset onto one of the sides of the subset.
     * 
     * @param buffer Pointer to a preallocated buffer holding at least as many elements of format as indicated by minVoxelCoordinates and maxVoxelCoordinates for the projected dimensions.
     * @param dimensionsND The dimensiongroup the requested data is read from.
     * @param LOD The LOD level the requested data is read from.
     * @param channel The channel index the requested data is read from.
     * @param minVoxelCoordinates The minimum voxel coordinates to request in each dimension (inclusive).
     * @param maxVoxelCoordinates The maximum voxel coordinates to request in each dimension (exclusive).
     * @param voxelPlane The plane equation for the projection from the dimension source to the projected dimensions (which must be a 2D subset of the source dimensions).
     * @param projectedDimensions The 2D dimension group that the plane in the source dimensiongroup is projected into. It must be a 2D subset of the source dimensions.
     * @param interpolationMethod Interpolation method to use when sampling the buffer.
     * @param format Voxel format of the destination buffer.
     * @param replacementNoValue If specified, this value is used to replace regions of the input VDS that has no data.
     * @return A VolumeDataRequest instance encapsulating the request status and buffer.
     */
    public VolumeDataRequest requestProjectedVolumeSubset(ByteBuffer buffer, DimensionsND dimensionsND, int LOD, int channel, int[] minVoxelCoordinates, int[] maxVoxelCoordinates, FloatVector4 voxelPlane, DimensionsND projectedDimensions, VolumeDataChannelDescriptor.Format format, InterpolationMethod interpolationMethod, Float replacementNoValue) {
        if (minVoxelCoordinates.length != 6) throw new IllegalArgumentException("Array \"minVoxelCoordinates\" must have length 6");
        if (maxVoxelCoordinates.length != 6) throw new IllegalArgumentException("Array \"maxVoxelCoordinates\" must have length 6");
        return VolumeDataRequest.fromNativeObject(RequestProjectedVolumeSubsetImpl(getNativeObject(), buffer, dimensionsND.value(), LOD, channel, minVoxelCoordinates, maxVoxelCoordinates, voxelPlane.getBackingByteBuffer(), voxelPlane.getByteBufferOffset(), projectedDimensions.value(), format.value(), interpolationMethod.value(), replacementNoValue == null ? (float)0 : (float)replacementNoValue, replacementNoValue != null));
    }

    ///AUTOGEN-OK: CXX_METHOD RequestProjectedVolumeSubset std::shared_ptr<OpenVDS::VolumeDataRequest> (OpenVDS::DimensionsND, int, int, int const (&)[6], int const (&)[6], const OpenVDS::Vector<float, 4> &, OpenVDS::DimensionsND, OpenVDS::VolumeDataChannelDescriptor::Format, OpenVDS::InterpolationMethod, OpenVDS::optional<float>) FUNCTIONPROTO
    native private long RequestProjectedVolumeSubset2Impl(long native_object, int dimensionsND, int LOD, int channel, int[] minVoxelCoordinates, int[] maxVoxelCoordinates, ByteBuffer voxelPlane, long voxelPlane_byteoffset, int projectedDimensions, int format, int interpolationMethod, float replacementNoValue, boolean use_replacementNoValue);

    /**
     * Request a subset projected from an arbitrary 3D plane through the subset onto one of the sides of the subset, using an automatically allocated buffer.
     * 
     * @param dimensionsND The dimensiongroup the requested data is read from.
     * @param LOD The LOD level the requested data is read from.
     * @param channel The channel index the requested data is read from.
     * @param minVoxelCoordinates The minimum voxel coordinates to request in each dimension (inclusive).
     * @param maxVoxelCoordinates The maximum voxel coordinates to request in each dimension (exclusive).
     * @param voxelPlane The plane equation for the projection from the dimension source to the projected dimensions (which must be a 2D subset of the source dimensions).
     * @param projectedDimensions The 2D dimension group that the plane in the source dimensiongroup is projected into. It must be a 2D subset of the source dimensions.
     * @param format Voxel format of the destination buffer.
     * @param interpolationMethod Interpolation method to use when sampling the buffer.
     * @param replacementNoValue If specified, this value is used to replace regions of the input VDS that has no data.
     * @return A VolumeDataRequest instance encapsulating the request status and buffer.
     */
    public VolumeDataRequest requestProjectedVolumeSubset(DimensionsND dimensionsND, int LOD, int channel, int[] minVoxelCoordinates, int[] maxVoxelCoordinates, FloatVector4 voxelPlane, DimensionsND projectedDimensions, VolumeDataChannelDescriptor.Format format, InterpolationMethod interpolationMethod, Float replacementNoValue) {
        if (minVoxelCoordinates.length != 6) throw new IllegalArgumentException("Array \"minVoxelCoordinates\" must have length 6");
        if (maxVoxelCoordinates.length != 6) throw new IllegalArgumentException("Array \"maxVoxelCoordinates\" must have length 6");
        return VolumeDataRequest.fromNativeObject(RequestProjectedVolumeSubset2Impl(getNativeObject(), dimensionsND.value(), LOD, channel, minVoxelCoordinates, maxVoxelCoordinates, voxelPlane.getBackingByteBuffer(), voxelPlane.getByteBufferOffset(), projectedDimensions.value(), format.value(), interpolationMethod.value(), replacementNoValue == null ? (float)0 : (float)replacementNoValue, replacementNoValue != null));
    }

    ///AUTOGEN-OK: CXX_METHOD GetVolumeSamplesBufferSize int64_t (int, int) FUNCTIONPROTO
    native private long GetVolumeSamplesBufferSizeImpl(long native_object, int sampleCount, int channel);

    /**
     * Compute the buffer size (in bytes) for a volume samples request.
     * 
     * @param sampleCount Number of samples to request.
     * @param channel The channel index the requested data is read from.
     * @return The buffer size needed.
     */
    public long getVolumeSamplesBufferSize(int sampleCount, int channel) {
        return GetVolumeSamplesBufferSizeImpl(getNativeObject(), sampleCount, channel);
    }

    ///AUTOGEN-OK: CXX_METHOD RequestVolumeSamples std::shared_ptr<OpenVDS::VolumeDataRequest_t<float>> (float *, int64_t, OpenVDS::DimensionsND, int, int, float const (*)[6], int, OpenVDS::InterpolationMethod, OpenVDS::optional<float>) FUNCTIONPROTO
    native private long RequestVolumeSamplesImpl(long native_object, ByteBuffer buffer, int dimensionsND, int LOD, int channel, float[] samplePositions, int sampleCount, int interpolationMethod, float replacementNoValue, boolean use_replacementNoValue);

    /**
     * Request sampling of the input VDS at the specified coordinates.
     * 
     * @param buffer Pointer to a preallocated buffer holding at least sampleCount elements.
     * @param dimensionsND The dimensiongroup the requested data is read from.
     * @param LOD The LOD level the requested data is read from.
     * @param channel The channel index the requested data is read from.
     * @param samplePositions Pointer to array of VolumeDataLayout::Dimensionality_Max-elements indicating the positions to sample. May be deleted once RequestVolumeSamples return, as HueSpace makes a deep copy of the data.
     * @param sampleCount Number of samples to request.
     * @param interpolationMethod Interpolation method to use when sampling the buffer.
     * @param replacementNoValue If specified, this value is used to replace regions of the input VDS that has no data.
     * @return A VolumeDataRequest instance encapsulating the request status and buffer.
     */
    public VolumeDataRequestFloat requestVolumeSamples(ByteBuffer buffer, DimensionsND dimensionsND, int LOD, int channel, float[] samplePositions, int sampleCount, InterpolationMethod interpolationMethod, Float replacementNoValue) {
        if (samplePositions.length != 6) throw new IllegalArgumentException("Array \"samplePositions\" must have length 6");
        return VolumeDataRequestFloat.fromNativeObject(RequestVolumeSamplesImpl(getNativeObject(), buffer, dimensionsND.value(), LOD, channel, samplePositions, sampleCount, interpolationMethod.value(), replacementNoValue == null ? (float)0 : (float)replacementNoValue, replacementNoValue != null));
    }

    ///AUTOGEN-OK: CXX_METHOD RequestVolumeSamples std::shared_ptr<OpenVDS::VolumeDataRequest_t<float>> (OpenVDS::DimensionsND, int, int, float const (*)[6], int, OpenVDS::InterpolationMethod, OpenVDS::optional<float>) FUNCTIONPROTO
    native private long RequestVolumeSamples2Impl(long native_object, int dimensionsND, int LOD, int channel, float[] samplePositions, int sampleCount, int interpolationMethod, float replacementNoValue, boolean use_replacementNoValue);

    /**
     * Request sampling of the input VDS at the specified coordinates, using an automatically allocated buffer.
     * 
     * @param dimensionsND The dimensiongroup the requested data is read from.
     * @param LOD The LOD level the requested data is read from.
     * @param channel The channel index the requested data is read from.
     * @param samplePositions Pointer to array of VolumeDataLayout::Dimensionality_Max-elements indicating the positions to sample. May be deleted once RequestVolumeSamples return, as HueSpace makes a deep copy of the data.
     * @param sampleCount Number of samples to request.
     * @param interpolationMethod Interpolation method to use when sampling the buffer.
     * @param replacementNoValue If specified, this value is used to replace regions of the input VDS that has no data.
     * @return A VolumeDataRequest instance encapsulating the request status and buffer.
     */
    public VolumeDataRequestFloat requestVolumeSamples(DimensionsND dimensionsND, int LOD, int channel, float[] samplePositions, int sampleCount, InterpolationMethod interpolationMethod, Float replacementNoValue) {
        if (samplePositions.length != 6) throw new IllegalArgumentException("Array \"samplePositions\" must have length 6");
        return VolumeDataRequestFloat.fromNativeObject(RequestVolumeSamples2Impl(getNativeObject(), dimensionsND.value(), LOD, channel, samplePositions, sampleCount, interpolationMethod.value(), replacementNoValue == null ? (float)0 : (float)replacementNoValue, replacementNoValue != null));
    }

    ///AUTOGEN-OK: CXX_METHOD GetVolumeTracesBufferSize int64_t (int, int, int, int) FUNCTIONPROTO
    native private long GetVolumeTracesBufferSizeImpl(long native_object, int traceCount, int traceDimension, int LOD, int channel);

    /**
     * Compute the buffer size (in bytes) for a volume traces request.
     * 
     * @param traceCount Number of traces to request.
     * @param traceDimension The dimension to trace
     * @param LOD The LOD level the requested data is read from.
     * @param channel The channel index the requested data is read from.
     * @return The buffer size needed.
     */
    public long getVolumeTracesBufferSize(int traceCount, int traceDimension, int LOD, int channel) {
        return GetVolumeTracesBufferSizeImpl(getNativeObject(), traceCount, traceDimension, LOD, channel);
    }

    ///AUTOGEN-OK: CXX_METHOD RequestVolumeTraces std::shared_ptr<OpenVDS::VolumeDataRequest_t<float>> (OpenVDS::DimensionsND, int, int, float const (*)[6], int, OpenVDS::InterpolationMethod, int, OpenVDS::optional<float>) FUNCTIONPROTO
    native private long RequestVolumeTracesImpl(long native_object, int dimensionsND, int LOD, int channel, float[] tracePositions, int traceCount, int interpolationMethod, int traceDimension, float replacementNoValue, boolean use_replacementNoValue);

    /**
     * Request traces from the input VDS, using an automatically allocated buffer.
     * 
     * @param dimensionsND The dimensiongroup the requested data is read from.
     * @param LOD The LOD level the requested data is read from.
     * @param channel The channel index the requested data is read from.
     * @param tracePositions Pointer to array of traceCount VolumeDataLayout::Dimensionality_Max-elements indicating the trace positions.
     * @param traceCount Number of traces to request.
     * @param interpolationMethod Interpolation method to use when sampling the buffer.
     * @param traceDimension The dimension to trace
     * @param replacementNoValue If specified, this value is used to replace regions of the input VDS that has no data.
     * @return A VolumeDataRequest instance encapsulating the request status and buffer.
     */
    public VolumeDataRequestFloat requestVolumeTraces(DimensionsND dimensionsND, int LOD, int channel, float[] tracePositions, int traceCount, InterpolationMethod interpolationMethod, int traceDimension, Float replacementNoValue) {
        if (tracePositions.length != 6) throw new IllegalArgumentException("Array \"tracePositions\" must have length 6");
        return VolumeDataRequestFloat.fromNativeObject(RequestVolumeTracesImpl(getNativeObject(), dimensionsND.value(), LOD, channel, tracePositions, traceCount, interpolationMethod.value(), traceDimension, replacementNoValue == null ? (float)0 : (float)replacementNoValue, replacementNoValue != null));
    }

    ///AUTOGEN-OK: CXX_METHOD RequestVolumeTraces std::shared_ptr<OpenVDS::VolumeDataRequest_t<float>> (float *, int64_t, OpenVDS::DimensionsND, int, int, float const (*)[6], int, OpenVDS::InterpolationMethod, int, OpenVDS::optional<float>) FUNCTIONPROTO
    native private long RequestVolumeTraces2Impl(long native_object, ByteBuffer buffer, int dimensionsND, int LOD, int channel, float[] tracePositions, int traceCount, int interpolationMethod, int traceDimension, float replacementNoValue, boolean use_replacementNoValue);

    /**
     * Request traces from the input VDS.
     * 
     * @param buffer Pointer to a preallocated buffer holding at least traceCount * number of samples in the traceDimension.
     * @param dimensionsND The dimensiongroup the requested data is read from.
     * @param LOD The LOD level the requested data is read from.
     * @param channel The channel index the requested data is read from.
     * @param tracePositions Pointer to array of traceCount VolumeDataLayout::Dimensionality_Max-elements indicating the trace positions.
     * @param traceCount Number of traces to request.
     * @param interpolationMethod Interpolation method to use when sampling the buffer.
     * @param traceDimension The dimension to trace
     * @param replacementNoValue If specified, this value is used to replace regions of the input VDS that has no data.
     * @return A VolumeDataRequest instance encapsulating the request status and buffer.
     */
    public VolumeDataRequestFloat requestVolumeTraces(ByteBuffer buffer, DimensionsND dimensionsND, int LOD, int channel, float[] tracePositions, int traceCount, InterpolationMethod interpolationMethod, int traceDimension, Float replacementNoValue) {
        if (tracePositions.length != 6) throw new IllegalArgumentException("Array \"tracePositions\" must have length 6");
        return VolumeDataRequestFloat.fromNativeObject(RequestVolumeTraces2Impl(getNativeObject(), buffer, dimensionsND.value(), LOD, channel, tracePositions, traceCount, interpolationMethod.value(), traceDimension, replacementNoValue == null ? (float)0 : (float)replacementNoValue, replacementNoValue != null));
    }

    ///AUTOGEN-OK: CXX_METHOD PrefetchVolumeChunk std::shared_ptr<OpenVDS::VolumeDataRequest> (OpenVDS::DimensionsND, int, int, int64_t) FUNCTIONPROTO
    native private long PrefetchVolumeChunkImpl(long native_object, int dimensionsND, int LOD, int channel, long chunkIndex);

    /**
     * Force production of a specific volume data chunk
     * 
     * @param dimensionsND The dimensiongroup the requested chunk belongs to.
     * @param LOD The LOD level the requested chunk belongs to.
     * @param channel The channel index the requested chunk belongs to.
     * @param chunkIndex The index of the chunk to prefetch.
     * @return A VolumeDataRequest instance encapsulating the request status.
     */
    public VolumeDataRequest prefetchVolumeChunk(DimensionsND dimensionsND, int LOD, int channel, long chunkIndex) {
        return VolumeDataRequest.fromNativeObject(PrefetchVolumeChunkImpl(getNativeObject(), dimensionsND.value(), LOD, channel, chunkIndex));
    }

    ///AUTOGEN-OK: CXX_METHOD FlushUploadQueue void (bool) FUNCTIONPROTO
    native private void FlushUploadQueueImpl(long native_object, boolean writeUpdatedLayerStatus);

    /**
     * Flush any pending writes and write updated layer status
     * 
     * @param writeUpdatedLayerStatus Write the updated layer status (or only flush pending writes of chunks and chunk-metadata).
     */
    public void flushUploadQueue(boolean writeUpdatedLayerStatus) {
        FlushUploadQueueImpl(getNativeObject(), writeUpdatedLayerStatus);
    }

    ///AUTOGEN-OK: CXX_METHOD ClearUploadErrors void () FUNCTIONPROTO
    native private void ClearUploadErrorsImpl(long native_object);

    /**
     * Clear all upload errors that have been retrieved
     * 
     */
    public void clearUploadErrors() {
        ClearUploadErrorsImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD ForceClearAllUploadErrors void () FUNCTIONPROTO
    native private void ForceClearAllUploadErrorsImpl(long native_object);

    /**
     * Clear all upload errors
     * 
     */
    public void forceClearAllUploadErrors() {
        ForceClearAllUploadErrorsImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD UploadErrorCount int () FUNCTIONPROTO
    native private int UploadErrorCountImpl(long native_object);

    /**
     * Get the number of unretrieved upload errors
     * 
     */
    public int uploadErrorCount() {
        return UploadErrorCountImpl(getNativeObject());
    }

    ///AUTOGEN-FAIL: CXX_METHOD GetCurrentUploadError void (const char **, int *, const char **) FUNCTIONPROTO

    ///AUTOGEN-FAIL: CXX_METHOD GetCurrentDownloadError void (int *, const char **) FUNCTIONPROTO

    VolumeDataAccessManager(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static VolumeDataAccessManager fromNativeObject(long nativeobject) {
        return new VolumeDataAccessManager(nativeobject);
    }




}
