/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public enum VolumeDataComponents {

    /**
     * Volume data is scalar
     */
    Components_1(1),
    /**
     * Volume data has 2-components
     */
    Components_2(2),
    /**
     * Volume data has 4-components
     */
    Components_4(4);

    private final int value;

    VolumeDataComponents(int value) {
        this.value = value;
    }

    public int value() {
        return this.value;
    }

    public static VolumeDataComponents fromInt(int value) {
        if (value == 1) return Components_1;
        if (value == 2) return Components_2;
        if (value == 4) return Components_4;
        return VolumeDataComponents.values()[0];
    }

}
