/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public class VolumeDataRequestDouble extends VolumeDataRequest {

    ///AUTOGEN-OK: CXX_METHOD Data vector<type-parameter-0-0, allocator<type-parameter-0-0>> &() FUNCTIONPROTO
    native private double[] DataImpl(long native_object);
    public double[] data() {
        return DataImpl(getNativeObject());
    }

    VolumeDataRequestDouble(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static VolumeDataRequestDouble fromNativeObject(long nativeobject) {
        return new VolumeDataRequestDouble(nativeobject);
    }





    /**
     * Get the buffer the request is writing to as a DoubleBuffer.
     * 
     * @return The buffer the request is writing to as a DoubleBuffer
     */
    public java.nio.DoubleBuffer getDoubleBuffer() {
        return getBuffer().asDoubleBuffer();
    }

}
