//=============================================================================
// <copyright>
// Copyright (c) 2021 Bluware Inc. All rights reserved.
//
// All rights are reserved. Reproduction or transmission in whole or in part,
// in any form or by any means, electronic, mechanical or otherwise,
// is prohibited without the prior written permission of the copyright owner.
// </copyright>
//=============================================================================

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;

/**
 * A class that provides random read/write access to the voxel values of a VDS
 * 
 */
public class VolumeData3DReadWriteAccessor1Bit extends VolumeDataReadAccessorIntVector3 {

    ///AUTOGEN-FAIL: CXX_METHOD SetValue void (type-parameter-0-0, type-parameter-0-1) FUNCTIONPROTO

    ///AUTOGEN-OK: CXX_METHOD Commit void () FUNCTIONPROTO
    native private void CommitImpl(long native_object);
    public void commit() {
        CommitImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD Cancel void () FUNCTIONPROTO
    native private void CancelImpl(long native_object);
    public void cancel() {
        CancelImpl(getNativeObject());
    }

    native private static long ctorImpl();
    
    public VolumeData3DReadWriteAccessor1Bit() {
    
        super(ctorImpl());
    
    }

    VolumeData3DReadWriteAccessor1Bit(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static VolumeData3DReadWriteAccessor1Bit fromNativeObject(long nativeobject) {
        return new VolumeData3DReadWriteAccessor1Bit(nativeobject);
    }




}
