//=============================================================================
// <copyright>
// Copyright (c) 2021 Bluware Inc. All rights reserved.
//
// All rights are reserved. Reproduction or transmission in whole or in part,
// in any form or by any means, electronic, mechanical or otherwise,
// is prohibited without the prior written permission of the copyright owner.
// </copyright>
//=============================================================================

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT!

package org.opengroup.openvds;

import org.opengroup.openvds.*;
import java.util.*;
import java.nio.ByteBuffer;


public class VolumeDataLayoutDescriptor extends ManagedBase {
    
    public enum BrickSize {
    
            BrickSize_32(5),
            BrickSize_64(6),
            BrickSize_128(7),
            BrickSize_256(8),
            BrickSize_512(9),
            BrickSize_1024(10),
            BrickSize_2048(11),
            BrickSize_4096(12);
    
        private final int value;
    
        BrickSize(int value) {
            this.value = value;
        }
    
        public int value() {
            return this.value;
        }
    
        public static BrickSize fromInt(int value) {
            if (value == 5) return BrickSize_32;
            if (value == 6) return BrickSize_64;
            if (value == 7) return BrickSize_128;
            if (value == 8) return BrickSize_256;
            if (value == 9) return BrickSize_512;
            if (value == 10) return BrickSize_1024;
            if (value == 11) return BrickSize_2048;
            if (value == 12) return BrickSize_4096;
            return BrickSize.values()[0];
        }
    
    }
    
    public enum LODLevels {
    
            LODLevels_None(0),
            LODLevels_1(1),
            LODLevels_2(2),
            LODLevels_3(3),
            LODLevels_4(4),
            LODLevels_5(5),
            LODLevels_6(6),
            LODLevels_7(7),
            LODLevels_8(8),
            LODLevels_9(9),
            LODLevels_10(10),
            LODLevels_11(11),
            LODLevels_12(12);
    
        private final int value;
    
        LODLevels(int value) {
            this.value = value;
        }
    
        public int value() {
            return this.value;
        }
    
        public static LODLevels fromInt(int value) {
            if (value == 0) return LODLevels_None;
            if (value == 1) return LODLevels_1;
            if (value == 2) return LODLevels_2;
            if (value == 3) return LODLevels_3;
            if (value == 4) return LODLevels_4;
            if (value == 5) return LODLevels_5;
            if (value == 6) return LODLevels_6;
            if (value == 7) return LODLevels_7;
            if (value == 8) return LODLevels_8;
            if (value == 9) return LODLevels_9;
            if (value == 10) return LODLevels_10;
            if (value == 11) return LODLevels_11;
            if (value == 12) return LODLevels_12;
            return LODLevels.values()[0];
        }
    
    }
    
    public enum Options {
    
            Options_None(0),
            Options_Create2DLODs(1),
            Options_ForceFullResolutionDimension(2);
    
        private final int value;
    
        Options(int value) {
            this.value = value;
        }
    
        public int value() {
            return this.value;
        }
    
        public static Options fromInt(int value) {
            if (value == 0) return Options_None;
            if (value == 1) return Options_Create2DLODs;
            if (value == 2) return Options_ForceFullResolutionDimension;
            return Options.values()[0];
        }
    
    }

    native private static long ctorImpl();
    
    public VolumeDataLayoutDescriptor() {
    
        super(ctorImpl());
    
    }

    native private static long ctor2Impl(long brickSize, int negativeMargin, int positiveMargin, int brickSize2DMultiplier, long lodLevels, long options, int fullResolutionDimension);
    
    public VolumeDataLayoutDescriptor(VolumeDataLayoutDescriptor.BrickSize brickSize, int negativeMargin, int positiveMargin, int brickSize2DMultiplier, VolumeDataLayoutDescriptor.LODLevels lodLevels, VolumeDataLayoutDescriptor.Options options, int fullResolutionDimension) {
    
        super(ctor2Impl(brickSize.value(), negativeMargin, positiveMargin, brickSize2DMultiplier, lodLevels.value(), options.value(), fullResolutionDimension));
    
    }

    ///AUTOGEN-OK: CXX_METHOD IsValid bool () const FUNCTIONPROTO
    native private boolean IsValidImpl(long native_object);
    public boolean isValid() {
        return IsValidImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetBrickSize OpenVDS::VolumeDataLayoutDescriptor::BrickSize () const FUNCTIONPROTO
    native private long GetBrickSizeImpl(long native_object);
    public VolumeDataLayoutDescriptor.BrickSize getBrickSize() {
        return VolumeDataLayoutDescriptor.BrickSize.fromInt((int)GetBrickSizeImpl(getNativeObject()));
    }

    ///AUTOGEN-OK: CXX_METHOD GetNegativeMargin int () const FUNCTIONPROTO
    native private int GetNegativeMarginImpl(long native_object);
    public int getNegativeMargin() {
        return GetNegativeMarginImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetPositiveMargin int () const FUNCTIONPROTO
    native private int GetPositiveMarginImpl(long native_object);
    public int getPositiveMargin() {
        return GetPositiveMarginImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetBrickSizeMultiplier2D int () const FUNCTIONPROTO
    native private int GetBrickSizeMultiplier2DImpl(long native_object);
    public int getBrickSizeMultiplier2D() {
        return GetBrickSizeMultiplier2DImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetLODLevels OpenVDS::VolumeDataLayoutDescriptor::LODLevels () const FUNCTIONPROTO
    native private long GetLODLevelsImpl(long native_object);
    public VolumeDataLayoutDescriptor.LODLevels getLODLevels() {
        return VolumeDataLayoutDescriptor.LODLevels.fromInt((int)GetLODLevelsImpl(getNativeObject()));
    }

    ///AUTOGEN-OK: CXX_METHOD IsCreate2DLODs bool () const FUNCTIONPROTO
    native private boolean IsCreate2DLODsImpl(long native_object);
    public boolean isCreate2DLODs() {
        return IsCreate2DLODsImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD IsForceFullResolutionDimension bool () const FUNCTIONPROTO
    native private boolean IsForceFullResolutionDimensionImpl(long native_object);
    public boolean isForceFullResolutionDimension() {
        return IsForceFullResolutionDimensionImpl(getNativeObject());
    }

    ///AUTOGEN-OK: CXX_METHOD GetFullResolutionDimension int () const FUNCTIONPROTO
    native private int GetFullResolutionDimensionImpl(long native_object);
    public int getFullResolutionDimension() {
        return GetFullResolutionDimensionImpl(getNativeObject());
    }

    VolumeDataLayoutDescriptor(long nativeobject) {
        super(nativeobject);
    }
    native private long dtorImpl(long nativeobject);

    @Override
    protected void onDisposing(long native_object) {
        dtorImpl(native_object);
    }

    static VolumeDataLayoutDescriptor fromNativeObject(long nativeobject) {
        return new VolumeDataLayoutDescriptor(nativeobject);
    }




}
