/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


// THIS FILE IS AUTOGENERATED. DO NOT EDIT!

//#pragma warning(disable : 4996) // Hide exception warning from VolumeDataAccess.h

#include "CPPJNI.h"


#include "Error.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_org_opengroup_openvds_VDSError_ctorImpl
  (JNIEnv * env, jclass cls)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto context = CPPJNI_createObjectContext<OpenVDS::VDSError>();

    auto native_handle = context->handle();
    context->setObject(CPPJNI_makeShared<OpenVDS::VDSError>());

    return native_handle;
  }
  CPPJNI_CATCH
  return 0;
}


JNIEXPORT jint JNICALL Java_org_opengroup_openvds_VDSError_getCodeImpl
  (JNIEnv * env, jobject object, jlong native_handle)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::VDSError>(native_handle);
    auto result = pInstance->code;
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_VDSError_setCodeImpl
  (JNIEnv * env, jobject object, jlong native_handle, jint value)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::VDSError>(native_handle);
    pInstance->code = value;
  }
  CPPJNI_CATCH
}


JNIEXPORT jstring JNICALL Java_org_opengroup_openvds_VDSError_getStringImpl
  (JNIEnv * env, jobject object, jlong native_handle)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::VDSError>(native_handle);
    auto result = pInstance->string;
    return CPPJNI_newString(env, result);
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_VDSError_setStringImpl
  (JNIEnv * env, jobject object, jlong native_handle, jstring value)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::VDSError>(native_handle);
    pInstance->string = std::string(CPPJNIStringWrapper(env, native_handle, value));
  }
  CPPJNI_CATCH
}


JNIEXPORT void JNICALL Java_org_opengroup_openvds_VDSError_dtorImpl
  (JNIEnv * env, jobject object, jlong native_handle, jboolean is_disposing)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    CPPJNI_destroyHandle<OpenVDS::VDSError>(native_handle, is_disposing);
  }
  CPPJNI_CATCH
}



#ifdef __cplusplus
}
#endif
