/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


// THIS FILE IS AUTOGENERATED. DO NOT EDIT!

//#pragma warning(disable : 4996) // Hide exception warning from VolumeDataAccess.h

#include "Marshaling.h"


#include "IJKCoordinateTransformer.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_ctorImpl
  (JNIEnv * env, jclass cls)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto context = new CPPJNIObjectContext_t<OpenVDS::IJKCoordinateTransformer>();

    auto native_handle = context->handle();
    context->setObject(std::make_shared<OpenVDS::IJKCoordinateTransformer>());

    return native_handle;
  }
  CPPJNI_CATCH
  return 0;
}


JNIEXPORT jlong JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_ctor2Impl
  (JNIEnv * env, jclass cls, jobject ijkGridDefinitionbytebuffer, jlong ijkGridDefinitionbyteoffset, jobject ijkSizebytebuffer, jlong ijkSizebyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto context = new CPPJNIObjectContext_t<OpenVDS::IJKCoordinateTransformer>();

    auto native_handle = context->handle();
    context->setObject(std::make_shared<OpenVDS::IJKCoordinateTransformer>(CPPJNIByteBufferAdapter<OpenVDS::IJKGridDefinition>(env, ijkGridDefinitionbytebuffer, ijkGridDefinitionbyteoffset), CPPJNIByteBufferAdapter<OpenVDS::IntVector3>(env, ijkSizebytebuffer, ijkSizebyteoffset)));

    return native_handle;
  }
  CPPJNI_CATCH
  return 0;
}


JNIEXPORT jlong JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_ctor3Impl
  (JNIEnv * env, jclass cls, jobject ijkGridDefinitionbytebuffer, jlong ijkGridDefinitionbyteoffset, jobject ijkSizebytebuffer, jlong ijkSizebyteoffset, jobject ijkToVoxelDimensionMapbytebuffer, jlong ijkToVoxelDimensionMapbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto context = new CPPJNIObjectContext_t<OpenVDS::IJKCoordinateTransformer>();

    auto native_handle = context->handle();
    context->setObject(std::make_shared<OpenVDS::IJKCoordinateTransformer>(
                               CPPJNIByteBufferAdapter<OpenVDS::IJKGridDefinition>(env, ijkGridDefinitionbytebuffer, ijkGridDefinitionbyteoffset), 
                               CPPJNIByteBufferAdapter<OpenVDS::IntVector3>(env, ijkSizebytebuffer, ijkSizebyteoffset), 
                               CPPJNIByteBufferAdapter<OpenVDS::IntVector3>(env, ijkToVoxelDimensionMapbytebuffer, ijkToVoxelDimensionMapbyteoffset)));

    return native_handle;
  }
  CPPJNI_CATCH
  return 0;
}


JNIEXPORT jlong JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_ctor4Impl
  (JNIEnv * env, jclass cls, jobject vdsIJKGridDefinitionbytebuffer, jlong vdsIJKGridDefinitionbyteoffset, jobject ijkSizebytebuffer, jlong ijkSizebyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto context = new CPPJNIObjectContext_t<OpenVDS::IJKCoordinateTransformer>();

    auto native_handle = context->handle();
    context->setObject(std::make_shared<OpenVDS::IJKCoordinateTransformer>(CPPJNIByteBufferAdapter<OpenVDS::VDSIJKGridDefinition>(env, vdsIJKGridDefinitionbytebuffer, vdsIJKGridDefinitionbyteoffset), CPPJNIByteBufferAdapter<OpenVDS::IntVector3>(env, ijkSizebytebuffer, ijkSizebyteoffset)));

    return native_handle;
  }
  CPPJNI_CATCH
  return 0;
}


JNIEXPORT jlong JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_ctor5Impl
  (JNIEnv * env, jclass cls, jobject ijkGridDefinitionbytebuffer, jlong ijkGridDefinitionbyteoffset, jobject ijkSizebytebuffer, jlong ijkSizebyteoffset, jobject ijkAnnotationStartbytebuffer, jlong ijkAnnotationStartbyteoffset, jobject ijkAnnotationEndbytebuffer, jlong ijkAnnotationEndbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto context = new CPPJNIObjectContext_t<OpenVDS::IJKCoordinateTransformer>();

    auto native_handle = context->handle();
    context->setObject(std::make_shared<OpenVDS::IJKCoordinateTransformer>(
                               CPPJNIByteBufferAdapter<OpenVDS::IJKGridDefinition>(env, ijkGridDefinitionbytebuffer, ijkGridDefinitionbyteoffset), 
                               CPPJNIByteBufferAdapter<OpenVDS::IntVector3>(env, ijkSizebytebuffer, ijkSizebyteoffset), 
                               CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, ijkAnnotationStartbytebuffer, ijkAnnotationStartbyteoffset), 
                               CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, ijkAnnotationEndbytebuffer, ijkAnnotationEndbyteoffset)));

    return native_handle;
  }
  CPPJNI_CATCH
  return 0;
}


JNIEXPORT jlong JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_ctor6Impl
  (JNIEnv * env, jclass cls, jobject ijkGridDefinitionbytebuffer, jlong ijkGridDefinitionbyteoffset, jobject ijkSizebytebuffer, jlong ijkSizebyteoffset, jobject ijkToVoxelDimensionMapbytebuffer, jlong ijkToVoxelDimensionMapbyteoffset, jobject ijkAnnotationStartbytebuffer, jlong ijkAnnotationStartbyteoffset, jobject ijkAnnotationEndbytebuffer, jlong ijkAnnotationEndbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto context = new CPPJNIObjectContext_t<OpenVDS::IJKCoordinateTransformer>();

    auto native_handle = context->handle();
    context->setObject(std::make_shared<OpenVDS::IJKCoordinateTransformer>(
                               CPPJNIByteBufferAdapter<OpenVDS::IJKGridDefinition>(env, ijkGridDefinitionbytebuffer, ijkGridDefinitionbyteoffset), 
                               CPPJNIByteBufferAdapter<OpenVDS::IntVector3>(env, ijkSizebytebuffer, ijkSizebyteoffset), 
                               CPPJNIByteBufferAdapter<OpenVDS::IntVector3>(env, ijkToVoxelDimensionMapbytebuffer, ijkToVoxelDimensionMapbyteoffset), 
                               CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, ijkAnnotationStartbytebuffer, ijkAnnotationStartbyteoffset), 
                               CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, ijkAnnotationEndbytebuffer, ijkAnnotationEndbyteoffset)));

    return native_handle;
  }
  CPPJNI_CATCH
  return 0;
}


JNIEXPORT jlong JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_ctor7Impl
  (JNIEnv * env, jclass cls, jobject vdsIJKGridDefinitionbytebuffer, jlong vdsIJKGridDefinitionbyteoffset, jobject ijkSizebytebuffer, jlong ijkSizebyteoffset, jobject ijkAnnotationStartbytebuffer, jlong ijkAnnotationStartbyteoffset, jobject ijkAnnotationEndbytebuffer, jlong ijkAnnotationEndbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto context = new CPPJNIObjectContext_t<OpenVDS::IJKCoordinateTransformer>();

    auto native_handle = context->handle();
    context->setObject(std::make_shared<OpenVDS::IJKCoordinateTransformer>(
                               CPPJNIByteBufferAdapter<OpenVDS::VDSIJKGridDefinition>(env, vdsIJKGridDefinitionbytebuffer, vdsIJKGridDefinitionbyteoffset), 
                               CPPJNIByteBufferAdapter<OpenVDS::IntVector3>(env, ijkSizebytebuffer, ijkSizebyteoffset), 
                               CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, ijkAnnotationStartbytebuffer, ijkAnnotationStartbyteoffset), 
                               CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, ijkAnnotationEndbytebuffer, ijkAnnotationEndbyteoffset)));

    return native_handle;
  }
  CPPJNI_CATCH
  return 0;
}


JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_IJKGridImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->IJKGrid();
    *(OpenVDS::IJKGridDefinition*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_IJKSizeImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->IJKSize();
    *(OpenVDS::IntVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_IJKToVoxelDimensionMapImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->IJKToVoxelDimensionMap();
    *(OpenVDS::IntVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_IJKToWorldTransformImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->IJKToWorldTransform();
    *(OpenVDS::DoubleMatrix4x4*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_WorldToIJKTransformImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->WorldToIJKTransform();
    *(OpenVDS::DoubleMatrix4x4*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_IJKAnnotationStartImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->IJKAnnotationStart();
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_IJKAnnotationEndImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->IJKAnnotationEnd();
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_AnnotationsDefinedImpl
  (JNIEnv * env, jobject object, jlong native_handle)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->AnnotationsDefined();
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_IJKPositionToWorldImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject ijkPositionbytebuffer, jlong ijkPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->IJKPositionToWorld(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, ijkPositionbytebuffer, ijkPositionbyteoffset));
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_IJKIndexToWorldImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject ijkIndexbytebuffer, jlong ijkIndexbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->IJKIndexToWorld(CPPJNIByteBufferAdapter<OpenVDS::IntVector3>(env, ijkIndexbytebuffer, ijkIndexbyteoffset));
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_IJKPositionToAnnotationImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject ijkPositionbytebuffer, jlong ijkPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->IJKPositionToAnnotation(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, ijkPositionbytebuffer, ijkPositionbyteoffset));
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_IJKIndexToAnnotationImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject ijkIndexbytebuffer, jlong ijkIndexbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->IJKIndexToAnnotation(CPPJNIByteBufferAdapter<OpenVDS::IntVector3>(env, ijkIndexbytebuffer, ijkIndexbyteoffset));
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_IJKPositionToVoxelPositionImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject ijkPositionbytebuffer, jlong ijkPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->IJKPositionToVoxelPosition(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, ijkPositionbytebuffer, ijkPositionbyteoffset));
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_IJKIndexToVoxelIndexImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject ijkIndexbytebuffer, jlong ijkIndexbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->IJKIndexToVoxelIndex(CPPJNIByteBufferAdapter<OpenVDS::IntVector3>(env, ijkIndexbytebuffer, ijkIndexbyteoffset));
    *(OpenVDS::IntVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_WorldToIJKPositionImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject worldPositionbytebuffer, jlong worldPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->WorldToIJKPosition(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, worldPositionbytebuffer, worldPositionbyteoffset));
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_WorldToIJKIndexImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject worldPositionbytebuffer, jlong worldPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->WorldToIJKIndex(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, worldPositionbytebuffer, worldPositionbyteoffset));
    *(OpenVDS::IntVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_WorldToAnnotationImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject worldPositionbytebuffer, jlong worldPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->WorldToAnnotation(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, worldPositionbytebuffer, worldPositionbyteoffset));
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_WorldToVoxelPositionImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject worldPositionbytebuffer, jlong worldPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->WorldToVoxelPosition(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, worldPositionbytebuffer, worldPositionbyteoffset));
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_WorldToVoxelIndexImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject worldPositionbytebuffer, jlong worldPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->WorldToVoxelIndex(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, worldPositionbytebuffer, worldPositionbyteoffset));
    *(OpenVDS::IntVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_AnnotationToIJKPositionImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject annotationPositionbytebuffer, jlong annotationPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->AnnotationToIJKPosition(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, annotationPositionbytebuffer, annotationPositionbyteoffset));
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_AnnotationToIJKIndexImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject annotationPositionbytebuffer, jlong annotationPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->AnnotationToIJKIndex(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, annotationPositionbytebuffer, annotationPositionbyteoffset));
    *(OpenVDS::IntVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_AnnotationToWorldImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject annotationPositionbytebuffer, jlong annotationPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->AnnotationToWorld(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, annotationPositionbytebuffer, annotationPositionbyteoffset));
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_AnnotationToVoxelPositionImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject annotationPositionbytebuffer, jlong annotationPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->AnnotationToVoxelPosition(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, annotationPositionbytebuffer, annotationPositionbyteoffset));
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_AnnotationToVoxelIndexImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject annotationPositionbytebuffer, jlong annotationPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->AnnotationToVoxelIndex(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, annotationPositionbytebuffer, annotationPositionbyteoffset));
    *(OpenVDS::IntVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_VoxelPositionToIJKPositionImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject voxelPositionbytebuffer, jlong voxelPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->VoxelPositionToIJKPosition(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, voxelPositionbytebuffer, voxelPositionbyteoffset));
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_VoxelIndexToIJKIndexImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject voxelIndexbytebuffer, jlong voxelIndexbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->VoxelIndexToIJKIndex(CPPJNIByteBufferAdapter<OpenVDS::IntVector3>(env, voxelIndexbytebuffer, voxelIndexbyteoffset));
    *(OpenVDS::IntVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_VoxelPositionToWorldImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject voxelPositionbytebuffer, jlong voxelPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->VoxelPositionToWorld(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, voxelPositionbytebuffer, voxelPositionbyteoffset));
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_VoxelIndexToWorldImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject voxelIndexbytebuffer, jlong voxelIndexbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->VoxelIndexToWorld(CPPJNIByteBufferAdapter<OpenVDS::IntVector3>(env, voxelIndexbytebuffer, voxelIndexbyteoffset));
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_VoxelPositionToAnnotationImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject voxelPositionbytebuffer, jlong voxelPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->VoxelPositionToAnnotation(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, voxelPositionbytebuffer, voxelPositionbyteoffset));
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_VoxelIndexToAnnotationImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject voxelIndexbytebuffer, jlong voxelIndexbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->VoxelIndexToAnnotation(CPPJNIByteBufferAdapter<OpenVDS::IntVector3>(env, voxelIndexbytebuffer, voxelIndexbyteoffset));
    *(OpenVDS::DoubleVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_IsIJKPositionOutOfRangeImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject ijkPositionbytebuffer, jlong ijkPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->IsIJKPositionOutOfRange(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, ijkPositionbytebuffer, ijkPositionbyteoffset));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_IsIJKIndexOutOfRangeImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject ijkIndexbytebuffer, jlong ijkIndexbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->IsIJKIndexOutOfRange(CPPJNIByteBufferAdapter<OpenVDS::IntVector3>(env, ijkIndexbytebuffer, ijkIndexbyteoffset));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_IsVoxelPositionOutOfRangeImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject voxelPositionbytebuffer, jlong voxelPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->IsVoxelPositionOutOfRange(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, voxelPositionbytebuffer, voxelPositionbyteoffset));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_IsVoxelIndexOutOfRangeImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject voxelIndexbytebuffer, jlong voxelIndexbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->IsVoxelIndexOutOfRange(CPPJNIByteBufferAdapter<OpenVDS::IntVector3>(env, voxelIndexbytebuffer, voxelIndexbyteoffset));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_ConvertIJKPositionToIndexImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject ijkPositionbytebuffer, jlong ijkPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->ConvertIJKPositionToIndex(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, ijkPositionbytebuffer, ijkPositionbyteoffset));
    *(OpenVDS::IntVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_ConvertVoxelPositionToIndexImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject resultbytebuffer, jlong resultbyteoffset, jobject voxelPositionbytebuffer, jlong voxelPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->ConvertVoxelPositionToIndex(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, voxelPositionbytebuffer, voxelPositionbyteoffset));
    *(OpenVDS::IntVector3*)((char*)env->GetDirectBufferAddress(resultbytebuffer) + resultbyteoffset) = result;
  }
  CPPJNI_CATCH
}

JNIEXPORT jboolean JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_operatorEQImpl
  (JNIEnv * env, jobject object, jlong native_handle, jlong other_native_handle)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto pOtherInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(other_native_handle);
    return *pInstance == *pOtherInstance;
  }
  CPPJNI_CATCH
  return 0;
}


JNIEXPORT jint JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_ErrorCodeIfIJKPositionOutOfRangeImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject ijkPositionbytebuffer, jlong ijkPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->ErrorCodeIfIJKPositionOutOfRange(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, ijkPositionbytebuffer, ijkPositionbyteoffset));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT jint JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_ErrorCodeIfVoxelPositionOutOfRangeImpl
  (JNIEnv * env, jobject object, jlong native_handle, jobject voxelPositionbytebuffer, jlong voxelPositionbyteoffset)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto pInstance = CPPJNI_cast<OpenVDS::IJKCoordinateTransformer>(native_handle);
    auto result = pInstance->ErrorCodeIfVoxelPositionOutOfRange(CPPJNIByteBufferAdapter<OpenVDS::DoubleVector3>(env, voxelPositionbytebuffer, voxelPositionbyteoffset));
    return result;
  }
  CPPJNI_CATCH
  return 0;
}

JNIEXPORT void JNICALL Java_org_opengroup_openvds_IJKCoordinateTransformer_dtorImpl
  (JNIEnv * env, jobject object, jlong native_handle, jboolean is_disposing)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    CPPJNI_destroyHandle<OpenVDS::IJKCoordinateTransformer>(native_handle);
  }
  CPPJNI_CATCH
}



#ifdef __cplusplus
}
#endif
