/*
 * Copyright 2022 The Open Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


// THIS FILE IS AUTOGENERATED. DO NOT EDIT!

//#pragma warning(disable : 4996) // Hide exception warning from VolumeDataAccess.h

#include "CPPJNI.h"


#include "Log.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_org_opengroup_openvds_LogHandler_ctorImpl
  (JNIEnv * env, jclass cls)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    auto context = CPPJNI_createObjectContext<OpenVDS::LogHandler>();

    auto native_handle = context->handle();
    context->setObject(CPPJNI_makeShared<OpenVDS::LogHandler>());

    return native_handle;
  }
  CPPJNI_CATCH
  return 0;
}

///AUTOGEN-FAIL: CONSTRUCTOR LogHandler void (void (*)(OpenVDS::LogLevel, const char *, uint64_t, void *), void *) FUNCTIONPROTO
///AUTOGEN-FAIL: FIELD_DECL callback void (*)(OpenVDS::LogLevel, const char *, uint64_t, void *) POINTER
///AUTOGEN-FAIL: FIELD_DECL userHandle void * POINTER

JNIEXPORT void JNICALL Java_org_opengroup_openvds_LogHandler_dtorImpl
  (JNIEnv * env, jobject object, jlong native_handle, jboolean is_disposing)
{
  JNIEnvGuard
    envGuard(env);

  CPPJNI_TRY
  {
    CPPJNI_destroyHandle<OpenVDS::LogHandler>(native_handle, is_disposing);
  }
  CPPJNI_CATCH
}



#ifdef __cplusplus
}
#endif
