macro(BuildAbsl)
  if (WIN32)
  list(APPEND ABSL_LIBS_LIST "lib/absl_int128.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_strings.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_strings_internal.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_str_format_internal.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_bad_optional_access.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_bad_variant_access.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_time.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_time_zone.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_throw_delegate.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_raw_logging_internal.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_string_view.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_crc32c.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_crc_internal.lib")
  elseif (APPLE)
  list(APPEND ABSL_DLLS_LIST "lib/absl_int128_a.a")
  list(APPEND ABSL_DLLS_LIST "lib/absl_strings_a.a")
  list(APPEND ABSL_DLLS_LIST "lib/absl_strings_internal_a.a")
  list(APPEND ABSL_DLLS_LIST "lib/absl_str_format_internal_a.a")
  list(APPEND ABSL_DLLS_LIST "lib/absl_bad_optional_access_a.a")
  list(APPEND ABSL_DLLS_LIST "lib/absl_bad_variant_access_a.a")
  list(APPEND ABSL_DLLS_LIST "lib/absl_time_a.a")
  list(APPEND ABSL_DLLS_LIST "lib/absl_time_zone_a.a")
  list(APPEND ABSL_DLLS_LIST "lib/absl_throw_delegate_a.a")
  list(APPEND ABSL_DLLS_LIST "lib/absl_raw_logging_internal_a.a")
  list(APPEND ABSL_DLLS_LIST "lib/absl_string_view_a.a")
  list(APPEND ABSL_DLLS_LIST "lib/absl_crc32c_a.a")
  list(APPEND ABSL_DLLS_LIST "lib/absl_crc_internal_a.a")
  else()
  list(APPEND ABSL_DLLS_LIST "lib${LIBSUFFIX}/absl_int128_a.a")
  list(APPEND ABSL_DLLS_LIST "lib${LIBSUFFIX}/absl_strings_a.a")
  list(APPEND ABSL_DLLS_LIST "lib${LIBSUFFIX}/absl_strings_internal_a.a")
  list(APPEND ABSL_DLLS_LIST "lib${LIBSUFFIX}/absl_str_format_internal_a.a")
  list(APPEND ABSL_DLLS_LIST "lib${LIBSUFFIX}/absl_bad_variant_access_a.a")
  list(APPEND ABSL_DLLS_LIST "lib${LIBSUFFIX}/absl_bad_optional_access_a.a")
  list(APPEND ABSL_DLLS_LIST "lib${LIBSUFFIX}/absl_time_a.a")
  list(APPEND ABSL_DLLS_LIST "lib${LIBSUFFIX}/absl_time_zone_a.a")
  list(APPEND ABSL_DLLS_LIST "lib${LIBSUFFIX}/absl_throw_delegate_a.a")
  list(APPEND ABSL_DLLS_LIST "lib${LIBSUFFIX}/absl_raw_logging_internal_a.a")
  list(APPEND ABSL_DLLS_LIST "lib${LIBSUFFIX}/absl_string_view_a.a")
  list(APPEND ABSL_DLLS_LIST "lib${LIBSUFFIX}/absl_crc32c_a.a")
  list(APPEND ABSL_DLLS_LIST "lib${LIBSUFFIX}/absl_crc_internal_a.a")
  endif()

  list(APPEND CMAKE_ARGS "-DCMAKE_POSITION_INDEPENDENT_CODE=ON")
  list(APPEND CMAKE_ARGS "-DBUILD_SHARED_LIBS=OFF")
  BuildExternal(absl ${absl_VERSION} "" ${absl_SOURCE_DIR} "${ABSL_LIBS_LIST}" "${ABSL_DLLS_LIST}" ON "${CMAKE_ARGS}")
endmacro()
