function(BuildLibreSSL)
  if (USE_LIBRESSL)
    get_property(_isMultiConfig GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
    if (WIN32)
      list(APPEND LIBRESSL_LIBS_LIST "lib/crypto-49.lib")
      list(APPEND LIBRESSL_LIBS_LIST "lib/tls-25.lib")

      list(APPEND LIBRESSL_DLLS_LIST "bin/crypto-49.dll")
      list(APPEND LIBRESSL_DLLS_LIST "bin/tls-25.dll")
      list(APPEND LIBRESSL_DLLS_LIST "bin/ssl-52.dll")
    else()
      list(APPEND LIBRESSL_DLLS_LIST "lib${LIBSUFFIX}/libcrypto.so.47.0.0")
      list(APPEND LIBRESSL_DLLS_LIST "lib${LIBSUFFIX}/libcrypto.so.47")
      list(APPEND LIBRESSL_DLLS_LIST "lib${LIBSUFFIX}/libtls.so.22.0.0")
      list(APPEND LIBRESSL_DLLS_LIST "lib${LIBSUFFIX}/libtls.so.22")
      list(APPEND LIBRESSL_DLLS_LIST "lib${LIBSUFFIX}/libssl.so.50.0.0")
      list(APPEND LIBRESSL_DLLS_LIST "lib${LIBSUFFIX}/libssl.so.50")
    endif()

    list(APPEND CMAKE_ARGS "-DLIBRESSL_APPS=OFF")
    list(APPEND CMAKE_ARGS "-DLIBRESSL_TESTS=OFF")
    list(APPEND CMAKE_ARGS "-DBUILD_SHARED_LIBS=ON")
    BuildExternal(libressl ${libressl_VERSION} "" ${libressl_SOURCE_DIR} "${LIBRESSL_LIBS_LIST}" "${LIBRESSL_DLLS_LIST}" ON "${CMAKE_ARGS}")
    set(LIBRESSL_ROOT ${libressl_INSTALL_INT_CONFIG} PARENT_SCOPE)
  endif()

endfunction()
