function(BuildLibUV)
  if (NOT BUILD_UV)
    return()
  endif()
  get_property(isMultiConfig GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
  if (WIN32)
    list(APPEND LIBUV_LIBS_LIST "lib/uv.lib")
    list(APPEND LIBUV_DLLS_LIST "bin/uv.dll")
  elseif (APPLE)
    list(APPEND LIBUV_DLLS_LIST "lib/libuv.dylib")
  else()
    list(APPEND LIBUV_DLLS_LIST "lib/libuv.so.1.0.0")
  endif()

  BuildExternal(libuv ${libuv_VERSION} "" ${libuv_SOURCE_DIR} "${LIBUV_LIBS_LIST}" "${LIBUV_DLLS_LIST}" ON "")
endfunction()
