include(CMake/BuildExternal.cmake)
if (BUILD_ZLIB)
  include(CMake/BuildZlib.cmake)
endif()
if (NOT EMSCRIPTEN)
  include(CMake/BuildCurl.cmake)
  include(CMake/BuildAWSSDK.cmake)
  include(CMake/BuildJsonCpp.cmake)
  include(CMake/BuildFmt.cmake)
  include(CMake/BuildCppRestSdk.cmake)
  include(CMake/BuildAzure.cmake)
  include(CMake/BuildLibUV.cmake)
  include(CMake/BuildLibreSSL.cmake)
  include(CMake/BuildCrc32c.cmake)
  include(CMake/BuildGoogleCloud.cmake)
  include(CMake/BuildDms.cmake)
  if (BUILD_LIBXML)
    include(CMake/BuildLibXML2.cmake)
  endif()
  include(CMake/BuildAzureSdkForCpp.cmake)
endif()

macro(build3rdparty)
  if (BUILD_ZLIB)
    BuildZlib()
  endif()

  if (NOT EMSCRIPTEN)
    BuildJsonCPP()
    BuildFmt()

    if (Python3_FOUND)
      add_subdirectory(${pybind11_SOURCE_DIR} ${PROJECT_BINARY_DIR}/pybind11_${pybind11_VERSION} EXCLUDE_FROM_ALL)
    endif()
  
    if (NOT DISABLE_CURL_IOMANAGER OR NOT DISABLE_GCP_IOMANAGER OR NOT DISABLE_DMS_IOMANAGER)
      BuildCurl()
      BuildLibUV()
    endif()

    if (NOT DISABLE_AWS_IOMANAGER)
      BuildAwsSdk()
    endif()

    if (NOT DISABLE_AZURE_IOMANAGER)
      BuildCppRestSdk()
      BuildAzure()
    endif()

    if (NOT DISABLE_GCP_IOMANAGER OR NOT DISABLE_DMS_IOMANAGER)
      BuildLibreSSL()
      BuildCrc32c()
      BuildGoogleCloud()
    endif()

    if (NOT DISABLE_AZURESDKFORCPP_IOMANAGER)
      if (BUILD_LIBXML)
        BuildLibXML2()
      endif()
      BuildAzureSdkForCpp()
    endif()
  
    if (NOT DISABLE_DMS_IOMANAGER)
      BuildDms()
    endif()

    include(${cmakerc_SOURCE_DIR}/CMakeRC.cmake)
  endif()
endmacro()
