macro(BuildAbsl)
  if (WIN32)
  list(APPEND ABSL_LIBS_LIST "lib/absl_raw_logging_internal.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_time_zone.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_time.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_crc_internal.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_crc32c.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_crc_cord_state.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_crc_cpu_detect.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_int128.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_strings.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_strings_internal.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_str_format_internal.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_bad_variant_access.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_bad_optional_access.lib")
  list(APPEND ABSL_LIBS_LIST "lib/absl_throw_delegate.lib")
  elseif (APPLE)
  list(APPEND ABSL_LIBS_LIST "lib/libabsl_raw_logging_internal.a")
  list(APPEND ABSL_LIBS_LIST "lib/libabsl_time_zone.a")
  list(APPEND ABSL_LIBS_LIST "lib/libabsl_time.a")
  list(APPEND ABSL_LIBS_LIST "lib/libabsl_crc_internal.a")
  list(APPEND ABSL_LIBS_LIST "lib/libabsl_crc32c.a")
  list(APPEND ABSL_LIBS_LIST "lib/libabsl_crc_cord_state.a")
  list(APPEND ABSL_LIBS_LIST "lib/libabsl_crc_cpu_detect.a")
  list(APPEND ABSL_LIBS_LIST "lib/libabsl_int128.a")
  list(APPEND ABSL_LIBS_LIST "lib/libabsl_strings.a")
  list(APPEND ABSL_LIBS_LIST "lib/libabsl_strings_internal.a")
  list(APPEND ABSL_LIBS_LIST "lib/libabsl_str_format_internal.a")
  list(APPEND ABSL_LIBS_LIST "lib/libabsl_bad_variant_access.a")
  list(APPEND ABSL_LIBS_LIST "lib/libabsl_bad_optional_access.a")
  list(APPEND ABSL_LIBS_LIST "lib/libabsl_throw_delegate.a")
  else()
  list(APPEND ABSL_LIBS_LIST "lib${LIBSUFFIX}/libabsl_raw_logging_internal.a")
  list(APPEND ABSL_LIBS_LIST "lib${LIBSUFFIX}/libabsl_time_zone.a")
  list(APPEND ABSL_LIBS_LIST "lib${LIBSUFFIX}/libabsl_time.a")
  list(APPEND ABSL_LIBS_LIST "lib${LIBSUFFIX}/libabsl_crc_internal.a")
  list(APPEND ABSL_LIBS_LIST "lib${LIBSUFFIX}/libabsl_crc32c.a")
  list(APPEND ABSL_LIBS_LIST "lib${LIBSUFFIX}/libabsl_crc_cord_state.a")
  list(APPEND ABSL_LIBS_LIST "lib${LIBSUFFIX}/libabsl_crc_cpu_detect.a")
  list(APPEND ABSL_LIBS_LIST "lib${LIBSUFFIX}/libabsl_int128.a")
  list(APPEND ABSL_LIBS_LIST "lib${LIBSUFFIX}/libabsl_strings.a")
  list(APPEND ABSL_LIBS_LIST "lib${LIBSUFFIX}/libabsl_strings_internal.a")
  list(APPEND ABSL_LIBS_LIST "lib${LIBSUFFIX}/libabsl_str_format_internal.a")
  list(APPEND ABSL_LIBS_LIST "lib${LIBSUFFIX}/libabsl_bad_variant_access.a")
  list(APPEND ABSL_LIBS_LIST "lib${LIBSUFFIX}/libabsl_bad_optional_access.a")
  list(APPEND ABSL_LIBS_LIST "lib${LIBSUFFIX}/libabsl_throw_delegate.a")
  endif()

  list(APPEND CMAKE_ARGS "-DCMAKE_POSITION_INDEPENDENT_CODE=ON")
  list(APPEND CMAKE_ARGS "-DBUILD_SHARED_LIBS=OFF")
  list(APPEND CMAKE_ARGS "-DCMAKE_CXX_STANDARD=14")
  list(APPEND CMAKE_ARGS "-DCMAKE_CXX_FLAGS=-Doff64_t=off_t")
  BuildExternal(absl ${absl_VERSION} "" ${absl_SOURCE_DIR} "${ABSL_LIBS_LIST}" "${ABSL_DLLS_LIST}" ON "${CMAKE_ARGS}")
endmacro()
