function(BuildAzureSdkForCpp)
  if (WIN32)
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-core.lib")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-identity.lib")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-security-keyvault-certificates.lib")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-security-keyvault-keys.lib")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-security-keyvault-secrets.lib")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-storage-blobs.lib")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-storage-common.lib")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-storage-files-datalake.lib")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-storage-files-shares.lib")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-storage-queues.lib")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-template.lib")

    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-core.dll")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-identity.dll")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-security-keyvault-certificates.dll")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-security-keyvault-keys.dll")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-security-keyvault-secrets.dll")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-storage-blobs.dll")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-storage-common.dll")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-storage-files-datalake.dll")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-storage-files-shares.dll")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-storage-queues.dll")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-template.dll")
  elseif (APPLE)
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib/libazure-core.dylib")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib/libazure-identity.dylib")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib/libazure-security-keyvault-certificates.dylib")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib/libazure-security-keyvault-keys.dylib")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib/libazure-security-keyvault-secrets.dylib")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib/libazure-storage-blobs.dylib")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib/libazure-storage-common.dylib")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib/libazure-storage-files-datalake.dylib")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib/libazure-storage-files-shares.dylib")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib/libazure-storage-queues.dylib")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib/libazure-template.dylib")
  else()
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib${LIBSUFFIX}/libazure-core.so")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib${LIBSUFFIX}/libazure-identity.so")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib${LIBSUFFIX}/libazure-security-keyvault-certificates.so")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib${LIBSUFFIX}/libazure-security-keyvault-keys.so")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib${LIBSUFFIX}/libazure-security-keyvault-secrets.so")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib${LIBSUFFIX}/libazure-storage-blobs.so")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib${LIBSUFFIX}/libazure-storage-common.so")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib${LIBSUFFIX}/libazure-storage-files-datalake.so")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib${LIBSUFFIX}/libazure-storage-files-shares.so")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib${LIBSUFFIX}/libazure-storage-queues.so")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "lib${LIBSUFFIX}/libazure-template.so")
  endif()
  if (BUILD_LIBXML)
    set(DEPENDENCIES libxml2)
  endif()
  if (OPENSSL_ROOT_DIR)
    set(OPENSSL_CMAKE ";-DOPENSSL_ROOT_DIR=${OPENSSL_ROOT_DIR}")
    message("OPENSSL_ROOT_DIR ${OPENSSL_ROOT_DIR}")
  endif()
  if (APPLE)
    set(MAC_RPATH ";-DCMAKE_MACOSX_RPATH=ON")
  endif()
  if (BUILD_CURL)
    list(APPEND DEPENDENCIES curl)
    set (CURL_ARGS ";-DCURL_DIR=${curl_root}")
    if (WIN32)
      set (CURL_ARGS "${CURL_ARGS};-DCMAKE_SHARED_LINKER_FLAGS=Ws2_32.lib")
    endif()
  endif()
  BuildExternal(azure-sdk-for-cpp ${azure-sdk-for-cpp_VERSION} "${DEPENDENCIES}" ${azure-sdk-for-cpp_SOURCE_DIR} "${AZURE_SDK_FOR_CPP_LIBS_LIST}" "${AZURE_SDK_FOR_CPP_DLLS_LIST}" ON "-DLibXml2_DIR=${libxml2_root};-DBUILD_SHARED_LIBS=ON;-DCMAKE_FIND_PACKAGE_PREFER_CONFIG=ON;-DBUILD_TESTING=OFF;-DBUILD_SAMPLES=OFF;-DBUILD_TRANSPORT_CURL=ON;-DDISABLE_AZURE_CORE_OPENTELEMETRY=ON${OPENSSL_CMAKE}${MAC_RPATH}${CURL_ARGS}")
endfunction()
