function(BuildCurl)
  if (NOT BUILD_CURL)
    return()
  endif()
  if (WIN32)
    set(PLATFORM_OPTIONS ";-DCMAKE_USE_SCHANNEL=ON")
    list(APPEND CURL_LIBS_LIST_RELEASE "lib/libcurl$<$<CONFIG:Debug>:-d>_imp.lib")
    list(APPEND CURL_DLLS_LIST_RELEASE "bin/libcurl$<$<CONFIG:Debug>:-d>.dll")
  else()
    set(PLATFORM_OPTIONS ";-DCURL_CA_BUNDLE=none;-DCURL_CA_PATH=none;-DCURL_CA_FALLBACK=ON")
    list(APPEND CURL_DLLS_LIST_RELEASE "lib${LIBSUFFIX}/libcurl$<$<CONFIG:Debug>:-d>.so")
  endif()

  BuildExternal(curl ${curl_VERSION} "" ${curl_SOURCE_DIR} "${CURL_LIBS_LIST_RELEASE}" "${CURL_DLLS_LIST_RELEASE}" ON "-DBUILD_CURL_EXE=OFF;-DHTTP_ONLY=ON;-DBUILD_TESTING=OFF${PLATFORM_OPTIONS}")
  set(curl_INSTALL_INT_CONFIG ${curl_INSTALL_INT_CONFIG} PARENT_SCOPE)
endfunction()
