macro(BuildAWSSDK)
  if (WIN32)
    list(APPEND AWS_LIBS_LIST "lib/aws-c-auth.lib")
    list(APPEND AWS_LIBS_LIST "lib/aws-c-cal.lib")
    list(APPEND AWS_LIBS_LIST "lib/aws-c-common.lib")
    list(APPEND AWS_LIBS_LIST "lib/aws-c-compression.lib")
    list(APPEND AWS_LIBS_LIST "lib/aws-c-event-stream.lib")
    list(APPEND AWS_LIBS_LIST "lib/aws-c-http.lib")
    list(APPEND AWS_LIBS_LIST "lib/aws-c-io.lib")
    list(APPEND AWS_LIBS_LIST "lib/aws-c-mqtt.lib")
    list(APPEND AWS_LIBS_LIST "lib/aws-c-s3.lib")
    list(APPEND AWS_LIBS_LIST "lib/aws-c-sdkutils.lib")
    list(APPEND AWS_LIBS_LIST "lib/aws-checksums.lib")
    list(APPEND AWS_LIBS_LIST "lib/aws-cpp-sdk-core.lib")
    list(APPEND AWS_LIBS_LIST "lib/aws-cpp-sdk-s3.lib")
    list(APPEND AWS_LIBS_LIST "lib/aws-cpp-sdk-sts.lib")
    list(APPEND AWS_LIBS_LIST "lib/aws-cpp-sdk-transfer.lib")
    list(APPEND AWS_LIBS_LIST "lib/aws-crt-cpp.lib")
  elseif (APPLE)
    list(APPEND AWS_DLLS_LIST "lib/libaws-c-common.a")
    list(APPEND AWS_DLLS_LIST "lib/libaws-checksums.a")
    list(APPEND AWS_DLLS_LIST "lib/libaws-c-sdkutils.a")
    list(APPEND AWS_DLLS_LIST "lib/libaws-c-event-stream.a")
    list(APPEND AWS_DLLS_LIST "lib/libaws-c-compression.a")
    list(APPEND AWS_DLLS_LIST "lib/libaws-c-cal.a")
    list(APPEND AWS_DLLS_LIST "lib/libaws-c-io.a")
    list(APPEND AWS_DLLS_LIST "lib/libaws-c-http.a")
    list(APPEND AWS_DLLS_LIST "lib/libaws-c-auth.a")
    list(APPEND AWS_DLLS_LIST "lib/libaws-c-mqtt.a")
    list(APPEND AWS_DLLS_LIST "lib/libaws-c-s3.a")
    list(APPEND AWS_DLLS_LIST "lib/libaws-crt-cpp.a")
    list(APPEND AWS_DLLS_LIST "lib/libaws-cpp-sdk-core.a")
    list(APPEND AWS_DLLS_LIST "lib/libaws-cpp-sdk-s3.a")
    list(APPEND AWS_DLLS_LIST "lib/libaws-cpp-sdk-transfer.a")
    list(APPEND AWS_DLLS_LIST "lib/libaws-cpp-sdk-sts.a")
  else()
    if (BUILD_CURL)
      list(APPEND AWS_CMAKE_PREFIX_PATH "${curl_INSTALL_INT_CONFIG}")
      list(APPEND PLATFORM_CMAKE_ARGS "-DCURL_LIBRARY=${curl_INSTALL_LIBRARY}")
      set(PLATFORM_DEPNDS "curl")
    endif()
    list(APPEND AWS_DLLS_LIST "lib${LIBSUFFIX}/libs2n.a")
    list(APPEND AWS_DLLS_LIST "lib${LIBSUFFIX}/libaws-c-common.a")
    list(APPEND AWS_DLLS_LIST "lib${LIBSUFFIX}/libaws-checksums.a")
    list(APPEND AWS_DLLS_LIST "lib${LIBSUFFIX}/libaws-c-sdkutils.a")
    list(APPEND AWS_DLLS_LIST "lib${LIBSUFFIX}/libaws-c-event-stream.a")
    list(APPEND AWS_DLLS_LIST "lib${LIBSUFFIX}/libaws-c-compression.a")
    list(APPEND AWS_DLLS_LIST "lib${LIBSUFFIX}/libaws-c-cal.a")
    list(APPEND AWS_DLLS_LIST "lib${LIBSUFFIX}/libaws-c-io.a")
    list(APPEND AWS_DLLS_LIST "lib${LIBSUFFIX}/libaws-c-http.a")
    list(APPEND AWS_DLLS_LIST "lib${LIBSUFFIX}/libaws-c-auth.a")
    list(APPEND AWS_DLLS_LIST "lib${LIBSUFFIX}/libaws-c-mqtt.a")
    list(APPEND AWS_DLLS_LIST "lib${LIBSUFFIX}/libaws-c-s3.a")
    list(APPEND AWS_DLLS_LIST "lib${LIBSUFFIX}/libaws-crt-cpp.a")
    list(APPEND AWS_DLLS_LIST "lib${LIBSUFFIX}/libaws-cpp-sdk-core.a")
    list(APPEND AWS_DLLS_LIST "lib${LIBSUFFIX}/libaws-cpp-sdk-transfer.a")
    list(APPEND AWS_DLLS_LIST "lib${LIBSUFFIX}/libaws-cpp-sdk-sts.a")
    list(APPEND AWS_DLLS_LIST "lib${LIBSUFFIX}/libaws-cpp-sdk-s3.a")
  endif()

  if (OPENSSL_ROOT_DIR)
    list(APPEND PLATFORM_CMAKE_ARGS "-DOPENSSL_ROOT_DIR=${OPENSSL_ROOT_DIR}")
    list(APPEND AWS_CMAKE_PREFIX_PATH "${OPENSSL_ROOT_DIR}")
  endif()


  if (OPENSSL_USE_STATIC_LIBS)
    list(APPEND PLATFORM_CMAKE_ARGS "-DOPENSSL_USE_STATIC_LIBS=ON")
  endif()

  list(APPEND PLATFORM_CMAKE_ARGS "-DBUILD_SHARED_LIBS=OFF")
  list(APPEND PLATFORM_CMAKE_ARGS "-DBUILD_ONLY=s3$<SEMICOLON>sts$<SEMICOLON>transfer")
  list(APPEND PLATFORM_CMAKE_ARGS "-DENABLE_TESTING=OFF")
  list(APPEND PLATFORM_CMAKE_ARGS "-DCMAKE_C_VISIBILITY_PRESET=hidden")
  list(APPEND PLATFORM_CMAKE_ARGS "-DCMAKE_CXX_VISIBILITY_PRESET=hidden")

  if (ENABLE_ASAN)
    list(APPEND PLATFORM_CMAKE_ARGS "-DENABLE_ADDRESS_SANITIZER=ON")
  endif()

  if (NOT AWS_CMAKE_PREFIX_PATH)
    list(APPEND AWS_CMAKE_PREFIX_PATH "AWS_FOOBAR") #this is to work around a performance problem when building on the builders
  endif()

  list(APPEND PLATFORM_CMAKE_ARGS "-DCURL_NO_CURL_CMAKE=ON")
  string(REPLACE ";" "$<SEMICOLON>" AWS_CMAKE_PREFIX_PATH "${AWS_CMAKE_PREFIX_PATH}")
  list(APPEND PLATFORM_CMAKE_ARGS "-DCMAKE_PREFIX_PATH=${AWS_CMAKE_PREFIX_PATH}")
  BuildExternal(aws-cpp-sdk ${aws-cpp-sdk_VERSION} "${PLATFORM_DEPNDS}" ${aws-cpp-sdk_SOURCE_DIR} "${AWS_LIBS_LIST}" "${AWS_DLLS_LIST}" OFF "${PLATFORM_CMAKE_ARGS}")

  if (WIN32)
    list(APPEND aws-cpp-sdk_EXTERNAL_LIBS "winhttp")
    list(APPEND aws-cpp-sdk_EXTERNAL_LIBS "wininet")
    list(APPEND aws-cpp-sdk_EXTERNAL_LIBS "shlwapi")
    list(APPEND aws-cpp-sdk_EXTERNAL_LIBS "secur32")
    list(APPEND aws-cpp-sdk_EXTERNAL_LIBS "userenv")
    list(APPEND aws-cpp-sdk_EXTERNAL_LIBS "version")
    list(APPEND aws-cpp-sdk_EXTERNAL_LIBS "ncrypt")
    list(APPEND aws-cpp-sdk_EXTERNAL_LIBS "iphlpapi")

  elseif (APPLE)
    list(APPEND aws-cpp-sdk_EXTERNAL_LIBS "-framework CoreFoundation")
    list(APPEND aws-cpp-sdk_EXTERNAL_LIBS "-framework SystemConfiguration")
    list(APPEND aws-cpp-sdk_EXTERNAL_LIBS "-framework Security")
  elseif(OPENVDS_AWS_BUILD_DYNAMIC)
    list(APPEND aws-cpp-sdk_EXTERNAL_LIBS "crypto")
    if (NOT BUILD_CURL)
      list(APPEND aws-cpp-sdk_EXTERNAL_LIBS "curl")
    endif()
  endif()
endmacro()
