function(BuildAzureSdkForCpp)
  if (WIN32)
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-core.lib")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-identity.lib")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-security-keyvault-common.lib")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-security-keyvault-keys.lib")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-storage-blobs.lib")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-storage-common.lib")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-storage-files-datalake.lib")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-storage-files-shares.lib")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib/azure-template.lib")

    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-core.dll")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-identity.dll")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-security-keyvault-common.dll")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-security-keyvault-keys.dll")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-storage-blobs.dll")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-storage-common.dll")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-storage-files-datalake.dll")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-storage-files-shares.dll")
    LIST(APPEND AZURE_SDK_FOR_CPP_DLLS_LIST "bin/azure-template.dll")
  elseif (APPLE)
  else()
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib${LIBSUFFIX}/libazure-core.so")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib${LIBSUFFIX}/libazure-storage-common.so")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib${LIBSUFFIX}/libazure-template.so")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib${LIBSUFFIX}/libazure-identity.so")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib${LIBSUFFIX}/libazure-security-keyvault-common.so")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib${LIBSUFFIX}/libazure-security-keyvault-keys.so")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib${LIBSUFFIX}/libazure-storage-blobs.so")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib${LIBSUFFIX}/libazure-storage-files-datalake.so")
    LIST(APPEND AZURE_SDK_FOR_CPP_LIBS_LIST "lib${LIBSUFFIX}/libazure-storage-files-shares.so")
  endif()
  if (BUILD_LIBXML)
    set(DEPENDENCIES libxml2)
  endif()
  BuildExternal(azure-sdk-for-cpp ${azure-sdk-for-cpp_VERSION} "${DEPENDENCIES}" ${azure-sdk-for-cpp_SOURCE_DIR} "${AZURE_SDK_FOR_CPP_LIBS_LIST}" "${AZURE_SDK_FOR_CPP_DLLS_LIST}" "" "" "${cmake_arg};-DLibXml2_DIR=${libxml2_root};-DBUILD_SHARED_LIBS=ON;-DCMAKE_FIND_PACKAGE_PREFER_CONFIG=ON")
endfunction()
