macro(BuildGoogleCloud)
  get_property(isMultiConfig GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
  if (WIN32)
  list(APPEND GCP_LIBS_LIST "lib/google_cloud_ovds.lib")
  elseif (APPLE)
  list(APPEND GCP_DLLS_LIST "lib/google_cloud_ovds_a.a")
  else()
  list(APPEND GCP_DLLS_LIST "lib${LIBSUFFIX}/google_cloud_ovds_a.a")
  endif()

  set(GCP_CMAKE_ARGS ${CMAKE_ARGS} -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} -DGCP_VERSION=${google-cloud-cpp_VERSION} -DGCP_SOURCE_DIR=${google-cloud-cpp_SOURCE_DIR})

  list(APPEND gcp_depends crc32c)
  list(APPEND gcp_depends absl)
  list(APPEND GCP_CMAKE_PREFIX_PATH "${crc32c_INSTALL_INT_CONFIG}")
  list(APPEND GCP_CMAKE_PREFIX_PATH "${absl_INSTALL_INT_CONFIG}")

  if(BUILD_CURL)
    list(APPEND gcp_depends curl)
    list(APPEND GCP_CMAKE_PREFIX_PATH "${curl_INSTALL_INT_CONFIG}")
  endif()

  if (USE_LIBRESSL)
    list(APPEND gcp_depends libressl)
    list(APPEND GCP_CMAKE_ARGS "-DGCP_DEPINSTALL=${libressl_INSTALL_INT_CONFIG}")
    list(APPEND GCP_CMAKE_PREFIX_PATH "${libressl_INSTALL_INT_CONFIG}")
  endif()

  if (BUILD_OPENSSL)
    list(APPEND gcp_depends openssl)
    list(APPEND GCP_CMAKE_PREFIX_PATH "${OPENSSL_ROOT_DIR}")
  endif()

  message(STATUS "GCP_CMAKE_ARGS:${GCP_CMAKE_ARGS}")
  message(STATUS "gcp_depends:${gcp_depends}")

  string(REPLACE ";" "\\$<SEMICOLON>" GCP_CMAKE_PREFIX_PATH "${GCP_CMAKE_PREFIX_PATH}")
  list(APPEND GCP_CMAKE_ARGS "-DCMAKE_POSITION_INDEPENDENT_CODE=ON")
  list(APPEND GCP_CMAKE_ARGS "-DBUILD_SHARED_LIBS=OFF")
  list(APPEND GCP_CMAKE_ARGS "-Dgoogle_nlohmann_SOURCE_DIR=${google_nlohmann_SOURCE_DIR}")
  list(APPEND GCP_CMAKE_ARGS "-DCMAKE_PREFIX_PATH=${GCP_CMAKE_PREFIX_PATH}")
  list(APPEND CMAKE_ARGS "-DCMAKE_CXX_STANDARD=14")
  BuildExternal(google_cloud_ovds ${google-cloud-cpp_VERSION} "${gcp_depends}" "${google-cloud-cpp_SOURCE_DIR}/../BuildGoogleCloud" "${GCP_LIBS_LIST}" "${GCP_DLLS_LIST}" ON "${GCP_CMAKE_ARGS}")
endmacro()
