function(setWarningFlagsForTarget target)
  if (DISABLE_STRICT_WARNINGS)
    return()
  endif()
  if (MSVC)
    openvds_target_compile_options(${target} PRIVATE /W3)
    openvds_target_compile_options(${target} PRIVATE /WX)
  else()
    openvds_target_compile_options(${target} PRIVATE -Wall -Wextra -pedantic -Werror -Wno-unused-parameter -fms-extensions)
  endif()
endfunction()
